### ISSUE TITLE
Web3 Signer integration updates for merge

### ISSUE THREAD

**Issue by james-prysm** [prysmaticlabs/prysm#10053]
# 💎 Issue

### Background

This issue tracks changes for web3signer with regards to the merge

### Description
 we will need to update the types to include the block v3 type 
also the block body for the request will need to change; reference to the following issue below.
https://github.com/ConsenSys/web3signer/issues/437
https://github.com/ConsenSys/web3signer/issues/459
https://github.com/ConsenSys/web3signer/pull/606

Bellatrix changes https://github.com/ConsenSys/teku/pull/5354
> For Bellatrix fork, send block_header instead of block for external signer block signing request (BLOCK_V2). block_header contains body_root instead of complete beacon block body which significantly reduces the traffic between Teku and external signer for block signing request.

> Either block_header or block can be used to calculate signing root by the external signer. For backward compatibility with PHASE0 and ALTAIR forks, only block is sent; for Bellatrix and later forks, only block_header is sent.

Prysm uses BLOCK_V3 Instead

## Tasks
- [x] manage bellatrix blocks ( blockv3/ handling block body to block header in payload)
- [x] handling blinded blocks
- [ ] [validator registration signing](https://github.com/ConsenSys/web3signer/issues/577) ( MEV/Builder)

**Comment by ItalianHamma777** [comment]
hello

**Comment by ItalianHamma777** [comment]
good work man, im new but i love this
