### ISSUE TITLE
Benchmark code tracking issue

### ISSUE THREAD

**Issue by potuz** [prysmaticlabs/prysm#10095]
# 🦄 Tracking Issue

## Description

We need several meaningful and realistic (eg. close to mainnet) benchmarks to track performance and regressions/improvements by a given PR.  There are many areas of code that can/should be benchmarked. This issue will grow accordingly we find more items to cover

## Benchmarks

- [ ] Full state transition (inner slot)
- [ ] Epoch transition
- [ ] Beacon Block verification
- [ ] SSZ objects (un)marshalling
- [ ] SSZ objects htr computation
- [ ] Block batch syncing
- [ ] State retrieval from DB

## Todo

Think about possible P2P/gossiping benchmarks

This issue should be closed after all of the above tasks are complete.
