### ISSUE TITLE
[Tracking] Native Beacon State - things not to forget

### ISSUE THREAD

**Issue by rkapka** [prysmaticlabs/prysm#10100]
The Native Beacon State feature is quite large and, especially with the introduction of a feature flag, changes will be rolled out slowly over several months. Sometimes we may have to temporarily remove some code or change existing behavior, but we mustn't forget to eventually roll back the code or reach the ultimate solution. This issue serves as a tracking issue for all such details.

- [ ] eventually remove `SafeCopyRootAtIndex` and wrappers around `ToProto` and `ToProtoUnsafe`
- [ ] bring back `TestAppendBeyondIndicesLimit` - https://github.com/prysmaticlabs/prysm/pull/10086#discussion_r786590264
- [ ] take a closer look at copies such as https://github.com/prysmaticlabs/prysm/pull/10086#discussion_r784884850; can they be avoided?
- [ ] `type Byte32 [32]byte` is not needed and `genesisValidatorsRoot` can simply be of type `[32]byte`
- [ ] move over fuzz tests introduced in https://github.com/prysmaticlabs/prysm/pull/10375

**Comment by rauljordan** [comment]
hi @rkapka whats the status of this one?

**Comment by rkapka** [comment]
Hi, this will be done once we deprecate the native state.
