### ISSUE TITLE
[Feature Flag Tracking] `enable-native-state`

### ISSUE THREAD

**Issue by rkapka** [prysmaticlabs/prysm#10231]
# 🦄 Feature Tracking

**Current status** (opt-in or opt-out): 

opt-out

**Opt-in feature flag name**:

`enable-use-native-state`

**Opt-out feature flag name**: 

`disable-use-native-state`

### Feature Description

See design doc: https://www.notion.so/prysmaticlabs/Native-Beacon-State-Redesign-6cc9744b4ec1439bb34fa829b36a35c1

### Tasks

- [x] Feature flag created as opt-in
- [x] Feature implemented / code complete
- [x] Feature tested in production for adequate amount of time
- [x] Feature flag is inverted to be opt-out and the opt-in flag is deprecated
- [x] Feature has made it to a tagged production release as an opt-out flag
- [x] Opt-out feature flag is deprecated and old code paths are cleaned up

This issue should be closed after all of the above tasks are complete.
