### ISSUE TITLE
Merge Issue Tracking

### ISSUE THREAD

**Issue by terencechain** [prysmaticlabs/prysm#10242]
**Spec:**
- [x] Pass consensus spec v1.1.9 spec tests
- [x] Pass consensus spec v1.1.10 spec tests #10298
- [x] Pass bellatrix forkchoice spec tests #forkchoice #10284
- [x] Rename receipt_root -> receipts_root
- [x] Rename execute_payload -> notify_new_payload

**Engine API:**
- [x] Support authentication for engine API #10236
- [x] Use `engine_exchangeTransitionConfigurationV1` to check EL config
- [x] Handle nil cases and`payloadStatus` invalid in respond
- [x] Unify --execution-provider and --http-web3provider
- [x] Better status, error and nil handling for responses
- [x] Update to kiln v2
 - [x] Review endianess conversations. More places are doing this wrong
 - [x] Call fcu as part of processing attestations and updating head
 - [x] Log out time taken for calls to the execution node in the critical paths.
 - [x] Add in tracing for execution node calls.

**Optimistic sync:**
- [x] Can optimistically sync beacon node under various scenarios 
- [x] Validator assignments are blocked under optimistic mode #10200
- [x] Can remove invalid `SYNCING/ACCEPTED` blocks
- [ ] Beacon APIs can properly respond under optimistic mode
- [x] Optimistically import any post-merge block https://github.com/ethereum/consensus-specs/pull/2844
- [x] P2p scorer and gossip pub beacon block under optimistic mode #10274
- [x] Beacon block sync validation under optimistic mode #10233
- [x] Sync service should still pass block with optimistic parent to blockchain service
- [ ] Retrospective transition block checking
- [x] Ensuring sync gracefully handles an offline EE (gracefully handle offline EE w/o penalizing innocent peers or wasting resources). Pause sync when execution layer is offline?
- [ ] #10487

**Web3signer**
- [x] add BLOCK_V3 mapping for web3signer refer to tracking issue #10053 
- [x] update Web3Signer binary for web3signer
- [x] remove condition check in e2e that stops tests right before Bellatrix

**Code health:**
- [x] Clean up process block with optimistic sync
- [ ] Cache eth1 hash and total difficulty for validator finding terminal transition block
- [ ] Set a max allowance for looking back to find terminal transition block
- [ ] Context timeout doesn't fail validator duty

**UX:**
- [x] Add `--kiln-testnet` flag
- [ ] Complete fee recipient tasks #10292
- [x] Check for terminal block during proposer preparation #10497 
- [x] Don't call fcu update twice to propose block #10481 
- [ ] Investiate why payload ID cache hit/miss ratio is not 100%
- [x] Improve logging. 
    - [x] Identify beacon block with non empty payload
    - [ ] Estimate time to TTD and log it
    - [ ] What else?

**Testing:**
- [ ] Support e2e test pass Bellatrix epoch and reach ttd
- [ ] Differential fuzz engine API req/res
- [ ] Test generator Bellatrix version block
- [x] Transaction Generator for execution nodes.
- [ ] Configurable tool to trigger optimistic sync.

**Eth2 API**
- [x] Update all the Bellatrix related beacon endpoints
- [x] Update all the Bellatrix related validator endpoints
- [x] Update all the Bellatrix related debug endpoints
- [x] Add `is_optimistic` field to all relevant endpoints 

**Prysm API**
- [x] Update all the Bellatrix related beacon endpoints

**Bugs**
- [ ] Beacon block's eth1 data hash is 0s
- [x] TTD checks are being bypassed in e2e
- [x] If the execution engine has a restart, prysm stalls and does nothing.

**Final:**
- [x] Cont merging `kiln` to `develop` (mostly go.mod changes)

Kiln spec: https://hackmd.io/@n0ble/kiln-spec
Milestones tracker: https://notes.ethereum.org/@timbeiko/kiln-milestones
Engine API test vectors: https://notes.ethereum.org/rmVErCfCRPKGqGkUe89-Kg?view

**Comment by james-prysm** [comment]
will start looking at fee recipients ux soon

**Comment by james-prysm** [comment]
Closing due to completion of merge
