### ISSUE TITLE
Make vectorized SHA256 default

### ISSUE THREAD

**Issue by potuz** [prysmaticlabs/prysm#10286]
With #10166 a feature flag to switch to a new hashing library has begun, this would close #9389. There are a few items that need to be fixed in order to make this feature the default feature:

- [ ] Fix the signature of `BitweiseMerkleize` and similar functions' arguments to be `[][32]byte` instead of `[][]byte`. 
- [ ] Avoid copying and allocations of lists as in `MerkleizeList`.
- [ ] Use `[][32]byte` instead of `[]*[32]byte` in the hash Trie layers for the state hash cache. 
- [ ] Better error handling, currently we panic if the hasher receives the wrong length for the output buffer (otherwise it would segfault)

**Comment by rauljordan** [comment]
Hi @potuz can we close this one as completed?

**Comment by potuz** [comment]
Yeah thanks!
