### ISSUE TITLE
Fee Recipient Feature Flag & APIs

### ISSUE THREAD

**Issue by james-prysm** [prysmaticlabs/prysm#10292]
# 🦄 Feature Tracking

part of #10242

**Current status** (opt-in or opt-out): 

**Opt-in feature flag name**:

**Opt-out feature flag name**: 

### Feature Description

Post merge, Eth-Stakers would like to earn rewards ( via gas fees) on particular transactions when proposing ( currently only earning rewards from the protocol itself and not on gas fees). This requires stakers to provide an eth1 account ( the fee recipient) to the validator client either as a catch-all ( all validators default to a particular eth1 account) or unique for each validator key. 

### Flow
config -> validator client -> beacon node  sets the configuration in cache
validator client get block -> beacon node get block with fee recipient -> execution client

## config json structure based on [teku implementation](https://github.com/ConsenSys/teku/pull/4894)
```
{
  "proposer_config": {
    "0xa057816155ad77931185101128655c0191bd0214c201ca48ed887f6c4c6adf334070efcd75140eada5ac83a92506dd7a": {
      "fee_recipient": "0x50155530FCE8a85ec7055A5F8b2bE214B3DaeFd3",
    }
  },
  "default_config": {
    "fee_recipient": "0x6e35733c5af9B61374A128e6F85f553aF09ff89A"
  }
}
```
proposer_config is optional
default_config is mandatory
fee_recipient is mandatory in each config

### Tasks

- [x] `fee-recipient-config-file` flag for fee recipient to provide config file location from validator client cli 
- [x] `fee-recipient-config-url` flg for fee recipient to provide config file via url( api call) from validator client cli 
- [x] `suggested-fee-recipient` to set default fee recipient from validator client cli
- [x] `suggested-fee-recipient` to set default fee recipient from beacon node cli
- [ ] flags to update fee recipient config from cli
- [x] a default 0 address is set if the config is not defined along with loud logs
- [x] BEACON API to see fee recipient cache ( [prepare beacon proposer api](https://github.com/ethereum/beacon-APIs/pull/178))
- [ ] trigger fee recipient update when using the fall back node
- [x] update prepare beacon proposer API for [Flashbots MEV Issue](https://github.com/ethereum/beacon-APIs/pull/206)
- [x] documentation
- [x] e2e tests
This issue should be closed after all of the above tasks are complete.
- [x] Fee recipient Spec for Keymanager API ( https://github.com/ethereum/keymanager-APIs)
- [x] Fee Recipient API implementation

**Comment by james-prysm** [comment]
There is an issue in the upcoming release that is fixed in develop
