### ISSUE TITLE
[Tracking] - Withdrawals

### ISSUE THREAD

**Issue by rkapka** [prysmaticlabs/prysm#11077]
## Accompanying documents

- Official specification: https://github.com/ethereum/consensus-specs/blob/dev/specs/capella/beacon-chain.md
- Feature document: https://www.notion.so/prysmaticlabs/Withdrawals-977373cfaf9e40feba57e19cfc687db5
- Team annotations: https://www.notion.so/prysmaticlabs/Annotations-on-withdrawals-0f967764131d41deace89634d1072b91

### Core changes reflecting the spec
- [x] Add Capella beacon state
- [x] Add Capella beacon block
- [x] Update configuration
- [x] Implement predicates: `has_eth1_withdrawal_credential`, `is_fully_withdrawable_validator`, `is_partially_withdrawable_validator`
- [x] Implement epoch processing: impl. `process_full_withdrawals`, impl. `process_partial_withdrawals`
- [x] Implement block processing: impl `get_expected_withdrawals`, impl. `process_withdrawals`, update `process_execution_payload`, update `process_operations`, impl. `process_bls_to_execution_change`
- [x] Implement `process_bls_to_execution_change`

### Other core changes
- [x] Database: persist and retrieve new objects
- [x] Support from engine client
- [x] Implement p2p code
- [x] Gossip SignedBLSToExecutionChange objects through the p2p network
- [x] Create a pool for SignedBLSToExecutionChange objects
- [x] Perform state transition

### RPC/API
- [x] Implement https://github.com/ethereum/beacon-APIs/pull/248
- [x] Update existing Prysm API endpoints to handle Capella block/state
- [x] Redesign pools since withdrawal and exit look similar #11898
- [x] Support custom builder and builder API https://github.com/prysmaticlabs/prysm/pull/11904

### Misc
- [x] Make sure withdrawals unmarshaling (https://github.com/prysmaticlabs/prysm/pull/11732#discussion_r1045715909) works as expected
- [ ] ~~Add withdrawal support for Web UI?~~ deprioritizing for now, other solutions are coming out.

### prysmctl
- [x] [Allow sending `SignedBLSToExecutionChange` objects to the beacon node through `prysmctl`](https://github.com/prysmaticlabs/prysm/pull/11744)
- [x] allow batch blstoexecutionchange by giving a file directory.
- [x] local devnet testing via ethdo generated signed messages.
- [x] ~~include prysmctl to prysm.sh/prysm.bat #11924~~ removing in favor of directing users to binaries

### Testing
- [x] [e2e](https://github.com/prysmaticlabs/prysm/pull/11951)
- [x] Spec tests
- [x] DOS/Stress test
- [x] Builder test

### Documentation
- [EF WITHDRAWAL PROGRESS](https://notes.ethereum.org/@ralexstokes/SyDqVjr4i)
- [EF WITHDRAWAL CLI PROGRESS](https://notes.ethereum.org/@ralexstokes/B1RlKlXBj)
- [x] [Prysm Capella/Shanghai documentation](https://github.com/prysmaticlabs/documentation/pull/702)

### Discussion
- [withdrawal queue in single function](https://github.com/ethereum/consensus-specs/pull/3042)
- [withdrawal simplification (note* would not require 3042 if included)](https://github.com/ethereum/consensus-specs/pull/3068)
- [staking-cli withdrawal message format](https://github.com/ethereum/staking-deposit-cli/issues/312)

**Comment by potuz** [comment]
The current endpoint `pool/bls_to_execution_changes` in the `capella` branch needs to be hardened to only accept BLS_TO_EXECUTION_CHANGE signed in the right forks. We are happy to take a very early one and then fail to validate it.
