### ISSUE TITLE
Keymanager APIs: gas_limit api

### ISSUE THREAD

**Issue by james-prysm** [prysmaticlabs/prysm#11155]
# 🚀 Feature Request

### Description

Prysm supports a standard set of APIs on the validator client to provide our end users endpoints for their own systems that integrate with prysm but also used for our own prysm web interface.

The newest addition is the gas limit API which is used for custom builders on the validator registry API call.

https://github.com/ethereum/keymanager-APIs/blob/master/apis/gas_limit.yaml 

- [x] get gas limit for the validator key #11156
- [x] set gas limit for the validator key #11208
- [x] delete gas limit for the validator key #11290

### Describe the solution you'd like

keymanager APIs lives under `validator/rpc/standard_api.go`
- a proto will need to be implemented and the associated gateway middleware updated to support this
- will have to account for cases where the custom builder is not enabled as well as if no proposer settings exist as is, see `fee_recipient` API
- delete gas limit will reset the gas limit back to the validator key

**Comment by james-prysm** [comment]
Completed!
