### ISSUE TITLE
Desired Mainnet Merge Metrics Tracking

### ISSUE THREAD

**Issue by rauljordan** [prysmaticlabs/prysm#11367]
# 💎 Issue

## Background

As part of our foray into improving our prometheus metrics for monitoring the merge, we have some more things we want to track in a more granular fashion in Prysm. This is a tracking issue for those items.

### Global Blockchain Health

- [x] Exit queue size (gauge) #11374
- [x] Activation queue size (gauge) #11374

### P2P Insights

- [x] Gossipsub scoring by topic and node (gauge)
- [x] Connected peer score distributions (gauge)
- [x] Inbound / outbound bandwidth libp2p measured in bytes/s (gauge)
- [x] Average peer score per client (gauge) (to be displayed as pie chart)
- [x] Connected peers by client type (gauge) (to be displayed as pie chart)
- [x] P2P RPC requests per slot (gauge)
- [x] Attestation errors per slot (gauge)
- [x] Subscribed peers per topic as pie chart (gauge)
- [x] Non-timeout RPC errors in p2p (counter)

### Execution Client Insights

- [x] Number of valid, invalid, and syncing execution payload statuses (count)
   - `new_payload_invalid_node_count`
   - `new_payload_valid_node_count`
   - `new_payload_optimistic_node_count`
   - `forkchoice_updated_valid_node_count`
   - `forkchoice_updated_optimistic_node_count`
   - `forkchoiceUpdatedInvalidNodeCount` #11374

- [x] Transaction count per slot (gauge) #11374
   - `txs_per_slot_count`

- [x] Error counts for engine calls #11374
  - `execution_parse_error_count` and more below that line...
 

| Code | Message | Meaning |
| - | - | - |
| -32700 | Parse error | Invalid JSON was received by the server. |
| -32600 | Invalid Request | The JSON sent is not a valid Request object. |
| -32601 | Method not found | The method does not exist / is not available. |
| -32602 | Invalid params | Invalid method parameter(s). | 
| -32603 | Internal error | Internal JSON-RPC error. |
| -32000 | Server error | Generic client error while processing request. |
| -38001 | Unknown payload | Payload does not exist / is not available. |
| -38002 | Invalid forkchoice state | Forkchoice state is invalid / inconsistent. |
| -38003 | Invalid payload attributes | Payload attributes are invalid / inconsistent. |

### Performance Insights

- [x]  Gossip verification times
    - [x]  Verification time processing rates before re-gossiping for atts and blocks (histogram)
    - [x]  Aggregate attestation gossip verification time (histogram)
    - [x]  Aggregate atts processed per minute (histogram)
    - [x]  Aggregate atts success rate (histogram)
- [x]  Saving to DB times
    - [x]  Block saving to DB performance (histogram)
    - [x]  State performance (histogram)
- [x]  Reads from DB times
    - [x]  Blocks (histogram)
    - [x]  States (histogram)
- [x]  Block processing total time
    - [x]  IO (histogram)
    - [x]  State transition times (histogram)
    - [x]  Gossip verification time (histogram)
- [x]  Attestation processing times (histogram 5m rate of sum / 5m rate of count) #11374
- [x]  Forkchoice processing times (histogram) #11374 
    - [x] What are specific things to split up from this ? Maybe more granular processing time histograms?
- [x]  Block assembly times from our validator clients (histogram) **Terence**: use grpc metric `GetBeaconBlock`
- [x]  Attestation aggregation latencies (histogram) **Terence**: use grpc metric `SubmitAggregateSelectionProof`
- [x]  State regeneration latencies (histogram)
- [x]  Validator builder response times (histogram) under `builder/metric.go`

**Comment by terencechain** [comment]
I'm working on these
```
Attestation processing times (histogram 5m rate of sum / 5m rate of count)
Forkchoice processing times (histogram)
What are specific things to split up from this ? Maybe more granular processing time histograms?

Block assembly times from our validator clients (histogram)
Attestation aggregation latencies (histogram)
Validator builder response times (histogram)
```
