### ISSUE TITLE
v3.1.2 Release Tracking

### ISSUE THREAD

**Issue by nisdas** [prysmaticlabs/prysm#11510]
# 💎 Issue

### Background

This issue tracks all the required items for our first post-merge release. 

### Description

- [x] Fix incorrect engine api timeouts. #11487 
- [x] Fix context deadlines when saving historical states. #11501 
- [x] Add flag to extend engine api timeouts. #11489 
- [ ] Migrate bellatrix blocks when enabling blinded payloads. #11438 
- [x] Add support for new lodestar agent version. #11430 
- [ ] Fix incorrect saving of state summaries. #11384 #11327 #11388
- [x] Fix non existent proposer caching when calling beacon api endpoints. #11520 
- [x] Fix broken validator monitoring parsing. #11532 
- [x] Update go-libp2p to v0.22 #11309

**Comment by terencechain** [comment]
Let's also take care of #11340

**Comment by james-prysm** [comment]
adding web3signer validator exit support ( migrated to prysm ctl) #11478
adding web ui release to help address oom issue #11544

**Comment by james-prysm** [comment]
closing this as version was released.
