### ISSUE TITLE
[Tracking] - EIP-4844

### ISSUE THREAD

**Issue by terencechain** [prysmaticlabs/prysm#11579]
## Background

With many eyes on EIP4844 lately, we need a canonical tracking issue to start capturing tasks needed in Prysm to support EIP4844. There have been many ongoing parallel efforts on implementing 4844 for prysm and those branches are scattered over the places. We should consolidate them in one place. This Issue will capture the detailed todos and push EIP4844 forward with Prysm

### New container
- [x] Add new sidecar containers
- [x] Modify beacon block containers
- [x] Modify execution payload containers

### KZG library
- [x] Pick a KZG library to use
- [x] Pick a backup KZG library to use
- [x] Do we need to write any wrappers on top of the KZG libraries?

### Consensus layer changes
- [x] Add `process_blob_kzg_commitments` and `verify_kzg_commitments_against_transactions` to validate commitments across payload raw transactions
- [x] Add `validate_blobs_sidecar` which uses `evaluate_polynomial_in_evaluation_form` and `verify_kzg_proof`
- [x] State transition should be aware of beacon objects under Capella/EIP4844 version
- [x] State transition should upgrade to Capella/EIP4844 version

### Networking changes
- [x] New gossip handler for `beacon_block_and_blob_sidecar`
- [x] New req/res handler to request and respond `blob_sidecar` by ranges
- [x] Update the same req/res handler for Capella/EIP4844 `beacon_block` 
- [x] New Capella/EIP4844 fork digest and fork watcher

### Validator changes
- [x] Use new engine API to retrieve payload and sidecar in one go
- [x] Add KZG proof construction for block proposal
- [x] Validator can sign new beacon block
- [x] Validator can sign sidecar

### RPC changes
- [x] Various RPC methods have to support Capella/EIP4844 block request/respond
- [x] Support retrieving sidecar by block root or block slot
- [x] Support retrieving individual blob by blob hash or commitment

### Database changes
- [x] Can save sidecar
- [x] Can prune sidecar after `N` epochs (rolling window style). Optional: `N` can be a parameter
- [x] We might need some lookups such as `beacon_block_root` -> `execution_block_hash` or vice versa

### Testing
- [x] Can sync devnet with the new branch

**Comment by terencechain** [comment]
Marking this as completed with devnet3 running. We'll open another issue to track the follow-ups

https://hackmd.io/q1SLCaubTIWw_1zsEjW_Vg?view
