### ISSUE TITLE
[Tracking] - Block Processing Improvements

### ISSUE THREAD

**Issue by rauljordan** [prysmaticlabs/prysm#11574]
# 💎 Issue

## Background

Block processing is the most critical code path in Prysm, as it involves significant complexity in validation of data, steps of processing, atomicity, and order of operations which could cause serious consensus bugs or leave nodes in inconsistent states if they go wrong. Over the past months, block processing has evolved significantly due to the complexity of the merge, execution client interactions, and fork choice being so tied to how the code behaves.

### Cleanup

- [ ] Explore creating "full copies" of forkchoice for scratchpad uses. For example, creating a whole copy of forkchoice statefulness for computing changes during initial sync that can be discarded if needed without polluting the actual forkchoice store
- [ ] Remove the need for two separate state transition functions by instead making a single state transition configurable via functional options. For example, one option can be to create a signature batch instead of verifying signatures sequentially
- [ ] Move all "book keeping" goroutines to the very end of block processing to keep processing atomic
- [ ] Refactor the main processing routine into smaller chunks to read as follows:

```go
PreTransitionVerification()
StateTransition()
NewPayloadNotification()
NewHead()
ForkchoiceUpdatedNotification()
CanonicalBookkeeping()
```

- [ ] Consider creating different type wrappers for the different verification stages of blocks. For example:
```go
type GossipVerifiedBlock interface {
  SignedBeaconBlock
}

type StateTransitionVerifiedBlock interface {
  GossipVerifiedBlock
}

type CanonicalBlock interface {
  StateTransitionVerifiedBlock
}
```
A `CanonicalBlock` would not require any checks that the block is canonical. Moreover, state transition verified block would not need to run a state transition again. We could perhaps even define a `NilCheckedBlock` to signify it does not need any nil checks.

- [ ] Do not make the blockchain service responsible for initial sync caches (explore this further)
- [ ] Do not prune attestations twice in block processing
- [ ] Do not track the “headRoot” as a cached value in the blockchain service struct 

### Testing

- [ ] Evaluate creating a "simulated backend" for CL testing that can be used in Go unit tests to set up a chain with different constraints. For example, set up a chain with caches/blockchain/forkchoice from genesis that skips every 3rd block, or a chain that has a fork at slot N of every epoch, etc. Could use something like the builder pattern:
```go
backend := testutil.NewSimulatedBeacon().UpToSlot(N).SkipEvery(N).ForksAtSlots(slots []types.Slot)
backend.Start()
```
this can be a more flexible solution than e2e for testing block processing in unit tests / integration tests with a much faster feedback loop. Can also be used in forkchoice tests! Could warrant a small design doc
