### ISSUE TITLE
[Tracking] - Prysm V4

### ISSUE THREAD

**Issue by terencechain** [prysmaticlabs/prysm#11841]
This PR tracks features to be included for the Prysm V4 release. Prysm V4 will target the Capella/Shanghai release and it's a hard fork / non-backward compatible release. We can divide Prysm V4 under the following sections and todos. Feel free to add anything as you see fit

Core consensus
- [x] Process withdrawal and process new bls-to-exec changes
- [x] Process historical batches

P2P
- [x] Gossip and validation for the new new bls-to-exec changes

Beacon API
- [x] Capella versioned beacon block and beacons state requests
- [x] Withdrawal related request
- [x] Historical batches related request

Sync
- [ ] Backfilling of beacon block for weak subjectivity sync

Builder / MEV-boost
- [x] Block construction is supported through the new builder API for Capella

Prysmctl
- [x] Node operator can sign and submit bls-to-exec changes

Web3Signer
- [x] Web3signer Capella support

🦉

**Comment by james-prysm** [comment]
Should we decom the old prysm remote signer as part of v4? 
https://github.com/prysmaticlabs/prysm/issues/11700

**Comment by potuz** [comment]
Do we really want to have this a major release? It's only a few months from the merge and we will have a free pass for breaking changes in the APIs?

**Comment by james-prysm** [comment]
if there's time, fully deprecating some unused grpc endpoints for webui would be good.

**Comment by rkapka** [comment]
Deprecate/remove removed/deprecated endpoints of Beacon APIs
-

**Comment by rkapka** [comment]
Remove `--interop-genesis-state` flag, it's broken. We should use `--genesis-state` instead

**Comment by potuz** [comment]
Leaving here what I would personally want before code freeze for mainnet:
 - [ ] Reorg late blocks
 - [ ] Forkchoice changes and removal of flags.

**Comment by james-prysm** [comment]
[ ] - new event stream type payload attribute - https://github.com/ethereum/beacon-APIs/pull/305
