### ISSUE TITLE
Integrate EIP-4881 Deposit Trie Into Runtime

### ISSUE THREAD

**Issue by rauljordan** [prysmaticlabs/prysm#11928]
# 🦄 Feature Tracking

**Current status** (opt-in or opt-out):

**Opt-in feature flag name**:

\--eip-4881

**Opt-out feature flag name**:

\--disable-eip-4881

### Feature Description

Part of #11256

### Tasks

**Integrating EIP-4881**

- [X] Replace all instances of \*depositcache.DepositCache with an interface. First, define smaller interfaces for the deposit cache in another package, make sure that \*depositcache.DepositCache implements this interface. Encompass all methods we need in that interface, and then use across Prysm instead of the concrete struct
- [X] Ensure both the \*depositcache.DepositCache struct implements this interface, and also that DepositSnapshot does the same
- [X] Write a feature flag that swaps out the implementation inside of beacon-node/node/node.go
- [X] Integrate the feature flag into e2e tests

**Feature Flag Integration**

- [X] Feature flag created as opt-in
- [X] Feature implemented / code complete
- [X] Feature tested in production for adequate amount of time
- [X] Feature flag is inverted to be opt-out and the opt-in flag is deprecated
- [X] Feature has made it to a tagged production release as an opt-out flag
- [X] Opt-out feature flag is deprecated and old code paths are cleaned up
