### ISSUE TITLE
EIP4844 Feature Completion Checklist

### ISSUE THREAD

**Issue by terencechain** [prysmaticlabs/prysm#12248]
This issue tracks the remaining tasks for completing the EIP4844 feature on Deneb. The following tasks have already been accomplished:

- State transition implementation is up to spec. Latest spec tests passed
- Validator signing blobs and broadcasting blobs to individual gossip net are working
- DB pruning for blobs is working
- Most of current spec'ed beacon API endpoints are implemented and tested
- Blob gossip is working
- Blob by range syncing is working
- Blob by root syncing is working
- A node can sync from Genesis to post Deneb on the block with blobs
- Prysmctl tool to request blobs by range

The following tasks are remaining:
- [ ] Implement backfilling for blocks and blobs
- [ ] Implement builder path for Deneb blind block and blind blobs 
   - [x]  update builder client handling https://github.com/ethereum/builder-specs/pull/61
- [ ] Implement a better heuristic approach to request missing blob
- [ ] Implement blob storage separation. Users can choose to store blobs in other file systems if they wish to
- [ ] Add and optimize sidecar KZG proof checks
- [ ] Handle the edge case where the finalized epoch is older than the data retention epoch
- [ ] Clean up the initial sync code. Perhaps using this excellent opportunity to rewrite the majority of the initial sync code
- [ ] Test thoroughly and refine the user experience
- [x] Update Beacon API endpoints:
  - [x] `getStateV2` json
  - [x] `getStateV2` ssz
  - [x] `getBlockV2` json
  - [x] `getBlockV2` ssz
  - [x] `getBlindedBlock` json
  - [x] `getBlindedBlock` ssz
  - [x] `publishBlock` json
  - [x] `publishBlock` ssz 
  - [x] `publishBlockV2` json
  - [x] `publishBlockV2` ssz
  - [x] `publishBlindedBlock` json
  - [x] `publishBlindedBlock` ssz 
  - [x] `publishBlindedBlockV2` json
  - [x] `publishBlindedBlockV2` ssz 
  - [x] `produceBlindedBlock` json
  - [x] `produceBlindedBlock` ssz 
  - [x]  `produceBlockV2` json
  - [x] `produceBlockV2` ssz 
  - [x]  `produceBlockV3` json https://github.com/ethereum/beacon-APIs/pull/339
  - [x]  `produceBlockV3` ssz
  - [x]  `getBlobs` json
  - [x]  `getBlobs` ssz
 - [ ] add Web3signer support for Deneb blocks
 - [ ] add Web3signer support for signed blobs
 - [ ] update validator rest api calls to support deneb:
   - [ ] `getBlock`
   - [ ] `streamBlock`
   - [ ] `submitBlock`
   - [ ] `submitBlindedBlock`
 - [ ] E2E for Deneb

**Comment by james-prysm** [comment]
getBlockV2 and getStateV2 related needs more review/unit tests but looks like they exist
