### ISSUE TITLE
Feature: P2P over v4/v6 dual-stack

### ISSUE THREAD

**Issue by yorickdowne** [prysmaticlabs/prysm#12303]
# 🦄 Feature Tracking

**Current status** (opt-in or opt-out): 

**Opt-in feature flag name**:

**Opt-out feature flag name**: 

### Feature Description

With CGNAT becoming more prevalent, peering is hard for users when IPv4 incoming connections are not available.

Support IPv4/6 dual-stack for P2P. Currently, either is supported by `--p2p-local-ip ::` or `--p2p-local-ip 0.0.0.0`. As users will need both v4 and v6 peering, being able to specify `--p2p-local-ip` twice, once for each address family, would be helpful. Defaulting to dual-stack would be gravy.

**Context**

P2P support is the driver, here. Metrics, REST, key manager, all can stay v4, at least initially. If it's trivial to make them dual-stack as well, by all means do, but for the bulk of users where this is an issue - home users with CGNAT - they'll have v4 available and they won't need to reach REST via v6 from "the Internet"

### Tasks

- [ ] Feature flag created as opt-in
- [ ] Feature implemented / code complete
- [ ] Feature tested in production for adequate amount of time
- [ ] Feature flag is inverted to be opt-out and the opt-in flag is deprecated
- [ ] Feature has made it to a tagged production release as an opt-out flag
- [ ] Opt-out feature flag is deprecated and old code paths are cleaned up

This issue should be closed after all of the above tasks are complete.
