### ISSUE TITLE
[Tracking] - HTTP Beacon API

### ISSUE THREAD

**Issue by saolyn** [prysmaticlabs/prysm#12635]
# 🦄 HTTP Beacon API Tracking

### Feature Description

RPC endpoints defined in the `v1alpha1` directory are currently being used by the validator client. Here we can track the ones that have been converted to pure HTTP REST endpoints.
See [reference document](https://hackmd.io/X9Epjx7ARMOXES0fye3ZRw) for more information.

Please remember to also add a benchmark to the PR:
`curl [your endpoint] -w "\n%{time_starttransfer}\n"`

### This is a full list of endpoints used by the validator client:

- [x] /eth/v1/validator/attestation_data
- [x] /eth/v1/beacon/headers/{block_id}
- [x] /eth/v1/beacon/states/{state_id}/finality_checkpoints
- [x] /eth/v1/beacon/states/{state_id}/fork
- [x] /eth/v1/beacon/headers
- [x] /eth/v1/validator/liveness
- [x] /eth/v1/node/syncing
- [x] /eth/v1/config/deposit_contract
- [x] /eth/v1/beacon/states/{state_id}/committees
- [x] /eth/v1/validator/duties/attester/{epoch}
- [x] /eth/v1/validator/duties/proposer/{epoch}
- [x] /eth/v1/validator/duties/sync/{epoch}
- [x] /eth/v1/beacon/genesis
- [x] /eth/v1/validator/prepare_beacon_proposer
- [x] /eth/v1/beacon/pool/attestations
- [x] /eth/v1/beacon/blinded_blocks
- [x] /eth/v1/beacon/blocks
- [x] /eth/v1/beacon/pool/voluntary_exits
- [x] /eth/v1/validator/register_validator
- [x] /eth/v1/beacon/states/{state_id}/validators
- [x] /eth/v1/validator/aggregate_attestation
- [x] /eth/v1/validator/aggregate_and_proofs
- [x] /eth/v1/validator/contribution_and_proofs
- [x] /eth/v1/validator/beacon_committee_subscriptions
- [x] /eth/v1/beacon/pool/sync_committees
- [x] /eth/v1/beacon/blocks/{block_id}/root
- [x] /eth/v1/validator/sync_committee_contribution

This issue should be closed after all of the above tasks are complete.

**Comment by rkapka** [comment]
I am working on `/eth/v1/validator/aggregate_attestation`

**Comment by rkapka** [comment]
Working on `/eth/v1/beacon/blocks/{block_id}/root` now

**Comment by rkapka** [comment]
Working on ` /eth/v1/validator/contribution_and_proofs` at the moment

**Comment by rkapka** [comment]
Looking at `/eth/v1/validator/beacon_committee_subscriptions` now

**Comment by saolyn** [comment]
Working on `/eth/v1/validator/sync_committee_contribution`

**Comment by saolyn** [comment]
Working on `/eth/v1/beacon/blocks/{block_id}/root`

**Comment by rkapka** [comment]
Implementing `/eth/v1/validator/sync_committee_contribution` now

**Comment by rkapka** [comment]
Looking at all the `beacon/pool` endpoints now

**Comment by anukul** [comment]
Working on `/eth/v1/beacon/headers`

**Comment by james-prysm** [comment]
working on /eth/v1/validator/register_validator

**Comment by saolyn** [comment]
Working on `/eth/v1/beacon/blocks`

**Comment by james-prysm** [comment]
Working on ` /eth/v1/beacon/states/{state_id}/fork`

**Comment by rkapka** [comment]
Looking at ` /eth/v1/beacon/states/{state_id}/validators` now

**Comment by saolyn** [comment]
Working on ` /eth/v1/beacon/states/{state_id}/committees`

**Comment by james-prysm** [comment]
working on ` /eth/v1/beacon/genesis`

**Comment by rkapka** [comment]
Tackling `/eth/v1/beacon/blinded_blocks` and `/eth/v1/beacon/blocks` now

**Comment by saolyn** [comment]
All endpoints merged
