### ISSUE TITLE
[Tracking] - Native Holesky Testnet Support

### ISSUE THREAD

**Issue by james-prysm** [prysmaticlabs/prysm#12724]
# 🚀 Feature Request

### Description
https://github.com/eth-clients/holesky
[note from parithosh](https://twitter.com/parithosh_j/status/1689753694487646208?s=46&t=FV26h3b9hzTKb_ndd2zkow)

holesky is a new ethereum testnet to be launched around sept15th, 2023 and will be the future replacement of goerli. 
Prysm should natively support this testnet and update required items around supporting it

Holesky Testnet 
- [x] Update Prysm documents
- [x] Add native holesky testnet flags to appropriate services (`--holesky`)
- [x] Submit Prysm team validator keys https://github.com/eth-clients/holesky/pull/31
- [x] Request genesis hETH https://github.com/eth-clients/holesky/issues/1

**Comment by prestonvanloon** [comment]
Once the Holesky genesis is created, we can add the `--holesky` flags and appropriate configuration to support this network in the Prysm client. Genesis state / config is expected to be defined this upcoming Monday. See https://github.com/eth-clients/holesky/issues/3

**Comment by prestonvanloon** [comment]
Waiting for https://github.com/eth-clients/holesky/pull/57 to merge then we can resolve the remaining items.

**Comment by barnabasbusa** [comment]
PR has been merged 👍

**Comment by prestonvanloon** [comment]
Thanks @barnabasbusa

**Comment by prestonvanloon** [comment]
Reopening due to updates required in #12919

**Comment by prestonvanloon** [comment]
Blocked by https://github.com/eth-clients/holesky/issues/74
