### ISSUE TITLE
HTTP Endpoint Cleanup

### ISSUE THREAD

**Issue by saolyn** [prysmaticlabs/prysm#12958]
# 🦄 HTTP Endpoint Cleanup Tracking

### Feature Description

Now that all the validator client endpoints have been modified to be HTTP endpoints we need to clean up a few things before moving on to converting the rest of the Beacon API.

### Tasks

- [ ] Audit all HTTP handlers and unify code patterns
- [ ] Replace all instances of `s.OptimisticModeFetcher` with `helpers.IsOptimistic`
- [ ] Remove the validation package
- [ ] Change `s.V1Alpha1Server.GetBeaconBlock` call in `produceBlockV3` to use the `core` package instead
- [ ] Write documentation on how to add new custom endpoints
- [ ] Add a page with dedicated documentation for each endpoint

This issue should be closed after all of the above tasks are complete.

**Comment by rkapka** [comment]
> Change s.V1Alpha1Server.GetBeaconBlock call in produceBlockV3 to use the core package instead

This one is implemented in #12927

**Comment by james-prysm** [comment]
we need to migrate lightclient to stop using the eth proto package and instead use just the v1alphav1

**Comment by james-prysm** [comment]
there are duplicate code in the builder types + how it uses ssz that could be cleaned up
