### ISSUE TITLE
[Tracking] Blob file storage

### ISSUE THREAD

**Issue by saolyn** [prysmaticlabs/prysm#13141]
# Blob file storage Tracking

### Feature Description

Within Prysm, blob data is currently stored in BoltDB and is set to automatically expire and be overwritten after 4096 epochs by default. 

We want to move away from BoltDB and use a filesystem and save each blob as individual files. To do this we need to modify the existing system and replace it with the new file storage.

### Tasks

- [x] Function to save blobs #13129
- [x] Function to prune blobs #13147
- [x] Add to existing system #13253 #13275
- [x] Add metrics #13316

This issue should be closed after all of the above tasks are complete.
