### ISSUE TITLE
Safe head tracking - confirmation rule

### ISSUE THREAD

**Issue by adiasg** [prysmaticlabs/prysm#13603]
# 🦄 Feature Tracking

**Current status** (opt-in or opt-out): 

**Opt-in feature flag name**: `safe-head-fcu`

### Feature Description

This feature implements a confirmation rule for better safe head tracking.

The CL passes fork choice information to the EL in the form of [fork choice updates](https://github.com/ethereum/execution-apis/blob/37c2b9ed24b4a61ead6e64ef99950dae68682db7/src/engine/cancun.md#engine_forkchoiceupdatedv3) (FCUs). One of the contents of the FCU is the [`safeBlockHash`](https://github.com/ethereum/execution-apis/blob/37c2b9ed24b4a61ead6e64ef99950dae68682db7/src/engine/paris.md#forkchoicestatev1). This is in turn exposed by the EL in the Ethereum RPC method `eth_getBlockByNumber("safe")`. Users consume this block as a low latency, high confidence indicator of non-reorgability. 
Currently `consensus-specs` requires that the CL pass the [justified block](https://github.com/ethereum/consensus-specs/blob/7402712e4faebcb9cd87370d91acf638ae168949/fork_choice/safe-block.md#get_safe_beacon_block_root) as safe. Soon, a new [confirmation rule](https://github.com/ethereum/consensus-specs/pull/3339) will be used to identify a safe block that is closer to the tip of the chain. This feature implements a [reduced version](https://github.com/adiasg/eth2.0-specs/blob/3e3ef28ace725b7b883f1908189406c890a569c3/fork_choice/confirmation-rule.md) of the confirmation rule.

### Tasks

- [x] Feature flag created as opt-in
- [x] Feature implemented / code complete
- [ ] Feature tested in production for adequate amount of time
- [ ] Feature flag is inverted to be opt-out and the opt-in flag is deprecated
- [ ] Feature has made it to a tagged production release as an opt-out flag
- [ ] Opt-out feature flag is deprecated and old code paths are cleaned up

This issue should be closed after all of the above tasks are complete.
