### ISSUE TITLE
Tracking: Spectest Coverage

### ISSUE THREAD

**Issue by saolyn** [prysmaticlabs/prysm#13767]
# Spectest Coverage Tracking

### Feature Description

The tests below are the tests identified as missing by the spectest coverage script #13718.
This issue is to track and add all the missing spec tests.

##### Altair
- [ ] tests/general/altair/bls/eth_aggregate_pubkeys
- [ ] tests/general/altair/bls/eth_fast_aggregate_verify

##### Deneb
- [ ] tests/general/deneb/kzg/blob_to_kzg_commitment
- [ ] tests/general/deneb/kzg/compute_blob_kzg_proof
- [ ] tests/general/deneb/kzg/compute_kzg_proof
- [ ] tests/general/deneb/kzg/verify_kzg_proof

##### Altair
- [ ] tests/minimal/altair/epoch_processing/sync_committee_updates
- [ ] tests/minimal/altair/genesis/initialization
- [ ] tests/minimal/altair/genesis/validity
- [ ] tests/minimal/altair/operations/sync_aggregate

##### Bellatrix
- [ ] tests/minimal/bellatrix/epoch_processing/sync_committee_updates
- [ ] tests/minimal/bellatrix/genesis/initialization
- [ ] tests/minimal/bellatrix/genesis/validity
- [ ] tests/minimal/bellatrix/operations/sync_aggregate

##### Capella
- [ ] tests/minimal/capella/epoch_processing/sync_committee_updates
- [ ] tests/minimal/capella/genesis/initialization
- [ ] tests/minimal/capella/genesis/validity
- [ ] tests/minimal/capella/operations/sync_aggregate

##### Deneb
- [ ] tests/minimal/deneb/epoch_processing/sync_committee_updates
- [ ] tests/minimal/deneb/genesis/initialization
- [ ] tests/minimal/deneb/genesis/validity
- [ ] tests/minimal/deneb/operations/sync_aggregate

##### Phase0
- [ ] tests/minimal/phase0/genesis/initialization
- [ ] tests/minimal/phase0/genesis/validity

This issue should be closed after all of the above tasks are complete.
