### ISSUE TITLE
Pectra-devnet-0 tracker

### ISSUE THREAD

**Issue by terencechain** [prysmaticlabs/prysm#13849]
This PR tracks the overall Prysm progress to support [pectra-devnet-0](https://notes.ethereum.org/@ethpandaops/pectra-devnet-0)
- [ ] [EIP-6110: Supply validator deposits on chain ](https://eips.ethereum.org/EIPS/eip-6110)
- [ ] [EIP-7002: Execution layer triggerable exits](https://eips.ethereum.org/EIPS/eip-7002)
- [ ] [EIP-7251: Increase the MAX_EFFECTIVE_BALANCE](https://eips.ethereum.org/EIPS/eip-7251)
- [ ] [EIP-7549: Move committee index outside Attestation](https://eips.ethereum.org/EIPS/eip-7549)
