### ISSUE TITLE
Tracking: Update Beacon API to Electra

### ISSUE THREAD

**Issue by saolyn** [prysmaticlabs/prysm#14476]
# Update Beacon API to Electra

These are the endpoints that we need to ensure are updated to Electra.

### Missing Endpoints

- [x] /eth/v2/beacon/blocks/{block_id}/attestations
- [x] /eth/v2/beacon/pool/attester_slashings GET
- [x] /eth/v2/beacon/pool/attester_slashings POST
- [x] /eth/v2/validator/aggregate_attestation
- [x] /eth/v2/validator/aggregate_and_proofs
- [x] /eth/v2/beacon/pool/attestations GET
- [x] /eth/v2/beacon/pool/attestations POST

### Endpoints to check

- [x] /eth/v1/beacon/blinded_blocks
- [x] /eth/v2/beacon/blinded_blocks
- [x] /eth/v1/beacon/blocks
- [x] /eth/v2/beacon/blocks
- [x] /eth/v2/beacon/blocks/{block_id}
- [x] /eth/v1/beacon/blob_sidecars/{block_id}
- [x] /eth/v1/beacon/blinded_blocks/{block_id}
- [x] /eth/v2/debug/beacon/states/{state_id}
- [x] /eth/v3/validator/blocks/{slot}
- [x] /eth/v1/events (update to use single attestation)

This issue should be closed after all of the above tasks are complete.

**Comment by james-prysm** [comment]
discussion from discord says we probably don't want to have a v2 of events, instead update the first

**Comment by james-prysm** [comment]
We also need to update the validator client to use these endpoints otherwise it will fail

**Comment by james-prysm** [comment]
using linear issue to track remaining endpoints
