### ISSUE TITLE
[Mega Tracking] Full Validator Spec Implementation

### ISSUE THREAD

**Issue by rauljordan** [prysmaticlabs/prysm#1510]
Hi all,

This is a tracking issue for all PRs related to finishing our implementation of the entire validator document as specified [here](https://github.com/ethereum/eth2.0-specs/blob/master/specs/validator/0_beacon-chain-validator.md). We are very close to finishing the entire logic in this document. Here is what has been done so far and the missing steps:

- [x] Validator account initialization
- [x] Submitting initial deposits pre-chainstart
- [x] Proposer responsibility (client and server)
- [x] Attester responsibility (client and server)
- [x] Pending deposits queue for proposers to include in their blocks
- [x] Remove pending deposits from the queue on block processing
- [x] Broadcasting proposals and attestations via p2p (attestations need to be broadcast at slot+0.5*SLOT_DURATION seconds)
- [x] Waiting for validator activation post-chainstart
- [x] Responsibility lookahead
- [x] Implement fetch ETH1 data in RPC server side
- [x] Use tree hashing and BLS in the validator client
- [x] Cap the number of block operations a proposer can include in a block
- [x] Persist validator index to disk post activation (it is guaranteed not to change) and use it for computation throughout the validator's lifecycle
- [x] (#1675) Pack validator initial credentials (withdrawal credentials can be computed as defined in the validator spec) into deposit input of the form:
```python
{
    # BLS pubkey
    'pubkey': 'bytes48',
    # Withdrawal credentials
    'withdrawal_credentials': 'bytes32',
    # A BLS signature of this `DepositInput`
    'proof_of_possession': 'bytes96',
}
```

**Comment by rauljordan** [comment]
@IvanTheGreatDev interested in any of this?

**Comment by IvanTheGreatDev** [comment]
Always am! I would be down to do: 

`Remove pending deposits from the queue on block processing`
` Broadcasting proposals and attestations via p2p (attestations need to be broadcast at slot+0.5*SLOT_DURATION seconds)`
`* Cap the number of block operations a proposer can include in a block`

I might need some guidance though 😄

**Comment by terenc3t** [comment]
Going to work on `Responsibility lookahead` helper first, this will be in `helper/committee.go`

**Comment by terenc3t** [comment]
Starting to work on `Responsibility lookahead`

**Comment by nisdas** [comment]
Will be taking up `Preventing slashing by persisting signed and proposed data to disk`

**Comment by rauljordan** [comment]
Slashing items moved to Q2 priorities:
- [ ] Preventing slashing by persisting signed and proposed data to disk
- [ ] If validator went offline during responsibility and comes online again, use the persisted signed data to prevent slashing and send that to the beacon node

**Comment by prestonvanloon** [comment]
WIP * Pack validator initial credentials

**Comment by prestonvanloon** [comment]
#1934 is the last part. Closing this issue in favor of that one.
