### ISSUE TITLE
[Mega Tracking] Align Codebase to Spec v0.2

### ISSUE THREAD

**Issue by terencechain** [prysmaticlabs/prysm#1541]
This issue tracks the overall progress of updating the current beacon chain implementation to spec [v0.2](https://github.com/ethereum/eth2.0-specs/releases/tag/v0.2.0) Here is what has been done so far and the missing steps:

**Phase 0 Beacon Chain:**
- [ ] introduce "swap-or-not" shuffle
- [x] fork choice rule now weighted by balance  #1564
- [x] mix epoch into seed within generate_seed rather than in get_shuffling #1533 
- [x] AttestationData includes latest_crosslink rather than just latest_crosslink_root #1546
- [x] add get_previous_epoch helper #1447 
- [x] add get_total_balance helper 
- [x] int_to_bytesN uses little-endian #1536
- [x] minor range fix to verify_bitfield  #1562
- [x] Use 2**63 for GENESIS_SLOT #1537 

**Phase 0 validator client:**
- [x] implement `get_next_epoch_committee_assignments` #1552

**Simple Serialize:**
- [ ] List tree-hash padding consistency fix
- [ ] "internal" vs "external" hash roots padding fix

**BLS:**
- [x] rename message -> message_hash in all bls functions #1563

**Comment by terenc3t** [comment]
Working issue: `AttestationData includes latest_crosslink rather than just latest_crosslink_root`

**Comment by terenc3t** [comment]
> Working on issue: `AttestationData includes latest_crosslink rather than just latest_crosslink_root`

Done! Please review #1546

**Comment by terenc3t** [comment]
Working on `get_next_epoch_committee_assignments`

**Comment by cyberbono3** [comment]
working on introduce "swap-or-not" shuffle

**Comment by terenc3t** [comment]
working on `fork choice rule now weighted by balance`

**Comment by terencechain** [comment]
Closed for #2307
