### ISSUE TITLE
[Mega Tracking] Phase 0 Testnet Items

### ISSUE THREAD

**Issue by rauljordan** [prysmaticlabs/prysm#1586]
Hi all,

This is a mega tracking issue for all the TODO items we have left before we can release a reliable testnet for Phase 0 pinned to v0.2 of the spec. We are pretty close, but there are still a lot of minor loose ends to take care of before we can finish putting this on a cluster and calling it a day. This will serve as the main issue we refer to when tracking all major features for the testnet.

- [x] Implement the full sync of the beacon block operations pool between nodes #1654 @terenc3t 
- [x] Ensure initial sync between nodes works for the beacon state and blocks during that state's epoch (this should use some basic progress mechanism in the logs for better UX) @nisdas #1593
- [x] Ensure incoming state/block sync works once a node has completed initial sync @nisdas #1593
- [x] Implement ETH1 data voting
- [x] Handle new validator onboarding post ChainStart by waiting for activation according to the v0.2 spec
- [x] Ensure our codebase reads almost exactly like the v0.2 spec @terenc3t 
- [x] Improve UX of validator onboarding, perhaps with a rudimentary front-end giving instructions on how to perform deposits on Metamask given a deposit data hex string, prompt users to sign up for updates on when they should upgrade their nodes https://github.com/prysmaticlabs/prysm-testnet-site/issues/3
- [x] Incorporate better logging at the epoch level to understand how the state changes, if there were newly activated validators, what the last finalized slot was, etc. @terenc3t 
- [x] Include logging for validator clients to query their rewards, if they have been penalized, if they have skipped their responsibilities, etc. throughout their lifecycle @terenc3t 
- [x] k8s infrastructure / config / monitoring @prestonvanloon 
- [x] Testnet documentations on GitBook 

## Moved to Q2
- [x] Incorporate public RPC methods for other applications or users to query information about the state at any given time @terenc3t 
- [x] Optimize fork-choice rule (LMD GHOST) and latest attestations  #1951

**Comment by prestonvanloon** [comment]
Added a few items: 
- UI for deposit flow (necessary for common users to join testnet)
- k8s infrastructure & monitoring

**Comment by terenc3t** [comment]
Added
- Testnet documentations on GitBook

**Comment by rauljordan** [comment]
Complete!
