### ISSUE TITLE
Use Simulated Backend to Test Sync [ Tracking Issue ] 

### ISSUE THREAD

**Issue by nisdas** [prysmaticlabs/prysm#1593]
With #1445 being merged in , we can use the simulated backend to generate blocks and advance the chain. What this means for testing sync is that now we can test how nodes will interact with each other under certain scenarios. Ex: Node A is synced to the current slot of 100 , with sync B we should be able to test if this also sync to the current slot of 100 with the same state root. We can test other scenarios also with multiple nodes. 

A high level overview is provided over here https://docs.google.com/document/d/18rZxhdLmM3zfC5RtHHkxuyWd2qDL6h_B6VuSnaVSBVs/edit?usp=sharing

This issue serves as a tracking issue for this. 

- [x] Add ability to spin up sync services, with a simulated p2p for exchanging messages between 
services.
- [x] Test a node syncing with multiple synced nodes
- [x] Test multiple nodes syncing with a single synced node.
- [x] Test node syncing from a far away behind slot
~~- [ ] Test syncing with malicious actors, ex : Batched blocks contain a single invalid block.~~
- [x] Test Syncing from the last finalized slot , for the beacon state.

This is also related to #1586
