### ISSUE TITLE
[Mega Tracking] Fuzz testing (RPC & p2p)

### ISSUE THREAD

**Issue by prestonvanloon** [prysmaticlabs/prysm#1930]
As part of improving the project binary resiliency, we must have fuzz testing as part of our test suite.

After some brief investigation, I suggest that we should adopt the [best practices of OSS-Fuzz](https://github.com/google/oss-fuzz/blob/master/docs/ideal_integration.md).

Some known areas for fuzz testing:

- [ ] Anything incoming from the p2p layer (libp2p pubsub, etc)
- [ ] Anything incoming from the RPC layer (gRPC client/server)

Currently, I'm investigating the best approach for introducing a framework for fuzz testing Prysm.

- [ ] Create a trivial fuzz test with the best practices above
- [ ] Create documentation to explain how to run and add new fuzz tests

Helpful resources:
- [Envoy fuzz testing doc](https://github.com/envoyproxy/envoy/tree/master/test/fuzz)
- [gRPC testing doc](https://github.com/grpc/grpc/tree/master/tools/run_tests)
- [libFuzzer structure aware fuzzing doc](https://github.com/google/fuzzer-test-suite/blob/master/tutorial/structure-aware-fuzzing.md)

**Comment by prestonvanloon** [comment]
go-fuzz supports libFuzzer archive generation: https://github.com/dvyukov/go-fuzz#libfuzzer-support

**Comment by rauljordan** [comment]
@prestonvanloon can we close this? Or perhaps open up in a more granular issue thread

**Comment by prestonvanloon** [comment]
Closing. Fuzz testing is mostly released and this issue is over a year old.
