### ISSUE TITLE
[Mega Tracking] - Align spec to release v0.6

### ISSUE THREAD

**Issue by terencechain** [prysmaticlabs/prysm#2307]
This PR tracks the overall progress of aligning current beacon chain implementation to spec version 0.6. Please comment on the issue before you pick up an item to work on. 

- [x] 💎  **Update [constant](https://github.com/ethereum/eth2.0-specs/blob/dev/specs/core/0_beacon-chain.md#constants) names and values** 💎
- [x] 💎  **Update Protobuf data structures** 💎
    - [x] Update [Crosslink](https://github.com/ethereum/eth2.0-specs/blob/dev/specs/core/0_beacon-chain.md#crosslink) | #2313
    - [x] Update [Eth1Data](https://github.com/ethereum/eth2.0-specs/blob/dev/specs/core/0_beacon-chain.md#eth1data) | #2315
    - [x] Update [AttestationData](https://github.com/ethereum/eth2.0-specs/blob/dev/specs/core/0_beacon-chain.md#attestationdata) | #2316
    - [x] Update [AttestationDataAndCustodyBit](https://github.com/ethereum/eth2.0-specs/blob/dev/specs/core/0_beacon-chain.md#attestationdataandcustodybit) | #2316
    - [x] Update [IndexedAttestation](https://github.com/ethereum/eth2.0-specs/blob/dev/specs/core/0_beacon-chain.md#indexedattestation) | #2316
    - [x] Update [DepositData](https://github.com/ethereum/eth2.0-specs/blob/dev/specs/core/0_beacon-chain.md#depositdata) | #2318
    - [x] Update [BeaconBlockHeader](https://github.com/ethereum/eth2.0-specs/blob/dev/specs/core/0_beacon-chain.md#beaconblockheader) | #2327
    - [x] Update [Validator](https://github.com/ethereum/eth2.0-specs/blob/dev/specs/core/0_beacon-chain.md#validator) | #2318
    - [x] Update [HistoricalBatch](https://github.com/ethereum/eth2.0-specs/blob/dev/specs/core/0_beacon-chain.md#historicalbatch) | #2327
    - [x] Update [ProposerSlashing](https://github.com/ethereum/eth2.0-specs/blob/dev/specs/core/0_beacon-chain.md#proposerslashing) | #2328
    - [x] Update [AttesterSlashing](https://github.com/ethereum/eth2.0-specs/blob/dev/specs/core/0_beacon-chain.md#attesterslashing) | #2328
    - [x] Update [Attestation](https://github.com/ethereum/eth2.0-specs/blob/dev/specs/core/0_beacon-chain.md#Attestation) | #2328
    - [x] Update [Deposit](https://github.com/ethereum/eth2.0-specs/blob/dev/specs/core/0_beacon-chain.md#Deposit) | #2327
    - [x] Update [VoluntaryExit](https://github.com/ethereum/eth2.0-specs/blob/dev/specs/core/0_beacon-chain.md#VoluntaryExit) | #2328
    - [x] Update [Transfer](https://github.com/ethereum/eth2.0-specs/blob/dev/specs/core/0_beacon-chain.md#Transfer) | #2328
    - [x] Update [BeaconBlockBody](https://github.com/ethereum/eth2.0-specs/blob/dev/specs/core/0_beacon-chain.md#BeaconBlockBody) | #2340
    - [x] Update [BeaconBlock](https://github.com/ethereum/eth2.0-specs/blob/dev/specs/core/0_beacon-chain.md#BeaconBlock) | #2340
    - [x] Update [BeaconState](https://github.com/ethereum/eth2.0-specs/blob/dev/specs/core/0_beacon-chain.md#BeaconState) | #2341 
    - [x] Update [Fork](https://github.com/ethereum/eth2.0-specs/blob/dev/specs/core/0_beacon-chain.md#fork) | #2545

- [x] 💎  **Update general [helper functions](https://github.com/ethereum/eth2.0-specs/blob/dev/specs/core/0_beacon-chain.md#helperfunctions)**  💎
    - [x] Update slot related helpers | #2345 
    - [x] Update validator related helpers | #2352 
    - [x] Update balance related helpers | #2348 
    - [x] Update permuted index helpers | #2350
    - [x] Update splitoffset helpers | #2365
    - [x] Update committee related helpers | #2354
    - [x] Update shard delta helpers | #2497
    - [x] Update epoch start shard helpers | #2497
    - [x] Update block root related helpers | #2355
    - [x] Update state root related helpers | #2355
    - [x] Update randao mix helpers |  #2357
    - [x] Update active index root helpers | #2369
    - [x] Update generate seed helpers | #2371
    - [x] Update beacon proposer index helpers | #2381
    - [x] Update attesting indices helpers | #2449
    - [x] Update balance related helpers | #2356
    - [x] Update bitfield related helpers | #2446 (bug fix)
    - [x] Update verify indexed attestation helpers | #2385
    - [x] Update churn limit helpers | #2364
    - [x] Update [convert to indexed ](https://github.com/ethereum/eth2.0/specs/blob/dev/specs/core/0_beacon-chain.md#convert_to_indexed) | #2519 
    - [x] update [get domain](https://github.com/ethereum/eth2.0-specs/blob/dev/specs/core/0_beacon-chain.md#get_domain) | #2545

- [x] 💎  **Update routines for [changing validator status](https://github.com/ethereum/eth2.0-specs/blob/dev/specs/core/0_beacon-chain.md#routines-for-updating-validator-status)****  💎
    - [x] Update initiate validator exit | #2366 
    - [x] Update slash validator (relies on balance and BeaconProposerIndex changes) | #2391

- [x] 💎  **Verify and update [chain start logic](https://github.com/ethereum/eth2.0-specs/blob/dev/specs/core/0_beacon-chain.md#eth2genesis-log)**  💎
    - [x] Update [genesis functions](https://github.com/ethereum/eth2.0-specs/blob/dev/specs/core/0_beacon-chain.md#on-genesis) | #2465 
    - [x] Update Deposit Contract to new spec.

- [x] 💎  **Verify and update [SSZ](https://github.com/ethereum/eth2.0-specs/blob/dev/specs/simple-serialize.md)** 💎 
    - [x] 🔹 Implement [self-signed containers](https://github.com/ethereum/eth2.0-specs/blob/dev/specs/simple-serialize.md#self-signed-containers)🔹

- [x] 💎  **Update beacon chain [state transition function](https://github.com/ethereum/eth2.0-specs/blob/dev/specs/core/0_beacon-chain.md#beacon-chain-state-transition-function)**  💎
    - [x] 🔹 Update [per epoch processing](https://github.com/ethereum/eth2.0-specs/blob/dev/specs/core/0_beacon-chain.md#per-epoch-processing)🔹
        - [x] Update [general helper functions](https://github.com/ethereum/eth2.0-specs/blob/dev/specs/core/0_beacon-chain.md#helper-functions-1) | #2379
        - [x] Update [justification and finalization functions](https://github.com/ethereum/eth2.0-specs/blob/dev/specs/core/0_beacon-chain.md#justification-and-finalization) | #2448
        - [x] Update [crosslink function](https://github.com/ethereum/eth2.0-specs/blob/dev/specs/core/0_beacon-chain.md#crosslinks) | #2460 
        - [x] Update [rewards and penalties functions](https://github.com/ethereum/eth2.0-specs/blob/dev/specs/core/0_beacon-chain.md#rewards-and-penalties) | #2517
        - [x] Update [registry updates functions](https://github.com/ethereum/eth2.0-specs/blob/dev/specs/core/0_beacon-chain.md#registry-updates) | #2521
        - [x] Update [slashings function](https://github.com/ethereum/eth2.0-specs/blob/dev/specs/core/0_beacon-chain.md#slashings)
        - [x] Update [final updates functions](https://github.com/ethereum/eth2.0-specs/blob/dev/specs/core/0_beacon-chain.md#final-updates)
    - [x]  🔹 Update [per slot processing](https://github.com/ethereum/eth2.0-specs/blob/dev/specs/core/0_beacon-chain.md#per-slot-processing)🔹
    - [x]  🔹 Update [per block processing](https://github.com/ethereum/eth2.0-specs/blob/dev/specs/core/0_beacon-chain.md#per-block-processing)🔹
        - [x] Implement [process block header](https://github.com/ethereum/eth2.0-specs/blob/dev/specs/core/0_beacon-chain.md#block-header) | #2534
        - [x] Update [process randao](https://github.com/ethereum/eth2.0-specs/blob/dev/specs/core/0_beacon-chain.md#randao) | #2614
        - [x] Update [process eth1 data](https://github.com/ethereum/eth2.0-specs/blob/dev/specs/core/0_beacon-chain.md#eth1-data)
        - [x] Update [proposer slashing](https://github.com/ethereum/eth2.0-specs/blob/dev/specs/core/0_beacon-chain.md#proposer-slashings) | #2603
        - [x] Update [attester slashing](https://github.com/ethereum/eth2.0-specs/blob/dev/specs/core/0_beacon-chain.md#attester-slashings)
        - [x] Update [attestation processing](https://github.com/ethereum/eth2.0-specs/blob/dev/specs/core/0_beacon-chain.md#attestations)
        - [x] Update [deposits processing](https://github.com/ethereum/eth2.0-specs/blob/dev/specs/core/0_beacon-chain.md#deposits)
        - [x] Update [exits processing](https://github.com/ethereum/eth2.0-specs/blob/dev/specs/core/0_beacon-chain.md#voluntary-exits)
        - [x] Implement [transfers processing](https://github.com/ethereum/eth2.0-specs/blob/dev/specs/core/0_beacon-chain.md#transfers)
        - [x] Update [state root verification](https://github.com/ethereum/eth2.0-specs/blob/dev/specs/core/0_beacon-chain.md#state-root-verification)

- [x] 💎  **Verify and update [BLS](https://github.com/ethereum/eth2.0-specs/blob/dev/specs/bls_signature.md#bls-signature-verification)
     - [x] 🔹  add [bls verify](https://github.com/ethereum/eth2.0-specs/blob/dev/specs/bls_signature.md#bls_verify)

- [x] align RPC endpoint [eth1data to spec](https://github.com/ethereum/eth2.0-specs/blob/dev/specs/validator/0_beacon-chain-validator.md#eth1-data) | #2733

**Comment by prestonvanloon** [comment]
Discussed offline that we should not break master, but it is acceptable to break a [spec-v0.6](https://github.com/prysmaticlabs/prysm/tree/spec-v0.6) working branch so that [spec-v0.6](https://github.com/prysmaticlabs/prysm/tree/spec-v0.6) can be reviewed in pieces then reviewed once more in a merge to master. 

Please submit all PRs to branch [spec-v0.6](https://github.com/prysmaticlabs/prysm/tree/spec-v0.6)

**Comment by terenc3t** [comment]
Working on updating protofields for [Crosslink](https://github.com/ethereum/eth2.0) and [Eth1Data](https://github.com/ethereum/eth2.0-specs/blob/dev/specs/core/0_beacon-chain.md#eth1data)

**Comment by terenc3t** [comment]
Working on AttestationData, AttestationDataAndCustodyBit and IndexedAttestation

**Comment by 0xKiwi** [comment]
Working on updating constant names and values

**Comment by prestonvanloon** [comment]
Working on removing genesisSlot/genesisEpoch

**Comment by terenc3t** [comment]
please review proto changes in following order:
#2315, #2316, #2318, #2327, #2338, #2340 and #2341

**Comment by 0xKiwi** [comment]
Working on updating validator related helpers

**Comment by shayzluf** [comment]
working on balance helpers

**Comment by shayzluf** [comment]
working on Update permuted index helpers

**Comment by 0xKiwi** [comment]
Spec updates made to BeaconProposerIndex in #2352 were left out due to them being extremely drastic 
https://github.com/ethereum/eth2.0-specs/pull/920

**Comment by terenc3t** [comment]
working on updating committee related helpers

**Comment by terenc3t** [comment]
working on block root and state root helpers

**Comment by 0xKiwi** [comment]
Working on randao mix and active index helpers

**Comment by terencechain** [comment]
Working on `initiate_validator_exit`

**Comment by shayzluf** [comment]
working on splitoffset helper

**Comment by shayzluf** [comment]
working on Update active index root helpers

**Comment by shayzluf** [comment]
working on generate seed

**Comment by 0xKiwi** [comment]
Working on attesting indice helpers

**Comment by terencechain** [comment]
Working on updating [general helpers](https://github.com/ethereum/eth2.0-specs/blob/dev/specs/core/0_beacon-chain.md#helper-functions-1) for epoch processing in #2379

**Comment by shayzluf** [comment]
working on  Update beacon proposer index helpers

**Comment by nisdas** [comment]
working on update bitfield helpers and slashing validator

**Comment by 0xKiwi** [comment]
working on updating slash validator

**Comment by terencechain** [comment]
Working on `get_crosslink_from_attestation_data` and `get_winning_crosslink_and_attesting_indices`

**Comment by shayzluf** [comment]
working on Update attesting indices helpers

**Comment by shayzluf** [comment]
working on Update bitfield related helpers

**Comment by shayzluf** [comment]
working on Add convert to indexed

**Comment by terencechain** [comment]
working on `process_crosslinks`

**Comment by cyberbono3** [comment]
working on convert_to_indexed

**Comment by cyberbono3** [comment]
working on process_eth1_data

**Comment by cyberbono3** [comment]
working on updating deposits processing

**Comment by shayzluf** [comment]
registry updates functions

**Comment by shayzluf** [comment]
working on process block header

**Comment by shayzluf** [comment]
working on update get domain

**Comment by shayzluf** [comment]
working on Update Fork

**Comment by cyberbono3** [comment]
working on update process_attestation

**Comment by cyberbono3** [comment]
working on get_attestation_data_slot

**Comment by terencechain** [comment]
Working on all the committee related functions in #2592, they consists of:
-  Removed `CrosslinkCommitteeAtSlot`
-  Removed `CurrentEpochCommitteeCount`
-  Removed `PrevEpochCommitteeCount`
-  Removed `NextEpochCommitteeCount`
-  Updated `ComputeCommittee`
-  Updated `AttestationParticipants`
-  Updated `BeaconProposerIndex`
-  Updated `AttestationData` protobuf to include `target_epoch`
-  Removed old core functions which still used `CrosslinkCommitteeAtSlot`
-  Removed old epoch processing functions which still used `CrosslinkCommitteeAtSlot`

**Comment by terencechain** [comment]
@rauljordan is working on proposer slashing in #2603

**Comment by shayzluf** [comment]
working on process randao

**Comment by shayzluf** [comment]
working on attestation processing

**Comment by nisdas** [comment]
Working on updating deposit contract and state root verification

**Comment by shayzluf** [comment]
working on Update state root verification

**Comment by shayzluf** [comment]
working on bls verify

**Comment by cyberbono3** [comment]
working on process_final_updates

**Comment by terencechain** [comment]
@cyberbono3 `process_final_updates` is done

**Comment by prestonvanloon** [comment]
Please add a requirement that all TODO(2307) are done in spec-v0.6 branch

**Comment by rauljordan** [comment]
Completed in spec-v0.6
