### ISSUE TITLE
Testnet Feedback Tracking

### ISSUE THREAD

**Issue by terencechain** [prysmaticlabs/prysm#2522]
This issue tracks the feedback from users trying out prysm alpha test net. Please add them to the list as we gather more feedbacks.

- [ ] beacon node doesn't touch keys, we should make them separate dirs (beacon node and validator) in instruction
- [ ] for activation status, waiting for deposit to be included by validator, it would be great to better define what "it'll take a while" means time wise
- [ ] For testnet site instructions, use a docker volume for the key storage instead of something under /tmp/ ? since that is flushed on reboot
- [ ] Validator metrics are inaccurately logged, when you have a pending validator along with another active validator in the client. the balance deviation is shown as -50% .
