### ISSUE TITLE
[Mega Tracking] - Align spec to release v0.7

### ISSUE THREAD

**Issue by 0xKiwi** [prysmaticlabs/prysm#2790]
This is a PR for tracking our updates to v0.7.0 of the spec 🎊 

- [x] 💎 **Documentation updates**  💎
  - [x] Update documentation in [`process_slashings`](https://github.com/ethereum/eth2.0-specs/pull/1123/files#diff-51a43328a58414e132a744f3771f018cR1535) | #2791

- [x] 💎  **Update Protobuf data structures**  💎
  - [x] Remove `index` from [Deposit](https://github.com/ethereum/eth2.0-specs/pull/1122)

- [x] 💎 **Renames in configs and parameters**  💎
  - [x] Rename `MaxCrosslinkEpochs` to `MaxEpochsPerCrosslink` in Beacon Chain config | #2791
  - [x] Rename `BaseRewardQuotient` to [`BaseRewardFactor`](https://github.com/ethereum/eth2.0-specs/pull/1123/files#diff-51a43328a58414e132a744f3771f018cR227) | #2791
  - [x] Rename parameters in [`get_genesis_beacon_state`](https://github.com/ethereum/eth2.0-specs/pull/1049/files#diff-51a43328a58414e132a744f3771f018cR1195) | #2791

- [x] 💎  **Bug fixes**  💎
  - [x] Update [`get_previous_epoch` ](https://github.com/ethereum/eth2.0-specs/pull/1092/files#diff-51a43328a58414e132a744f3771f018cR650)
  - [x] Update [`process_justification_and_finalization`](https://github.com/ethereum/eth2.0-specs/pull/1092/files#diff-51a43328a58414e132a744f3771f018cR1365)
  - [x] Update [`get_total_balance`](https://github.com/ethereum/eth2.0-specs/pull/1123/files#diff-51a43328a58414e132a744f3771f018cR968)
  - [x] Update [`get_base_reward`](https://github.com/ethereum/eth2.0-specs/pull/1123/files#diff-51a43328a58414e132a744f3771f018cR1416)

- [x] 💎**New functions**  💎
  - [x] Implement [`bls_domain`](https://github.com/ethereum/eth2.0-specs/pull/1055)

- [x] 💎**Function changes**  💎
  - [x] Update `int_to_bytes` to be [generic](https://github.com/ethereum/eth2.0-specs/pull/1060)
  - [x] Update [`get_domain`](https://github.com/ethereum/eth2.0-specs/pull/1055/files#diff-51a43328a58414e132a744f3771f018cR982)
  - [ ] Update [`process_deposit`](https://github.com/ethereum/eth2.0-specs/pull/1055/files#diff-51a43328a58414e132a744f3771f018cR1781)
  - [ ] Update [deposit submission](https://github.com/ethereum/eth2.0-specs/pull/1055/files#diff-abbdef70b08ada829d740f06c004c154R101)

**Comment by prestonvanloon** [comment]
Can this be closed? everything is checked...

**Comment by terencechain** [comment]
The rest of the checklists will be addressed by
https://github.com/prysmaticlabs/prysm/pull/2797

**Comment by rauljordan** [comment]
Completed!
