### ISSUE TITLE
Write Test Runners for Spec Tests in Their Respective Packages

### ISSUE THREAD

**Issue by rauljordan** [prysmaticlabs/prysm#2812]
Hi all,

This is a tracking issue to ensure Prysm passes the latest Eth2 spec tests as maintained [here](https://github.com/ethereum/eth2.0-spec-tests/tree/master/tests). Every YAML file has a specific structure to it with specific expectations and configuration values. As discussed by the team offline, we agreed to keep these test runners constrained to the specific package they target. For example, the spec test runner for block processing should be kept in

```
/beacon-chain
  /core
    /blocks
      /spectest
        autogenerated.yaml.go
        block_processing_spec_test.go
      block_processing.go
```

This runner will have specific Go code for parsing and running the [block sanity tests](https://github.com/ethereum/eth2.0-spec-tests/tree/master/tests/sanity/blocks). This work can be split up, and [shuffling spec tests](https://github.com/ethereum/eth2.0-spec-tests/tree/master/tests/shuffling/core) have already been handled by @shayzluf [here](https://github.com/prysmaticlabs/prysm/blob/b2ddee1ae8f93e502b3a44479a60abcb641b1155/beacon-chain/chaintest/backend/simulated_backend.go#L175), but they should still be moved somewhere closer to the core shuffling logic in a respective /spectest folder as outlined above. The TODOS are as follow:

- [x] Isolate [shuffling related spec tests](https://github.com/ethereum/eth2.0-spec-tests/tree/master/tests/shuffling/core) and their runner closer to the shuffling core logic #2829
- [x] Implement [block processing](https://github.com/ethereum/eth2.0-spec-tests/tree/master/tests/sanity/blocks) sanity tests runner #2817
- [x] Implement [slot processing](https://github.com/ethereum/eth2.0-spec-tests/tree/master/tests/sanity/slots) sanity tests runner #2813
- [x] Implement epoch processing [crosslink](https://github.com/ethereum/eth2.0-spec-tests/tree/master/tests/epoch_processing/crosslinks) tests runner #2814
- [x] Implement epoch processing [registry updates](https://github.com/ethereum/eth2.0-spec-tests/tree/master/tests/epoch_processing/registry_updates) runner #2814
- [x] Implement block [attestation](https://github.com/ethereum/eth2.0-spec-tests/tree/master/tests/operations/attestation) operations test runner #2828
- [x] Implement block [attester slashing](https://github.com/ethereum/eth2.0-spec-tests/tree/master/tests/operations/attester_slashing) operations test runner #2828
- [x] Implement block [block header](https://github.com/ethereum/eth2.0-spec-tests/tree/master/tests/operations/block_header) operations test runner #2828
- [x] Implement block [deposit](https://github.com/ethereum/eth2.0-spec-tests/tree/master/tests/operations/deposit) operations test runner #2828
- [x] Implement block [proposer slashing](https://github.com/ethereum/eth2.0-spec-tests/tree/master/tests/operations/proposer_slashing) operations test runner #2828
- [x] Implement block [transfer](https://github.com/ethereum/eth2.0-spec-tests/tree/master/tests/operations/transfer) operations test runner #2828
- [x] Implement block [voluntary exit](https://github.com/ethereum/eth2.0-spec-tests/tree/master/tests/operations/voluntary_exit) operations test runner #2828
- [x] Implement SSZ [generic/core](https://github.com/ethereum/eth2.0-spec-tests/tree/master/tests/ssz_generic/uint) test runner
- [x] Implement [BLS](https://github.com/ethereum/eth2.0-spec-tests/tree/master/tests/bls) tests #2826
- [x] Implement finalization and justification tests #2896 
- [x] Implement final updates tests #2901
- [x] Genesis trigger spec tests #2940
- [x] Update YAMLs from spec freeze

**Comment by prestonvanloon** [comment]
Example gist of using upstream eth2 yaml as a runfile data via bazel: https://gist.github.com/prestonvanloon/7beb97de9d22651dd5bf318135bb4520

Please choose the appropriate test size https://docs.bazel.build/versions/master/test-encyclopedia.html#role-of-the-test-runner

Please tag all of the spec tests with `manual` and `spectest`.

```python
# Example test target (exclude the comments in prod BUILD files)
go_test(
   name = "go_default_test",
   ...
    
   size = "large", # Implied test timeout of 300s; choose appropriate size.
   tags = [
        "manual", # So it doesn't run on `bazel test //...`
        "spectest", # So we can query for spec tests.
    ],
)
```

**Comment by rauljordan** [comment]
I am taking up SSZ

**Comment by prestonvanloon** [comment]
Is this a complete list of all yamls upstream? 
```
tests
├── bls
│   ├── aggregate_pubkeys
│   ├── aggregate_sigs
│   ├── msg_hash_g2_compressed
│   ├── msg_hash_g2_uncompressed
│   ├── priv_to_pub
│   └── sign_msg
├── epoch_processing
│   ├── crosslinks
│   └── registry_updates
├── operations
│   ├── attestation
│   ├── attester_slashing
│   ├── block_header
│   ├── deposit
│   ├── proposer_slashing
│   ├── transfer
│   └── voluntary_exit
├── sanity
│   ├── blocks
│   └── slots
├── shuffling
│   └── core
├── ssz_generic
│   └── uint
└── ssz_static
    └── core
```

**Comment by prestonvanloon** [comment]
Waiting for spec freeze to cut new (final) yaml files to resolve this.

**Comment by prestonvanloon** [comment]
There are some new tests: https://gist.github.com/prestonvanloon/ad815f6bd4c132018f16f53b436e2440

**Comment by rauljordan** [comment]
Completed in the spec-v0.6 branch

**Comment by prestonvanloon** [comment]
There are still two PRs that are open:

#2901 - Final updates spec test
#2905 - Genesis trigger update
TBD - Genesis trigger spec tests

**Comment by prestonvanloon** [comment]
Some details about genesis yaml test here: https://github.com/prysmaticlabs/prysm/issues/2934

**Comment by 0xKiwi** [comment]
Genesis Spec Tests complete, #2940 builds fine!

**Comment by rauljordan** [comment]
Closed by #2940
