### ISSUE TITLE
Align to the latest v0.8 Beacon Chain Spec

### ISSUE THREAD

**Issue by terencechain** [prysmaticlabs/prysm#2891]
This is a tracking issue to ensure our beacon chain implementation is up to date with the latest v0.8 spec. The target is: https://github.com/ethereum/eth2.0-specs/commit/8d324b7497bcb558e0183a30002d78d18704e3fa

**features**

- [x] minor modification to inclusion rewards and adjust reward factor (https://github.com/ethereum/eth2.0-specs/pull/1159) #2888
- [x] increase historical vectors length and cleanups (https://github.com/ethereum/eth2.0-specs/pull/1196) #2876
- [x] introduce Checkpoint type (https://github.com/ethereum/eth2.0-specs/pull/1210) #2877
- [x] slashing penalty calculation change to prevent gaming (https://github.com/ethereum/eth2.0-specs/pull/1217) #2889
- [x] add compact committee roots for light client support (https://github.com/ethereum/eth2.0-specs/pull/1219, https://github.com/ethereum/eth2.0-specs/pull/1247) #2897 

**simplifications**
- [x] cleanup containers (https://github.com/ethereum/eth2.0-specs/pull/1156) #2872
- [x] remove sort from get_attesting_indices and instead return set (https://github.com/ethereum/eth2.0-specs/pull/1225) #2893 
- [x] cleanup how genesis is calculated and triggered (https://github.com/ethereum/eth2.0-specs/pull/1202) #2905 **on-going**
- [x] cleanup helpers grouping, consistency in naming, comments, etc (https://github.com/ethereum/eth2.0-specs/pull/1237, https://github.com/ethereum/eth2.0-specs/pull/1241) #2895
- [x] add bls domain type (https://github.com/ethereum/eth2.0-specs/pull/1246) (json encoder understands the bytes to uint64)
- [x] basket of minor cleanups (https://github.com/ethereum/eth2.0-specs/pull/1251) #2893
 
**bugs**
- [x] critical Transfer bug (https://github.com/ethereum/eth2.0-specs/pull/1220) #2890 
- [x] fix genesis effective balance in corner case (https://github.com/ethereum/eth2.0-specs/pull/1248) #2890 
- [x] fix scaling for inclusion_reward (https://github.com/ethereum/eth2.0-specs/pull/1257) #2890 
 
**misc**
- [x] set MIN_ATTESTATION_INCLUSION_DELAY to 1 in mainnet config (https://github.com/ethereum/eth2.0-specs/pull/1157) #2876
- [x] make explicit which constants are configurable or not (https://github.com/ethereum/eth2.0-specs/pull/1191) #2898
- [x] clarify validity conditions for initiating a transfer (https://github.com/ethereum/eth2.0-specs/pull/1213)
- [x] remove bounds check in compute_shuffled_index (https://github.com/ethereum/eth2.0-specs/pull/1252) (we'll still do this check)
- [x] minor formatting/typos/etc PRs (https://github.com/ethereum/eth2.0-specs/pull/1203, https://github.com/ethereum/eth2.0-specs/pull/1214, https://github.com/ethereum/eth2.0-specs/pull/1215, https://github.com/ethereum/eth2.0-specs/pull/1212, https://github.com/ethereum/eth2.0-specs/pull/1230, https://github.com/ethereum/eth2.0-specs/pull/1221, https://github.com/ethereum/eth2.0-specs/pull/1235, https://github.com/ethereum/eth2.0-specs/pull/1234, https://github.com/ethereum/eth2.0-specs/pull/1243, https://github.com/ethereum/eth2.0-specs/pull/1245, https://github.com/ethereum/eth2.0-specs/pull/1249, https://github.com/ethereum/eth2.0-specs/pull/1255, https://github.com/ethereum/eth2.0-specs/pull/1256)

**Comment by shayzluf** [comment]
working on add compact committee roots get_compact_committees_root

**Comment by terencechain** [comment]
> working on add compact committee roots get_compact_committees_root

I'm pretty sure @nisdas has been working on that. It says on going with a PR number

**Comment by shayzluf** [comment]
yes he updated me. and i added his pr to the issue. just forgot to remove my comment. not working on it anymore

**Comment by terencechain** [comment]
This is done, great job everyone! 🎈
