### ISSUE TITLE
[Mega tracking] - Align Prysm to 0.8.1

### ISSUE THREAD

**Issue by terencechain** [prysmaticlabs/prysm#2969]
This is a tracking issue to ensure our beacon chain implementation is up to date with the latest v0.8x spec. The target is: https://github.com/ethereum/eth2.0-specs/commit/452ecf8e27c7852c7854597f2b1bb4a62b80c7ec
 
**bugs**

- [x]  fix off-by-one bug in randomness seed lookahead (https://github.com/ethereum/eth2.0-specs/pull/1296)
- [x] call pack when merkeizing bitlist/vector https://github.com/ethereum/eth2.0-specs/pull/1271)
- [x] corrections to merkleization (https://github.com/ethereum/eth2.0-specs/pull/1292)
- [x] avoid overflow in slashing calculation (https://github.com/ethereum/eth2.0-specs/pull/1286) #2977

**non-substantive**

- [x] define bitlist/vector wrt bytes, not bigints (https://github.com/ethereum/eth2.0-specs/pull/1267)
- [x] clarify zero hash representation using Bytes32 (https://github.com/ethereum/eth2.0-specs/pull/1297)
- [x] update test formats list in readme (https://github.com/ethereum/eth2.0-specs/pull/1265)
- [x] fix test generator make command in readme (https://github.com/ethereum/eth2.0-specs/pull/1268)
- [x] minor fix to typing (https://github.com/ethereum/eth2.0-specs/pull/1263)
- [x] minor fix to headers/toc (https://github.com/ethereum/eth2.0-specs/pull/1285)
- [x] minor cosmetic fixes (https://github.com/ethereum/eth2.0-specs/pull/1275)

**Comment by shayzluf** [comment]
working on - avoid overflow in slashing calculation

**Comment by shayzluf** [comment]
working on fix off-by-one bug in randomness seed lookahead

**Comment by terencechain** [comment]
Done
