### ISSUE TITLE
[Tracking] Implement EthereumAPI v1alpha1

### ISSUE THREAD

**Issue by terencechain** [prysmaticlabs/prysm#3045]
This PR tracks the overall progress of implementing RPC methods for what's defined in ethapi's [v1alpha1](https://github.com/prysmaticlabs/ethereumapis/tree/master/eth/v1alpha1)

Beacon chain:
- [x] `ListAttestations` - Retrieve attestations by head root, source root/epoch, target root/epoch
- [x] `AttestationPool` - Retrieve pool attestations
- [x] `ListBlocks` - List blocks by root, slot or epoch
- [x] `GetChainHead` - Get chain head
- [x] `ListValidatorBalances` - List validator balances for a given set of public keys at a specific epoch in time
- [x] `GetValidators` - List active validators, optional historical epoch to retrieve validator set in time
- [x] `GetValidatorActiveSetChanges` - List active set changes for a given epoch, includes activations, exists, and involuntary ejections
- [x] `GetValidatorQueue` - Retrieve the current validator queue information
- [x] `ListValidatorAssignments ` - Retrieve validator assignment of a given epoch, optional validator indices or public keys for filter
- [x] `GetValidatorParticipation ` - Retrieve the validator participation information of a given epoch

Node:
- [x] `GetSyncStatus` - Retrieve the current sync status of the node
- [x] `GetGenesis` - Retrieve the genesis information from the node  
- [x] `GetVersion` - Retrieve the node version
- [x] `ListImplementedService` - Retrieve the list of services implemented and enabled by this node

Beacon node <-> validator:
- [x] `GetDuties`
- [x] `GetBlock`
- [x] `ProposeBlock`
- [x] `GetAttestationData` 
- [x] `ProposeAttestation`

**Comment by rauljordan** [comment]
Interested in the `Node` category, as well as block and attestation information from the beacon node

**Comment by terencechain** [comment]
working on `GetValidators` and `ListValidatorBalances`

**Comment by rauljordan** [comment]
Workin on `ListAttestations` and `AttestationPool`

**Comment by terencechain** [comment]
Working on `ListValidatorAssignments`

**Comment by terencechain** [comment]
Working on `ListBlocks`

**Comment by prestonvanloon** [comment]
GetValidatorParticipation doesn't filter by epoch. Unchecked that box and marked as partially implemented.

**Comment by prestonvanloon** [comment]
ListValidatorBalances doesn't filter by epoch. Unchecked that box and marked partially implemented.

**Comment by prestonvanloon** [comment]
ListValidatorBalances fails to return full list of validators.
ListValidatorBalances fails to return list validators when an empty public key is passed.

**Comment by rauljordan** [comment]
This is currently blocked by #3064

**Comment by rauljordan** [comment]
We are now unblocked on this - picking up work on this issue now

**Comment by mkosowsk** [comment]
@rauljordan awesome! Thanks 🙏

Gonna add `Attestation Pool` to Mytchmatic and then onward from there!
