### ISSUE TITLE
[Tracking] Caches are causing unstable results

### ISSUE THREAD

**Issue by prestonvanloon** [prysmaticlabs/prysm#3106]
Some caches (see [cache pkg](https://godoc.org/github.com/prysmaticlabs/prysm/beacon-chain/cache)) are causing invalid block proposals, attestations, and other unknown side effects.

This is a tracking issue to disable and carefully re-evaluate each cache mechanism.

Safe caches:
- [ActiveCountCache](https://github.com/prysmaticlabs/prysm/blob/e744d1a07e4ee33e77ef54d4cd84d619fc746853/beacon-chain/cache/active_count.go). The validator active count is only updated on finality. There is no risk of fork conditions to corrupt this cache.
- [ActiveIndicesCache](https://github.com/prysmaticlabs/prysm/blob/e744d1a07e4ee33e77ef54d4cd84d619fc746853/beacon-chain/cache/active_indices.go). Also only updated on finality. No risk from fork condition.
- [ShuffledIndicesCache](https://github.com/prysmaticlabs/prysm/blob/e744d1a07e4ee33e77ef54d4cd84d619fc746853/beacon-chain/cache/shuffled_indices.go). Indices only updated on finality. No risk from fork condition.

Everything else is unsafe from forking and other conditions.
- [ ] [ActiveBalanceCache](https://github.com/prysmaticlabs/prysm/blob/e744d1a07e4ee33e77ef54d4cd84d619fc746853/beacon-chain/cache/active_balance.go)
- [ ] [AttestationCache](https://github.com/prysmaticlabs/prysm/blob/e744d1a07e4ee33e77ef54d4cd84d619fc746853/beacon-chain/cache/attestation_data.go)
- [ ] [AncestorBlockCache](https://github.com/prysmaticlabs/prysm/blob/e744d1a07e4ee33e77ef54d4cd84d619fc746853/beacon-chain/cache/block.go)
- [ ] [Eth1DataVoteCache](https://github.com/prysmaticlabs/prysm/blob/88b715d8f65a6e2bd752b02eadb30bf0b5d22f18/beacon-chain/cache/eth1_data.go)
- [ ] [SeedCache](https://github.com/prysmaticlabs/prysm/blob/88b715d8f65a6e2bd752b02eadb30bf0b5d22f18/beacon-chain/cache/seed.go)
- [ ] [StartShardCache](https://github.com/prysmaticlabs/prysm/blob/88b715d8f65a6e2bd752b02eadb30bf0b5d22f18/beacon-chain/cache/start_shard.go)
- [ ] [TotalBalanceCache](https://github.com/prysmaticlabs/prysm/blob/e744d1a07e4ee33e77ef54d4cd84d619fc746853/beacon-chain/cache/total_balance.go)

The above caches are checked when they have been reimplemented with careful consideration or removed entirely. 

Misc tasks:

- [x] Disable all unsafe caches and toggle via feature flags. #3107

**Comment by prestonvanloon** [comment]
The StartShardCache is incorrectly caching start shards after epoch transitions. See more background in https://github.com/prysmaticlabs/prysm/issues/3083.

**Comment by terencechain** [comment]
We can close this when #3631 is merged

**Comment by prestonvanloon** [comment]
Related #3664.

**Comment by rauljordan** [comment]
We can close this as it is nearly identical to #3603
