### ISSUE TITLE
[Mega tracking] - Implement policing service

### ISSUE THREAD

**Issue by shayzluf** [prysmaticlabs/prysm#3133]
While starting the design process of policing service that will keep an eye at the network for finding slashable events. as well as protect his own subscribers (Validators) from creating a slashable event.

The way to a full blown policing service is comprised of these steps:
Bug fixes:
- [x] grpc proto api #3134
- [x] separate db for slasher #3270 
- [x] making slasher grpc server #3271 
- [x] Store historical block headers in local db #3270
- [x] Store indexed attestations in db #3322 / #3897 
- [x] Store min max span per validator #3941
- [x] Update min max span per validator #3951
- [x] Detect surround attestations using min max span #3967
- [x] Proposer slashing detection (db keys)
- [x] Double Attestation detection (db keys) 
- [x] Surround attestation detection ([min max span](https://github.com/protolambda/eth2-surround))
- [x] Benchmark surround attestation detection
- [x] Slasher grpc client of beacon node
- [ ] Store active validator state per epoch
- [ ] Store validator index to public key map 
- [ ] Validate attestation signature
- [ ] Purge attestations and historic block headers bucket to max size #3270

- [ ] Beacon server detection of all slashable events of its subscribed validators(bitmap 54000 epoches X number of running validators). By storing all the data concerning them in db and validating against it. Panic in case a rpc call is going to create a slashable event. 
- [ ] Slasher server with pruning at weak subjectivity period 
- [ ] Beacon node / Slasher communication. to feed slasher with attestations and block proposals.
- [ ] Beacon node / Slasher communication. to listen slashable events
- [ ] Slashing simulator

**Comment by prestonvanloon** [comment]
Design doc: https://docs.google.com/document/d/12Eg-ysK5aQKQIjTKL6srqu8-ZY44iZ2MNwuqPaymlYk/edit#

**Comment by rauljordan** [comment]
Suggestion to name the watchtower server Bazel binary that's in charge of policing slashable events across beacon nodes the **"Hash Slinging Slasher"** after the iconic Spongebob Squarepants villain (credits to @prestonvanloon)

<img width="482" alt="Screen Shot 2019-08-05 at 8 56 49 AM" src="https://user-images.githubusercontent.com/5572669/62469998-04b11100-b75f-11e9-88f6-ec1db94f3ef3.png">

**Comment by shayzluf** [comment]
> Suggestion to name the watchtower server Bazel binary that's in charge of policing slashable events across beacon nodes the **"Hash Slinging Slasher"** after the iconic Spongebob Squarepants villain (credits to @prestonvanloon)
> 
> <img alt="Screen Shot 2019-08-05 at 8 56 49 AM" width="482" src="https://user-images.githubusercontent.com/5572669/62469998-04b11100-b75f-11e9-88f6-ec1db94f3ef3.png">

should i change the folder name?

**Comment by rauljordan** [comment]
Closing this in favor of #4836
