### ISSUE TITLE
[Mega Tracking] Align Prysm to Interop Networking Spec

### ISSUE THREAD

**Issue by prestonvanloon** [prysmaticlabs/prysm#3147]
The new interop networking spec has been merged (https://github.com/ethereum/eth2.0-specs/pull/1328). 

### Spec requirements ###

Interop requirements:
- [x] Support libp2p TCP transport for inbound/outbound IPv4 and IPv6 addresses.
- [x] Expose at least one IPv4 endpoint. #3211 
- [x] All endpoints must be publicly dialable (no advertising local networked addresses or relay)
- [x] Testnet infrastructure configured to enable direct, inbound traffic 
- [x] SecIO w/ secp256k1 for identity 
- [x] mplex protocol for multiplexing
- [x] (optional) yamux protocol for multiplexing
- [x] Gossipsub alignment 
- [x] RPC (req/res) alignment 
- [x] Discovery (discv5) alignment

Mainnet requirements:
- [x] Noise handshakes (Moved to #3687)

### Code changes ###

_Not in any particular order_. See [networking design doc](https://docs.google.com/document/d/1VyhobQRkEjEkEPxmmdWvaHfKWn0j6dEae_wLZlrFtfU/edit).

Migration:
- [x] Move/prefix sync and p2p packages with `deprecated-` as part of the migration. #3190 #3191
- [x] Mark existing p2p pb messages as deprecated #3194
- [x] Mark existing topic mappings as deprecated #3192 #3194

`p2p` package:
- [x] Add new p2p package with boilerplate libp2p configuration #3196 
- [x] Add unit tests and explicit config to ensure libp2p configuration parameters meet the network spec requirements #3200

`p2p` encoding:
- [x] Add API for encoding registration 
- [x] Register `ssz` encoder/decoder #3198 #3210
- [x] Register `ssz_snappy` encoder/decoder #3198  #3210
- [x] Add encoding enum flag for selecting the p2p encoding #3256
- [x] Prefix ssz encoded data with protobuf.Varint length indicator #3210

`p2p` hello/goodbye:
- [x] Add peerstore abstraction for tracking handshake responses
- [x] Add handler for hello #3216 
- [x] Add handler for goodbye #3282

Initial sync:
- [x] Add round robin sync strategy
- [x] Add logic to sync round robin up to finalized epoch
- [x] Add logic to sync to head after finalized epoch

Topic mappings:
- [x] Add new message topic mappings #3201

Regular sync RPC:
- [x] `/eth2/beacon_chain/req/beacon_blocks/1/{ssz,ssz_snappy}` handler #3218
- [x] `/eth2/beacon_chain/req/recent_beacon_blocks/1/{ssz,ssz_snappy}` handler #3281
- [x] `/eth2/beacon_chain/req/hello/1/{ssz,ssz_snappy}` handler #3216 
- [x] `/eth2/beacon_chain/req/goodbye/1/{ssz,ssz_snappy}` handler #3282
- [x] Add new message types #3199 

Regular sync gossip sub:
- [x] `/eth2/beacon_block/{ssz,ssz_snappy}` handler & validator #3220 
- [x] `/eth2/beacon_attestation/{ssz,ssz_snappy}` handler & validator 
- [x] `/eth2/voluntary_exit/{ssz,ssz_snappy}` handler & validator #3227
- [x] `/eth2/proposer_slashing/{ssz,ssz_snappy}` handler & validator
- [x] `/eth2/attester_slashing/{ssz,ssz_snappy}` handler & validator

Broadcaster:
- [x] Broadcast with encoding #3226

Fork choice:
- [x] Add ReceiveBlock path that does not apply fork choice (for initial sync up to finalized epoch)

Discovery:
- [x] Change bootnode to use Discv5 instead of kademlia #3203
- [x] Allow node discovery via Discv5. #3211 
~~- [ ] Handle topic search for stored node records.~~
~~- [ ] Standardize interfaces to match libp2p for [discovery](https://github.com/libp2p/go-libp2p-core/blob/master/discovery/discovery.go#L12) and [peer routing](https://github.com/libp2p/go-libp2p-core/blob/master/routing/routing.go#L36-L44)~~
- [x] ENR for nodes in prysm must conform with the required fields as stated [here](https://github.com/ethereum/eth2.0-specs/blob/dev/specs/networking/p2p-interface.md#enr-structure)

Ssz:
- [x] Add support for proto enum fields (int32) https://github.com/prysmaticlabs/go-ssz/issues/66

**Comment by terencechain** [comment]
Interested in gossips and rpc alignments

**Comment by nisdas** [comment]
interested in discovery and RPC alingment
