### ISSUE TITLE
[Mega Tracking] Integrate latest forkchoice to run time

### ISSUE THREAD

**Issue by terencechain** [prysmaticlabs/prysm#3219]
This is an overall tracking for integrating latest fork choice in run time:

- [x] Implement the new fork choice spec as a service #3209
- [x] benchmark fork choice implementation #3212 
- [x] Implement yaml driven test framework #3213 
- [x] Mark the old `ReceiveBlock`, `ReceiveAttestation` method in `blockchain` service as deprecated #3215 
- [x] Mark the old fork choice run time functions as deprecated #3215 
- [x] Implement new `ReceiveBlock` in `blockchain` service #3242
- [x] Implement new `ReceiveAttestation` in `blockchain` service #3246 
- [x] Implement chain info interface to query head, finalized check point and canonical roots #3263 
- [x] Update `sync` service to use the new `ReceiveBlock` and `ReceiveAttestation` from `blockchain` service
- [x] Update `initsync` service to use the new `ReceiveBlock` and `ReceiveAttestation` from `blockchain` service
- [x] Update `rpc` service to use the new `ReceiveBlock` and `ReceiveAttestation` from `blockchain` service
- [x] Update `blockchain` service to use the new fork choice and new DB
- [x] Add doc on how fork choice works in `doc.go`
- [x] Add forking metrics in `metric.go`
- [x] Add trancing/spans
- [x] Test local run time, 1 node 8 validators
- [x] Test local run time, 2 nodes 4 validators each
- [x] Test local run time, 3 nodes 3,3,2 validators each
- [x] Test local run time, 2 nodes 32 validators each
- [x] Test cluster

forkchoice spec:
https://github.com/ethereum/eth2.0-specs/blob/dev/specs/core/0_fork-choice.md
