### ISSUE TITLE
[Tracking] Interop mock start

### ISSUE THREAD

**Issue by rauljordan** [prysmaticlabs/prysm#3398]
This issue tracks progress on the interop mock start functionality which is needed for cross-client testing
- [x] Deterministically generate validator private keys using the method outlined in the interop doc [here](https://github.com/ethereum/eth2.0-pm/tree/master/interop/mocked_start)
- [x] Create a tool to generate a `genesis_state.yaml`, `genesis_state.ssz`, or `genesis_state.json` from the deterministic set of private keys
- [x] Skip checking of `is_valid_genesis_state` in Prysm if a `--genesis-state genesis.yaml` flag is provided or if another cold start option is done
- [x] Allow starting from `--mock-start-validator-count N --mock-start-genesis-time TIMESTAMP` as a simple solution in the beacon chain
- [x] Allow starting from `--mock-start-validator-count N --mock-start-genesis-time TIMESTAMP` as a simple solution in the validator client
- [x] Mock the ETH1 chain in Prysm if any of the mock start flags are provided according to [these rules](https://github.com/ethereum/eth2.0-pm/issues/62)
