### ISSUE TITLE
[Tracking] Post Interop Top Priorities

### ISSUE THREAD

**Issue by rauljordan** [prysmaticlabs/prysm#3450]
Thanks to @prestonvanloon for this list:

Top Priorities Are:
- [x] Regular sync resilience (handling missing parent blocks)
- [x] Scaling validator count (BLS padding issue, attestion handling locks)
- [x] P2P stream issues 
- [x] Networking spec update
- [x] Round robin sync

Second tier priorities are:
- [ ] SSZ resilience (never panic, fuzz testing, stack overflow)
- [ ] Test coverage improvements (mutation testing) #2910, package cleanup, documentation
- [x] Add the following consensus test cases from [interop](https://github.com/djrtwo/interop-test-cases)
- [x] Metrics, monitoring, UX
- [x] API completion #3045

**Comment by rauljordan** [comment]
This is also too open ended to ever be resolved - instead, we should open the remaining items as specific tracking issues with clear goals. Closing for now.
