### ISSUE TITLE
Improve and standardize prysm caching

### ISSUE THREAD

**Issue by terencechain** [prysmaticlabs/prysm#3603]
This PR tracks the overall progress on improving and standardizing Prysm cache.

Working items:

- [x] Remove the deprecated caches (i.e. total balance, start shard, seed) #3584 
- [x] Can retrieve shuffled committee indices by inputting state and epoch #3605
- [x] Can cache for shuffled committee indices #3607
- [x] Can update committee cache in block processing #3617
- [x] Use a feature flag #3619
- [x] Make use of the committee cache in helper functions #3625 
- [x] Enhance cache for active validator indices #3629
- [x] Deprecate active indices, shuffled indices and active count caches for the newly implemented committee cache #3631

Reference doc:  https://docs.google.com/presentation/d/1I9ToaccGX-arYoojzexpj3x22qTsoxsnTT8yUyH-kHY/edit#slide=id.p

**Comment by rauljordan** [comment]
This can be closed as we are now taking a more thorough approach to caching with fuzz tests where appropriate, making only incremental changes
