### ISSUE TITLE
Attestation Aggregation is Broken

### ISSUE THREAD

**Issue by rauljordan** [prysmaticlabs/prysm#3744]
- [x] Use bitfield utils to detect overlaps instead of the bitfield.Contains function when handling attestations in operations service #3747 
- [ ] Change the key for attestations to be the SigningRoot of the entire attestation rather than simply the HashTreeRoot 
- [ ] Explore optimal strategy for detecting the overlapped attestations

**Comment by prestonvanloon** [comment]
Related: https://github.com/prysmaticlabs/go-bitfield/pull/18

**Comment by terencechain** [comment]
It is required to have todo 1 and 2 merged together for run time

**Comment by prestonvanloon** [comment]
Also need to add functionality to the attestation pool for maximum profit / attestation inclusion. 

For a first pass, we'll naively fill blocks up to max attestations. We must revisit the scenarios where full blocks must select the most profitable attestations.

**Comment by prestonvanloon** [comment]
Added a full design for this solution: https://hackmd.io/@prestonvanloon/better_aggregation_inclusion

**Comment by terencechain** [comment]
Completed via #3790, it's working run time
