### ISSUE TITLE
Implement naive aggregations strategy

### ISSUE THREAD

**Issue by terencechain** [prysmaticlabs/prysm#3835]
This issue tracks the necessary changes needed to implement the naive aggregation strategy as outlined [here](https://github.com/ethereum/eth2.0-specs/pull/1440/files). To break it down into smaller tasks:
- [ ] Update sync service
- [x] Update pool service
- [x] Implement new helpers #3837 
- [x] Implement new proto field #3836

**Comment by rauljordan** [comment]
@terencechain can we open up some specific tracking issues for these items? Specifically I see a TODO in the v0.9.2 branch [here](https://github.com/prysmaticlabs/prysm/blob/25b6aa0d33eaefd23da2655837c282cfe4a580a6/beacon-chain/sync/validate_aggregate_proof.go#L54). What do you think?

**Comment by terencechain** [comment]
Oh we forgot about that todo, we can roll it in after the testnet launches

**Comment by terencechain** [comment]
But that is the last one, the rest is done

**Comment by rauljordan** [comment]
Could you kindly help open a tracking issue outlining the TODO and resolution?
