### ISSUE TITLE
Attestation pool tracking for v0.9.2

### ISSUE THREAD

**Issue by terencechain** [prysmaticlabs/prysm#4224]
This tracks the current progress of attestation pool revamp for v0.9.2 

- [x] Attestation pool basic CRUD methods #4191 
- [x] RPC Attester server uses pool #4223 
- [x] RPC Proposer server uses pool #4223
- [x] RPC Aggregator server uses pool #4223
- [ ] Sync aggregation subscription uses pool #4240 
 - [ ] Sync committee_index unaggregated subscription uses pool
- [ ] Fork choice service uses pool
- [ ] Delete attestations object in pool after seen in sync #4241

**Comment by rauljordan** [comment]
@terencechain this can now be closed right?

**Comment by terencechain** [comment]
Can be closed with merging of #4316
