### ISSUE TITLE
Beacon Node Optimizations

### ISSUE THREAD

**Issue by rauljordan** [prysmaticlabs/prysm#4508]
This is a tracking issue for all optimization-related items for our current testnet. We are seeing massive CPU/Memory usage coupled with really slow sync times affecting everyone connected to the network. We will be opening up TODO items in this issue and tackling them as we go along, as well as updating this issue with any new optimizations we deem reasonable.

- [x] Batch save validator indices calls #4489
- [x] Optimize filter block trie #4515 
- [x] Optimize archival assignments #4480 
- [x] Optimize beacon proposer index #4500 
- [x] Optimize attestation inclusion #4513
- [x] Fix the SSZ caching mechanism to prevent failures in prod

**Comment by rauljordan** [comment]
All items done!
