### ISSUE TITLE
Documentation Improvements Tracking

### ISSUE THREAD

**Issue by rauljordan** [prysmaticlabs/prysm#4734]
Hi all,

This is a tracking issue to determine next priorities for the Prysm project in terms of documentation needs. @har00ga fully ported our docs into our shiny new website: https://docs.prylabs.network where it is maintained as an open-source project in [github.com/prysmaticlabs/documentation](https://github.com/prysmaticlabs/documentation).

We want running our code and eth2 to be as friendly as possible, making it easy for users to understand any bugs they may run into and answer as many frequent concerns as possible. To do this, we need to make our codebase even more thoroughly documented and standardized.

Here are some important action items we need to take to bring Prysm to the next level:

- [ ] Create thorough godoc package-level comments for all the folders in Prysm, and improve current ones to be more informative (i.e. avoiding stuff like "package blocks contains stuff for blocks")
- [x] Get rid of the `docs/` folder in `prysm` and instead publish those items in our docs portal (some are out of date and need to be reconsidered)
- [x] Add better READMEs for the various tools in `prysm/tools`
- [x] Include a debugging section in our docs portal explaining how to file a bug report, how to search if your bug has already occurred (link to Github issues with the bug label), last case resort to reach out on discord to the team
- [ ] Include a better coding guide in our docs portal, right now we have some basic go tips but we can use something a bit more robust such as https://github.com/uber-go/guide with some tweaks
- [x] In the `Getting Started` section of our docs portal, we can be a bit more specific for our users (see https://docs.lotu.sh/) outlines install sections clearly for Windows, MacOS, Linux, etc. We should also add section for Arm and Raspberry PI devices in general
- [x] Inspired by https://docs.lotu.sh/, we should have a section in the getting started pages for setup troubleshooting (i.e. why am I not getting peers? Why is docker crashing? Why do I get this weird error on startup of the beacon chain?)
- [ ] Add a developer tools section where we can explain how to use prometheus, setup grafana, use jaeger for tracing of our beacon chain, and more
- [x] In the developer tools section also have a page for each of the various tools in the `prysm/tools` directory and how to use them
- [x] Updating the required reading section instead to a top level `Recommended Readings & Resources`, and update the links in there to be more relevant. Have a page for Go specific readings, maybe one for eth2, etc.
- [x] Rename Ethereum 2.0 Public API to a top-level section in the docs called `Public API` and add more details about its rationale, some of the endpoints available, and why we are using protobuf and gRPC (some justification can be found in https://github.com/prysmaticlabs/ethereumapis/issues/91
- [x] Check for your validator activation docs: remind users to copy their public key somewhere when they run their validator client. Point users to https://beacon.etherscan.io where they can paste in their public key and see the eth1 deposit information for their validator. Let users know they can also see their estimated time to activation by looking up their public key on https://beaconcha.in

Please suggest any other items that could help improve the Prysm developer/user experience as reflected in our docs! Tagging our docs expert @har00ga

**Comment by har00ga** [comment]
It's like a technical writers Christmas list. :joy: Happy to help with these / any new additions that come in!

**Comment by Mrtenz** [comment]
Some documentation I'd like to see:
* Command line options for the beacon node and validator.
* How to use your own eth1 node.
* Instructions for running the beacon node and validator with `docker-compose`. [Here](https://gist.github.com/Mrtenz/bfcd2aacd3c19be5ee80fd62bcca9896) is my stack for example, though it includes Geth, Watchtower and Eth2stats as well, which may be a little bit overkill.

**Comment by har00ga** [comment]
By suggestion of @prestonvanloon: Include documentation for running and syncing a eth1 node on port 8545 and 8546 and use flags `--http-web3provider=localhost:8545` and `--web3provider=localhost8546`. Include link to go-ethereum documentation on eth1 node setup.

**Comment by rauljordan** [comment]
Adding Go coding conventions specific to Prysm (maybe like a Prysm style guide) would be nice to our docs. See: https://github.com/prysmaticlabs/prysm/issues/2311. We could have specific guidelines as to how we write tests, how we define new services in Prysm, how to define a new API endpoint, etc.

**Comment by har00ga** [comment]
> Add a developer tools section where we can explain how to use prometheus, setup grafana, use jaeger for tracing of our beacon chain, and more

@rauljordan Is there relevant links / issues I should be looking to parse for this information?

**Comment by rauljordan** [comment]
Closing this and moving some leftover items to the https://github.com/prysmaticlabs/documentation repository for better tracking
