### ISSUE TITLE
Rework Slasher Architecture for Maintainability and Speed

### ISSUE THREAD

**Issue by rauljordan** [prysmaticlabs/prysm#4836]
Hi all,

This is a tracking issue that revisits the current [slasher project](https://github.com/prysmaticlabs/prysm/tree/master/slasher) in Prysm in order to increase its code health and performance through good tests, separation of concerns, and carefully thought out design decisions. Currently, slasher lacks enough tests, does not follow the code health patterns we use in the beacon node or validator client, and needs to be optimized for production. Here are some items in the cooker we are planning on bringing into the slasher project as a refactor:

## Architecture Fixes

Slasher has different moving pieces that all work concurrently, it makes sense to use a service pattern similar to what we do in the beacon node (operations, blockchain, powchain, sync)
- [x] Create a `node` package that initializes all services in the slasher in a single place #4856 
- [x] Create a `beaconclient` package that receives blocks/attestations #4835
- [x] Submit found attester/proposer slashings to the beacon node via gRPC #4866 
- [x] Eliminate the `rpc` package in slasher, as slasher does not need to have an RPC server - it being a client of the beacon node is enough
- [x] Make a package detection/ with two subpackages, proposals/ attestations/ that can figure out double votes, double proposals, and surround votes #4841 
- [x] We need to add comprehensive tests and benchmarks to the most expensive operations in the slasher
- [x] Add prometheus metrics + proper spans to the slasher codebase
- [x] Include proposer/attester slashings from operations pool in blocks #2766

## Slashing Detection Optimizations

- [x] Detecting double vote and detecting surround votes can be done in parallel

**Comment by shayzluf** [comment]
@rauljordan about `We can have an easier way of tracking in the DB if a validator index has committed double votes by having a schema such as: validatorIdx + epoch => []attDataRoot, check if > 1, then true`
we can replace  attestations keys in #4832 with attDataRoot and add attDataRoot to indexed attestation key for quick lookup in case slashing offence was committed

**Comment by prestonvanloon** [comment]
Please add #2766 to this task.

**Comment by shayzluf** [comment]
@rauljordan @0xKiwi 
> Detecting double vote and detecting surround votes can be done in parallel
could be completely removed as we seem to be able to detect both using span maps

**Comment by rauljordan** [comment]
Complete
