### ISSUE TITLE
Mega tracking - state management service

### ISSUE THREAD

**Issue by terencechain** [prysmaticlabs/prysm#4958]
Opening this up to track state management service related todos

### Local setup checks
- [x] eth1 mock RPC with 64 validators with finality over 100 epochs
- [x] eth1 mock RPC with 16384 validators with finality over 100 epochs
- [x] Verify one can query historical state with eth1 mock RPC setup. From genesis epoch to latest epoch 
- [x] Check profiling for the above

### Cluster checks
- [x] Verify a node can sync using a fresh DB
- [x] Verify a node can sync to head using an existing DB
- [x] Verify 2000 validators can perform with a node running new state mgmt service
- [x] Check profiling for the above

### Misc improvements and pending bugs
- [x] Add a fall back path for unknown state summary incase people switch on/off new state service
- [x] Better handling when epoch boundary root is skipped
- [x] Solve initial sync error: `panic: could not process block: could not get pre state for slot 351241: unknown boundary state`
- [x] Solve initial sync error: `could not save state: could not verify epoch boundary root has state: could not compute epoch boundary state: could not replay blocks: could not process block: could not process block header: parent root does not match the latest block header signing root in state` 

### Production readiness
- [x] Benchmark numbers for worst case state gen for both cold and hot sections
- [ ] Deprecate current archival usages 

Design doc:
https://hackmd.io/-XUMOlKkToS6PRiGC9Vljw

**Comment by terencechain** [comment]
Fun fact. With the new state mgmt service and comparing to latest beacon node. The new state mgmt service uses 70% less on TotalAlloc  reported by memstats. TotalAlloc tracks the cumulative bytes allocated for heap objects. I think this is heading towards the right direction

```
New state management service:
go_memstats_alloc_bytes 6.7818112e+08
go_memstats_alloc_bytes_total 9.840466792e+09

Currently:
go_memstats_alloc_bytes 7.37364544e+08
go_memstats_alloc_bytes_total 1.5895535144e+10
```

**Comment by prestonvanloon** [comment]
Is this running in production?

**Comment by terencechain** [comment]
No, it'll be running by default with the relaunch v0.11.1 so I'm waiting to see how that goes

**Comment by terencechain** [comment]
Closing this and defer this to  #5350
