### ISSUE TITLE
Remove lookback and properly handle min span updates in Slasher

### ISSUE THREAD

**Issue by 0xKiwi** [prysmaticlabs/prysm#5040]
This is an issue for handling min span updates in the slasher, since currently they require going to epoch 0 on a first run, we need a better way to handle them as using the lookback sacrifices security.

following the initial design doc: https://hackmd.prylabs.network/s/H1jO_H9wL

Starting to resolve this issue:

- [x] batch read attestation validators spans from db #5534
- [x] batch write attestation validators spans from db #5534
- [x] use batch read and write to update min span

**Comment by prestonvanloon** [comment]
@0xKiwi Please add more context. I am not sure how to triage this issue or what action needs to be taken.

**Comment by 0xKiwi** [comment]
The strategy we use for catching double and surround votes is referred to as [min-max spans](https://github.com/protolambda/eth2-surround#min-max-surround). This strategy involves maintaining every validators information on a per-epoch basis for the full validator set.

Say we receive an aggregated attestation of 16 validators, spanning from source epoch 2 to target epoch 8. We update the min max spans representing epoch 0 to epoch 8 for each of those 16 validators. Currently, we chunk up the min max spans for the full validator set into per-epoch buckets, so if we want to change epoch 3, we need to load that epoch into the cache to perform an update on it.

Every attestation we receive needs to have its min spans updated which means updating the spans from the source epoch, all the way to 0. This is troublesome to handle for validators that haven't attested until epoch 10,000, because it means we need to update the min spans from epoch 0, all the way to epoch 10,000. Processing such an attestation would normally load all of the existing validator history into memory for 10,000 epochs.

This wouldn't be a huge problem to do once, but we would need to do it for every new validator index received in the network. 


Our current workaround is to only "lookback" 128 epochs. Say we get an attestation for epoch 1000, we only update the spans to epoch 872, instead of epoch 0. This allows us to keep the full 128 epochs of lookback in a cache to prevent unneeded database checks and edited.

**Comment by shayzluf** [comment]
started a design doc to resolve this issue
https://hackmd.prylabs.network/s/H1jO_H9wL

**Comment by rauljordan** [comment]
Keep us posted on your progress on this @shayzluf, maybe we can have a quick design review session over voice chat - let's talk on discord about this

**Comment by shayzluf** [comment]
starting to resolve this issue:
 [ ] add validators activation epoch to cache 
 [ ] use validator activation for detection & update
 [ ] batch load validators spans from db
 [ ] batch write validators spans to db

**Comment by alonmuroch** [comment]
@shayzluf I couldn't open the hackmd doc, any chance you have a newer link?

**Comment by alonmuroch** [comment]
@0xKiwi where did we take the lookback value (128)? 
I see a var called WeakSubjectivityPeriod.. is that it? does it appear in the spec?
