### ISSUE TITLE
Add proposer slashing detection

### ISSUE THREAD

**Issue by shayzluf** [prysmaticlabs/prysm#5116]
In order to complete the slasher functionality we need to add proposer slashing functionality to the slasher. in order to complete this functionality we need to complete these tasks:
- [x] write and test proposer slashing detector #5120
- [x] add proposer index to blockheader #5127
- [x] receive signed blocks from stream and detect slashing #5139
- [x] change proposer slashing to detect by slot and not by epoch [spec changes](https://github.com/ethereum/eth2.0-specs/blob/dev/specs/phase0/beacon-chain.md#proposer-slashings)
