### ISSUE TITLE
reintroduce slasher RPC server

### ISSUE THREAD

**Issue by shayzluf** [prysmaticlabs/prysm#5189]
in order to support validator redundancy slasher need to support external calls:
- [x] slasher grpc server #5190
- [x] implement IsSLashableAttestation endpoint #5209
- [ ] implement IsSLashableBlock endpoint #5765
- [x] retrieve and cache validators public keys #5220
- [x] get fork version and genesis validators root ethereumapi endpoint 
- [x] implement ethereumapi endpoint in beacon node
- [x] validate signature of rpc requests
