### ISSUE TITLE
V0.11 Testnet: use 32 ETH deposits

### ISSUE THREAD

**Issue by prestonvanloon** [prysmaticlabs/prysm#5362]
In the upcoming testnet release, we aim to remove any "demo" configuration and target a pure mainnet specification within Prysm.

Required changes:

**Beacon node / Validator**
- [x] Make mainnet configuration the default in //shared/params #5367

**Documentation** 
- [x] Update references to "deposit 3.2 ETH"  in Prysm markdown.
- [x] Update prylabs.net with language regarding full mainnet configuration
- [x] Update docs.prylabs.network https://github.com/prysmaticlabs/documentation/issues/24

**Prysm testnet infra**
- [x] Adjust key manager deposit values
- [x] Update defaults in deposit tooling #5367
- [x] Update faucet to give 32 Testnet ETH

**Comment by prestonvanloon** [comment]
The only remaining items are docs and some infra configuration.
