### ISSUE TITLE
Align to spec v0.12

### ISSUE THREAD

**Issue by terencechain** [prysmaticlabs/prysm#5935]
This PR tracks to the progress to align Prysm to v.0.12 which is target for multi client testnet and hopefully the very last release for mainnet. The working branch for this is on: https://github.com/prysmaticlabs/prysm/tree/v0.12

## Beacon chain ⛓️ 
- [x] Adjust INACTIVITY_PENALTY_QUOTIENT to accurately reflect intention (https://github.com/ethereum/eth2.0-specs/pull/1712)
- [x] Rename SigningRoot to SigningData https://github.com/ethereum/eth2.0-specs/pull/1740)
- [x] Remove PERSISTENT_ COMMITTEE_PERIOD in favor of SHARD_COMMITTEE_PERIOD (https://github.com/ethereum/eth2.0-specs/pull/1783)
- [x] Disallow empty aggregation bits in attestations (https://github.com/ethereum/eth2.0-specs/pull/1780)
- [x] Change MAX_ATTESTER_SLASHINGS from 1 to 2 (https://github.com/ethereum/eth2.0-specs/pull/1794)
- [x] Ensure balances remain unchanged for optimal validators during inactivity leak (https://github.com/ethereum/eth2.0-specs/pull/1830)
Non-substantive:
- [x] Fix some ValidatorIndex type casting (https://github.com/ethereum/eth2.0-specs/pull/1714)
- [x] Minor typing fixes (https://github.com/ethereum/eth2.0-specs/pull/1731)
- [x] Clarify eth1 timestamp can be less than genesis time (https://github.com/ethereum/eth2.0-specs/pull/1756)
- [x] Clarify that eth1 blocks must be deep enough in chain for consideration for genesis (https://github.com/ethereum/eth2.0-specs/pull/1834) #5941 
- [x] Structure rewards/penalties to allow for more granular testing (https://github.com/ethereum/eth2.0-specs/pull/1747, https://github.com/ethereum/eth2.0-specs/pull/1826)

##  Fork choice 🍴 
- [x] Add FFG-LMD vote consistency checks (https://github.com/ethereum/eth2.0-specs/pull/1742)
- [x] [Non-substantive] Remove redundant check in validate_on_attestation (https://github.com/ethereum/eth2.0-specs/pull/1755)

##  Validator 🧑‍🤝‍🧑 
- [x] Ensure eth1data voting can't move to past eth1data states (https://github.com/ethereum/eth2.0-specs/pull/1836) #5944 
- [x] [Non-substantive] Minor cleanups and validator sanity tests (https://github.com/ethereum/eth2.0-specs/pull/1745)

##  Networking 🖥️ 
- [x] Require "seen" aggregates to be valid to bound cache (https://github.com/ethereum/eth2.0-specs/pull/1749)
- [x] Clarify beacon committee assignments are not added to attnets ENR entry (https://github.com/ethereum/eth2.0-specs/pull/1775)
- [x] Remove interop from p2p spec (https://github.com/ethereum/eth2.0-specs/pull/1767)
- [x] Bump gossipsub to v1.1 and note extended validator enums for gossip conditions (https://github.com/ethereum/eth2.0-specs/pull/1796, https://github.com/ethereum/eth2.0-specs/pull/1828)
- [x] Clarify blocks in BlocksByRange must be from a single chain (https://github.com/ethereum/eth2.0-specs/pull/1795) #5955
- [x] Req/Resp sizes constrained by SSZ bounds (https://github.com/ethereum/eth2.0-specs/pull/1800)
- [x] Loosen restrictions for aggregate propagation to not require aggregator in bitfield (https://github.com/ethereum/eth2.0-specs/pull/1801)
- [x] Use all attestation subnets in Phase 0 (https://github.com/ethereum/eth2.0-specs/pull/1804)
- [x] Restrict and clarify BlocksByRange request (https://github.com/ethereum/eth2.0-specs/pull/1835) #5955 

##  BLS 🔑 
- [x] Update BLS to use IETF bls draft 2 with hash-to-curve draft 7 (https://github.com/ethereum/eth2.0-specs/pull/1799)

**Comment by 0xKiwi** [comment]
I will work on INACTIVITY_PENALTY_QUOTIENT changes, renaming PERSISTENT_COMMITTEE_PERIOD, modifying MAX_ATTESTER_SLASHINGS and disallowing empty bits in attestations.

**Comment by terencechain** [comment]
@rauljordan is taking on 1780

**Comment by terencechain** [comment]
Taking 1712

**Comment by terencechain** [comment]
Taking 1740

**Comment by terencechain** [comment]
Taking 1830

**Comment by terencechain** [comment]
Taking 1742

**Comment by terencechain** [comment]
Last one before I take a break.  Taking 1755

**Comment by rauljordan** [comment]
We never had an interop network config, so this is done `Remove interop from p2p spec (ethereum/eth2.0-specs#1767)`

**Comment by rauljordan** [comment]
@nisdas for 1800, a bit confused about whether or not we implement what it specifies. It seems like we do all the pieces, I'm just unsure about this part https://github.com/ethereum/eth2.0-specs/pull/1800/files#diff-2e616bac0161143d97e596d333a60561R423. Lmk if you can take a look
