### ISSUE TITLE
Feature Flag Tracking: enableInitSyncWeightedRoundRobin

### ISSUE THREAD

**Issue by farazdagi** [prysmaticlabs/prysm#6024]
# 🦄 Feature Tracking

**Current status** (opt-in or opt-out): 
Opt-out

**Opt-in feature flag name**:
`enableInitSyncWeightedRoundRobin`

**Opt-out feature flag name**: 
`disableInitSyncWeightedRoundRobin`

### Feature Description

- Enables weighted round robin fetching optimization (when fetching is done from a single peer having maximum capacity of the rate limit)

### Tasks

- [x] Feature flag created as opt-in
- [x] Feature implemented / code complete #5887 
- [x] Feature tested in production for adequate amount of time
- [x] Feature flag is inverted to be opt-out and the opt-in flag is deprecated #6187
- [x] Feature has made it to a tagged production release as an opt-out flag `tag: v1.0.0-alpha.10`
- [x] Opt-out feature flag is deprecated and old code paths are cleaned up #6400

This issue should be closed after all of the above tasks are complete.

**Comment by farazdagi** [comment]
From discord:
>Raul: Perhaps we can make those warn level and say something about "Perhaps you received data from a bad peer"

With our updated algo (where batch is read from a single peer) it makes sense to throw away whole batch of data on the first invalid block (as all the data in batch is from the very same peer). So, whenever this flag will be released - create corresponding issue to handle this.

**Comment by rauljordan** [comment]
Update on this @farazdagi ?
