### ISSUE TITLE
Topaz Testnet v0.12.1 Restart

### ISSUE THREAD

**Issue by rauljordan** [prysmaticlabs/prysm#6076]
# 💎 Issue

### Background

We have been successfully running a v0.12 testnet for a while now, with 65536 validators. We are pretty much ready to restart Topaz, which will get us one step closer to mainnet by having the _closest_ possible spec to the real thing. We are aiming to complete this milestone by end of week, and here are the required items to check in to consider this milestone complete:

- [x] Disable kademlia DHT from Prysm
- [x] Enable new state management by default
- [x] Unskip e2e for v0.12, it is failing due to https://github.com/prysmaticlabs/prysm/pull/6020 as the first handshake fails because RPC handlers haven't been registered yet. Requires investigation.
- [x] Recommend users to run their own ETH1 nodes, prepare docs portal for this #6126 https://github.com/prysmaticlabs/documentation/issues/23
- [x] Enable HTTP gateway by default on a common port
- [x] Remove websocket requirements for eth1 nodes in Prysm
- [x] Include stream duties functionality for the validator client
- [x] Have proper documentation to use the go tool with prysm for building, testing, and doing `go get`, especially updating contribution guidelines to encourage go tool usage to make it easier to get involved
- [x] Proper security fallback for handshakes
- [x] Bug: ERROR sync: Failed to handle p2p pubsub error=attestation is not aggregated
- [x] Save all items to DB as ssz marshaled bytes for efficiency (it seems faster than proto.Marshal, but need proof through a benchmark)
- [x] Merge ethereumapis v0.12 into master and update dependency for it in prysm
- [x] Use fastssz everywhere in Prysm for marshal/unmarshal instead of go-ssz
- [x] Target v0.12.1: https://github.com/ethereum/eth2.0-specs/releases/tag/v0.12.1

We need to ensure all milestone items are completed in https://github.com/prysmaticlabs/prysm/milestone/10

**Comment by prestonvanloon** [comment]
Let's make sure we have resolved everything in this milestone as well: https://github.com/prysmaticlabs/prysm/milestone/10, maybe add that as an action item.

**Comment by terencechain** [comment]
Taking on `Save all items to DB as ssz marshaled bytes for efficiency`

**Comment by terencechain** [comment]
Any objection to target v0.12.1? It's just 2 minor PRs away:
https://github.com/ethereum/eth2.0-specs/releases/tag/v0.12.1

Since Topaz is a long standing PR. It'll be good to incorporate the only v0.12.1 change  which is to modify genesis time to be more tunable:
https://github.com/ethereum/eth2.0-specs/pull/1866

**Comment by nisdas** [comment]
0.12.1 is fine to work on, its just a few PRs away. That will be the target for other clients too, to work on.

**Comment by prestonvanloon** [comment]
>  Merge ethereumapis v0.12 into master and update dependency for it in prysm
Is this done?

**Comment by rauljordan** [comment]
@prestonvanloon we'll leave that for last, until we have fully reviewed v0.12 and are about to merge it

**Comment by rauljordan** [comment]
DONEEE
