### ISSUE TITLE
Reuf 

### ISSUE THREAD

**Issue by R1971** [prysmaticlabs/prysm#6162]
# 🦄 Feature Tracking

**Current status** (opt-in or opt-out): 

**Opt-in feature flag name**:

**Opt-out feature flag name**: 

### Feature Description

 A clear and concise description of the new feature. Provide links to your technical
design document or other supporting information.

### Tasks

- [ ] Feature flag created as opt-in
- [ ] Feature implemented / code complete
- [ ] Feature tested in production for adequate amount of time
- [ ] Feature flag is inverted to be opt-out and the opt-in flag is deprecated
- [ ] Feature has made it to a tagged production release as an opt-out flag
- [ ] Opt-out feature flag is deprecated and old code paths are cleaned up

This issue should be closed after all of the above tasks are complete.
