### ISSUE TITLE
Feature Flag Tracking: attestationAggregationStrategy

### ISSUE THREAD

**Issue by farazdagi** [prysmaticlabs/prysm#6236]
# 🦄 Feature Tracking

**Current status** (opt-in or opt-out): 
- opt-out

**Opt-in feature flag name**:
`--attestation-aggregation-strategy=max_cover`

**Opt-out feature flag name**: 
`--attestation-aggregation-strategy=naive`

### Feature Description
- `--attestation-aggregation-strategy=strategy` allows to switch between different attestation aggregation heuristics (naive, max_cover, max_ind_set etc).

### Tasks

- [x] Feature flag created as opt-in #6343
- [x] Feature implemented / code complete
- [x] Feature tested in production for adequate amount of time
- [x] Feature flag is inverted to be opt-out and the opt-in flag is deprecated #6960
- [x] Feature has made it to a tagged production release as an opt-out flag
- [ ] **CRUCIAL** Before wrapping up the feature, benchmarks should be provided.
- [x] Opt-out feature flag is deprecated and old code paths are cleaned up

This issue should be closed after all of the above tasks are complete.

**Comment by rauljordan** [comment]
Hi @farazdagi, just wondering if you have an update on this one

**Comment by farazdagi** [comment]
Raul, will come try to come up with a closing PRs (bench + flag deprecation) till the end of this week.

**Comment by prestonvanloon** [comment]
@farazdagi can we release this feature fully?

**Comment by farazdagi** [comment]
Since attestation aggregation is a enum-type flag (we are able to feed in values "naive" and "max_cover"), and deprecated flags have been removed for beta -- nothing more to do on this item ("max_cover" is enabled by default for quite some time now, and ability to switch to "naive" is still needed for base comparison).
