### ISSUE TITLE
Audit documentation feedbacks

### ISSUE THREAD

**Issue by terencechain** [prysmaticlabs/prysm#6336]
Opening this issue to track documentations feedbacks from the Quantstamp audit

- [x] 0.Code is lacking inline developer documentation. For instance, beacon-chain/p2p/subnets.go, beacon-chain/p2p/utils.go do not contain any documentation, while for other files (such as, beacon-chain/p2p/service.go) contain comments, however, do not describe the individual parameters and return values
- [x] 1. In validator/node/node.go, on L276 and L282, the error message "Could not create DB in dir %s" should say "clear" instead of "create".
- [x] 2. In validator/flags/interop.go, the description for InteropNumValidators appears to incorrectly reference itself: "The number of
- [x] validators to deterministically generate when used in combination with --interop-num-validators.". Likely a copy and paste error between L11 and 17.
- [x] 3. In beacon-chain/state/stateutil/state_root.go#196, copy and paste error -- "could not compute previous epoch attestations merkleization" should be "... current epoch ...".
- [x] 4. In beacon-chain/state/types.go#112, the comment in MinusRef() should say "underflow", not "overflow".
- [x] 5. In beacon-chain/state/state_trie.go, in the function merkleize(), it is claimed that it pads the leaves to a power-of-two length. It does
- [x] this only up to the length of 32. We recommend adjusting the comment.
- [x] 6. In beacon-chain/state/setters.go, the comment This PR updates the randao mixes is used in many places, but is likely only relevant to
- [x] UpdateRandaoMixesAtIndex().
- [x] 7. In beacon-chain/state/setters.go, unclear why "This PR..." is referenced in many of the comments.
- [x] 8. In beacon-chain/state/setters.go, L135-136 - one or more words are missing in the comments.
- [x] 9. In beacon-chain/core/epoch/precompute/justification_finalization.go, the specification pseudocode from
- [x] process_justification_and_finalization could be included for ProcessJustificationAndFinalizationPreCompute().
- [x] 10. In beacon-chain/core/block_operations.go, the comment on L587-588 This function returns a list of pending attestations which can then be appended to the BeaconState's latest attestations. is not accurate. The attestations are appended to the BeaconState's list internal to the function, and the BeaconState itself is returned.
- [x] 11. Cache in beacon-chain/cache/hot_state_cache.go is the only cache that doesn't use a mutex. We recommend documenting this design rationale.
- [x] 12. Typos in beacon-chain/p2p/service.go, L383-384, “id’s” -> “ids”
- [x] 13. Typo in beacon-chain/blockchain/process_attestation.go#125, "state to to validate".
- [x] 14. Typo in beacon-chain/blockchain/receive_block.go#63, "preformed" -> "performed".
- [x] 15. Typo in beacon-chain/core/helpers/slot_epoch.go#57, "form" should be "from".
- [x] 16. In beacon-chain/blockchain/metrics.go, should the Help strings on L80 and L84 be reversed?
- [x] 11. InProcessDeposits() do not match the specification.
- [x]  17. In beacon-chain/blockchain/chain_info.go#146, "head state" should be "head block".
- [x] 18. In beacon-chain/blockchain/head.go#30, not a correct English sentence.
- [x] 19. In beacon-chain/blockchain/head.go#115, typo "inital-sync-cache-state" should be "initial-sync-cache-state".
- [x] 20. Typo in beacon-chain/core/state/transition.go#244: "skip skips" -> "skip slots".
- [x] 21. In shared/bytesutil/bytes.go, L24-43, the functions implement little-endian format but specifications mention big.
- [x] 22. In shared/sliceutil/slice.go, the function NotUint64(), returns elements of b which are not in a, not the other way around.
- [x] 23. In shared/sliceutil/slice.go, the function UnionByteSlices(), doesn't return common elements, but all of them.
- [x] 24. In beacon-chain/core/epoch/epoch_processing.go, in the spec pseudocode for process_final_updates, after L208 the pseudocode for the if-block is missing: validator.effective_balance = min(balance - balance % EFFECTIVE_BALANCE_INCREMENT, MAX_EFFECTIVE_BALANCE).
- [x] 25. In beacon-chain/p2p/encoder/ssz.go, in function DecodeWithMaxLength(), msgLen stands for the remaining bytes in r, but this is NOT the decoded message. Thus the check on L163 and the comment on L164 do not match. The decoded message seems to be on L167 numOfBytes, err := r.Read(b).
- [x] 26. Typo in beacon-chain/core/helpers/slot_epoch.go, “alswo” -> “also”.
- [x] 27. Typo in beacon-chain/core/helpers/slot_epoch.go, “compute_start_slot_of_epoch” -> “compute_start_slot_at_epoch”.
- [x] 28. There are issues in end-user documentation:
- [x] 1. All 3 links are broken in step 1 on this page https://docs.prylabs.network/docs/install/lin/activating-a-validator/
- [x] 2. The link indicated in the following screenshots are broken on this page https://docs.prylabs.network/docs/install/lin/bazel/
- [x] 30. In beacon-chain/db/iface/interface.go, URLs mentioned in file are broken.
- [x] 31. In beacon-chain/db/kv/blocks.go, L585-587, comment is misleading, as no list is being returned. Rather, the return will be a map with a single key-value pair: "block-parent-root-indices” -> parentRoot (array of bytes). Change the comment accordingly.
- [x] 32. In beacon-chain/db/kv/blocks.go, in function fetchBlockRootsBySlotRange() header comment says it performs a binary search. However, if step is one, the implemented logic won’t skip half of the slots in the range. Fix the comment accordingly.
- [x] 33. Typo in beacon-chain/syncservice.go, “Intialize” -> “Initialize”.
