### ISSUE TITLE
Audit best practice feedback

### ISSUE THREAD

**Issue by terencechain** [prysmaticlabs/prysm#6337]
Opening this issue to track best practices feedbacks from the Quantstamp audit

- [x] 1. ~~In shared/bls/bls.go, duplicated code between VerifyAggregate, AggregateVerify and FastAggregateVerify~~ Won't fix, out of date feedback
- [x] 2. In beacon-chain/state/getters.go, duplicated code between: #6476
- [x] 3. In beacon-chain/state/setters.go, duplicated code between: #6476
- [x] 4. In beacon-chain/cache/depositcache/pending_deposits.go, duplicated code between pendingDeposits and In pendingContainers. #6476
- [x] 5. In beacon-chain/interop-cold-start/service.go, error messages on L182, 189, 192 should read “could not save”. #6355
- [x] 6. In beacon-chain/forkchoice/types.go, field names in type Node struct do not follow a consistent naming convention. 
- [x] 7. In beacon-chain/blockchain/metrics.go#122, ignores error logging. Should it log it?
- [x] 8. In beacon-chain/p2p/encoder/ssz.go, in function writeSnappyBuffer(), when there is an error, the function returns without closing bufWriter. We recommend closing it before returning.
- [x] 9. In beacon-chain/p2p/beacon-chain/p2p/sender.go#20, baseTopic is used without validation. If the upstream code has an issue or becomes out-of-sync (e.g., attempts to send a topic that is no longer supported), the baseTopic string could potentially be a topic that is actually not supported. #6558 
- [x] 10. In beacon-chain/p2p/peers/status.go#487, CurrentEpoch() could be renamed to HighestEpoch() to better reflect the semantics.
- [x] 11. In beacon-chain/p2p/peers/status.go#433, pidEpochs could be renamed to pidToEpoch for consistency with rootToEpoch defined on L432.
- [x] 12. There are multiple instances of in-line constants. We recommend moving these constants elsewhere: a separate constants file or the top of the current file, for better visibility and maintainability. Some instances including, but not limited to #6467 
- [x] 13. Error messages should be more precise
- [x] 14. In beacon-chain/p2p/watch_peers.go, there is a 30-second timeout. However, in beacon-chain/p2p/service.go#555, and beacon-chain/p2p/dial_relay_node.go#29, such a timeout is not present. We recommend to make the logic consistent. #6560 
- [x] 15. We recommend to resolving the TODOs for production readiness:
- [x] 16. In beacon-chain/p2p/discovery.go#33, the createListener() method does not follow the same pattern for error propagation as other methods do: it fails with Fatal errors while, for instance, the createLocalNode() method returns an error in case of an issue, which seems to be more common in the P2P codebase. We recommend improving consistency of error handling. #6525
- [x] 17. In gossip_topic_mappings.go, the following constant is defined in the GossipTopicMappings: "/eth2/%x/committee_index%d_beacon_attestation": &pb.Attestation{} . The same constant is being defined again in broadcaster.go, attestationSubnetTopicFormat. We advise against code clones. #6525
- [x] 18. The schema version of the libp2p protocol ID is currently hard-coded in the topic strings. To facilitate updating the version it would be beneficial to use a separate SchemaVersion state variable. #6558 
- [x] 19. In validator/client/runner.go#111 since id represents a public key, we recommend renaming it to pubKey. #6375
- [x] 20. In beacon-chain/core/helpers/validators.go#178, as long as the epoch doesn't change, there is no need to call CurrentEpoch(state)   since L151 already retrieves it in the e.
- [x] 21. In beacon-chain/state/stateutil/arrays.go#118, inner and outer loops use variables named i. Use different names for these variables.
- [x] 22. In shared/sliceutil/slice.go, function SplitOffset() should add a check to ensure that index * chunks < listSize.
- [x] 23. ~~In beacon-chain/blockchain/process_attestation_helpers.go#126, the error message should be aligned with the code with respect to the logical operator; it should use “and” instead of “or”.~~ Alignment is fixed, wording is correct (we try to match ether current or prev epoch, so reporting issue when we can't match one **or** another).
- [x] 24. In beacon-chain/state/stateutil/blocks.go, the constants such as 16 on L112, which corresponds to MAX_DEPOSITS in the ETH2 spec, should be refactored into named constants.
- [x] 25. In beacon-chain/state/state_trie.go, the constant 21 is used throughout which corresponds to the number of field indices. This should be a named constant.
- [x] 26. In beacon-chain/state/setters.go, the function SetStateRoots() does not appear to be used anywhere or tested.
- [x] 27. In beacon-chain/state/setters.go, when updating reference counts, MinusRef() is used in many places, however varname.refs-- is used in others. It is not clear what distinguishes these cases, and likely MinusRef() could be used throughout.
- [x] 28. In beacon-chain/state/getters.go, the function ValidatorAtIndex() could reuse Cloners.CopyValidator().
- [x] 29. In beacon-chain/core/feed/operation/events.go#17, the constant AggregatedAttReceived does not appear to be used anywhere in the codebase.
- [x] 30. In beacon-chain/core/block_operations.go#818, the statement: if len(indices) > 0, is unnecessary since the nested for-loop would not loop if len(indices) == 0.
- [x] 31. In beacon-chain/core/block_operations.go, the deprecated function verifyDepositDataSigningRoot(), which relies upon the function ssz.SigningRoot() (which is also deprecated), is still used in ProcessDeposit().
- [x] 32. In beacon-chain/main.go#115, the switch statement has breaks in case branches. Those are not needed in Go.
- [x] 33. In validator/main.go#152, the switch statement has breaks in case branches. Those are not needed in Go. #6375
- [x] 34. In beacon-chain/sync/subscriber.go#36, noopValidator() does not use the context parameter. It should be removed.
- [ ] 35. In beacon-chain/sync/subscriber.go#135, uses deprecated PubSub.Subscribe(). The code should be updated. #6554
- [x] 36. In beacon-chain/sync/initial-sync/block_fetcher.go#405, the function for selecting a failover peer is inefficient. It does not have to filter out the wrong peer at the beginning by searching for it. It can right away randomly select a new peer. If it happens to find the same peer (the forbidden one), it knows where it is and can drop it. #6442
- [x] 37. In beacon-chain/sync/initial-sync/block_fetcher.go#269, the name count is reused (previously used as a name of of the argument). We recommend using different names. #6357
- [x] 38. In beacon-chain/sync/initial-sync/blocks_queue.go#310, there is a switch statement with an empty default label. Some logging/comment would be handy. #6357 
- [x] 39. In beacon-chain/p2p/encoder/ssz.go, L160 and 163 should be swapped. The length error is known on L160, and the reader is not needed if the error happens.
- [x] 40. In beacon-chain/db/iface/interface.go (and implementations), DeleteBlock() and DeleteBlocks() are not used outside tests. They are declared in the interface, and supported by the database in blocks.go (as well as kafka), but not used otherwise. They should be moved to the test scope only.
- [x] 41. In beacon-chain/db/kv/operations.go, the functions HasVoluntaryExit() and VoluntaryExit() have a lot of duplicated code related to retrieving the exit. Reuse VoluntaryExit() in HasVoluntaryExit() and return whether it is not nil. #6476
- [x] 42. In beacon-chain/db/kv/operations.go, it seems that none of the methods here is called externally. Are they part of the future phase? At the very least, DeleteVoluntaryExit() is only called in tests. Consider moving it to the test scope.
- [x] 43. In beacon-chain/db/kv/slashings.go, the function ProposerSlashing() has a lot of duplicated code with HasProposerSlashing(). Reuse the result in HasProposerSlashing(). Same holds for AttesterSlashing() and HasAttesterSlashing(). #6476
- [x] 44. In beacon-chain/db/kv/slashings.go, Delete[Attester]Slashing() methods seem to have a testing scope only. Unless they are part of an upcoming phase, consider moving those to the testing scope.
- [x] 45. In beacon-chain/db/kv/state_summary.go and beacon-chain/db/kv/state.go, the functions State() and HasState() duplicate the code similarly to StateSumary() and HasStateSummary(). #6476
- [x] 46. The code in beacon-chain/db/http_backup_handler.go seems to be obsolete. It should be removed. **Comment:** Not sure why it was deemed obsolete - it is being used.
- [x] 47. In package validator/db, the code suffers from the same unused code issue as the beacon chain database (the Delete() methods). This is present in DeleteAttestationHistory() of attestation_history.go, DeleteProposalHistory() in proposal_history.go. #6557 
- [x] ~~48.In package validator/db, there is some code duplicated in NewKVStore() methods in both validator/db and beacon_chain/db packages. Consider removing the duplicates and consolidate the filesystem code.~~ Won't fix, somewhat odd to deduplicate.
- [x] 49. Inline constants are used instead of existing named constants. #6463
- [x] 50. Many DB-related functions that perform a computation on a given entity also have a corresponding function to perform the same computation on a corresponding batch of elements of the same entity kind. Examples: SaveBlock()/SaveBlocks(), DeleteBlock()/DeleteBlocks(), SaveStateSummary()/SaveStateSummaries(), etc. Such pairs of singular/plural functions share a lot of common code that could be simplified. Since the plural form is the most generic computation, it suffices to rewrite the singular function as a call to the plural one giving it a batch of size one. #6462
- [x] 51. In beacon-chain/db/filters/filter.go, L21-44: use iota instead of enumerating sequential values. #6358
- [x] 52. In beacon-chain/db/filters/filter.go, declaring FilterType as an alias to int seems excessive; rather, uint8 would have sufficed. #6358
- [x] 53. In beacon-chain/db/kafka/export_wrapper.go#36, prior to returning, issue a log info just to inform that the db was not wrapped. #6358
- [x] 54. In beacon-chain/db/kv/archived_point.go#38, Update is being called, but no side effect occurs. Replace it with View. #6358
- [x] ~~55. In beacon-chain/db/kv/archived_point.go#40, rename b to a more descriptive name.~~ No need, code block is focused enough, and bytes returned (which we call `b`) are converted to little-endian index.
- [x] 56. In beacon-chain/db/kv/attestations.go, function createAttestationIndicesFromData() does not start & end a span. Following other functions, start & end a span. #6358 
- [x] 57. In beacon-chain/db/kv/backup.go#32, the permissions of the backup directory path (0777) are less strict than the database folder (0700). Make it the same - 0700. #6522
- [x] 58. In beacon-chain/db/kv/backup.go#38, the permissions of the backup db file (0666) are less strict than the target database (0600). Make it the same - 0600. #6522
- [x] 59. In beacon-chain/db/kv/backup.go#38: give Open a timeout option. #6555
- [x] 60. In beacon-chain/db/kv/backup.go, receiver name (kv) does not match receiver name in other files (k). Change all receiver names under db/* to the same name. #6356
- [x] 61. In beacon-chain/db/kv/backup.go, Backup does not start & end an span. Following other functions in kv/*, start & end a span.
- [x] 62. In beacon-chain/db/kv/blocks.go, L527, L531, Rename k to key for better expressiveness. #6358 
- [x] ~~63. In beacon-chain/db/kv/blocks.go, L509, L512, the assignment of startSlot is redundant, as its value is already set by the if condition (success), or defaults to zero (failure) otherwise. Thus there is no need to update startSlot and the code can be simplified.~~ Intended: we have type assertion static analysis check, that requires us to check if assertion was ok.
- [x] 64. In beacon-chain/db/kv/blocks.go, functions fetchBlockRootsBySlotRange(), createBlockIndicesFromBlock(), and createBlockIndicesFromFilters() do not start & end a span. Following other operations, start & end a span. #6358
- [x] 65. In beacon-chain/db/kv/check_historical_state.go, the function HistoricalStatesDeleted() does not start & end aSpan. Following other operations, start & end a span. #6358
- [x] 66. In beacon-chain/db/kv/encoding.go, encode and decode functions do not start & end a span. Following other functions in kv/*, start & end a span.
- [x] 67. In beacon-chain/db/kv/kv.go, functions in kv.go do not start & end a span. Following other operations in kv/*, start & end a span.
- [x] 68. In beacon-chain/db/kv/regen_historical_states.go, functions lastSavedBlockArchivedIndex() and saveArchivedInfo() do not start a trace. Following other functions in kv/*, start & end a span. #6358
- [x] 69. In beacon-chain/db/kv/utils.go, no function in utils.go start & end a span. Following other functions in kv/*, start & end a span. #6358
- [x] 70. In validator/db/attestation_history.go, unmarshalAttestationHistory() does not start & end a trace. Following other operations, start & end a span. #6375
- [x] 71. In validator/db/db.go, rename receiver name for better reading. Suggestion: instead of db, which causes db.db to appear in some places, rename it to store. #6375
- [x] 72. In validator/db/setup_db.go, as this code is essentially testing infra, put it in a dedicated testing folder (the same way as performed for the setup_db.go file in the beacon-chain db).
- [x] 73. In Beacon-chain::Sync, across many files, Service receiver is named r. Suggestion: name r *Service as service *Service. #6348
- [x] 74. In beacon-chain/sync/service.go, rename receiver to make it more expressive. Suggestion: name r *Service as service *Service. #6348
- [x] 75. In beacon-chain/sync/pending_blocks_queue.go, lock/unlock in processPendingBlocksQueue() is not required, as the internal function execution never overlaps with itself. #6357
- [x] 76. In beacon-chain/sync/pending_attestations_queue.go, lock/unlock in processPendingAttsQueue() is not required, as the internal function execution never overlaps with itself. #6357
- [x] 77. In beacon-chain/blockchain/service.go#349, error message is incorrect, as it misses negation. Should be "could not save genesis block root". #6355

**Comment by terencechain** [comment]
Working down this list today. Let me know if you are working on anything in the list

**Comment by terencechain** [comment]
```
functions HasVoluntaryExit() and VoluntaryExit() have a lot of duplicated code related to retrieving the exit. Reuse VoluntaryExit() in HasVoluntaryExit() and return whether it is not nil.
```

I'm leaning towards not to do this. This means `HasVoluntaryExit` will be burdened with an unnecessary decode, while some of the beacon operation is small, it could be fairly large later

**Comment by prestonvanloon** [comment]
@terencechain 

This can still be refactored for deduplication without the decoding, but it is a bit of a stretch to do so.


```go
func (kv *Store) voluntaryExitBytes(ctx context.Context, exitRoot [32]byte) ([]byte, error) {
        ctx, span := trace.StartSpan(ctx, "BeaconDB.voluntaryExitBytes")
	defer span.End()
	var dst []byte
	err := kv.db.View(func(tx *bolt.Tx) error {
		bkt := tx.Bucket(voluntaryExitsBucket)
		dst := bkt.Get(exitRoot[:])
		return nil
	})
	return dst, err
}

// VoluntaryExit retrieval by signing root.
func (kv *Store) VoluntaryExit(ctx context.Context, exitRoot [32]byte) (*ethpb.VoluntaryExit, error) {
	ctx, span := trace.StartSpan(ctx, "BeaconDB.VoluntaryExit")
	defer span.End()
        enc, err := kv.voluntaryExitBytes(ctx, exitRoot)
        if err != nil {
           return nil, err
        }
	exit := &ethpb.VoluntaryExit{}
	return enc, decode(ctx, enc, exit)
}

// HasVoluntaryExit verifies if a voluntary exit is stored in the db by its signing root.
func (kv *Store) HasVoluntaryExit(ctx context.Context, exitRoot [32]byte) bool {
	ctx, span := trace.StartSpan(ctx, "BeaconDB.HasVoluntaryExit")
	defer span.End()
	enc, err := kv.voluntaryExitBytes(ctx, exitRoot)
	return len(enc) > 0, err
}
```
