### ISSUE TITLE
Create Developer Wiki for Prysm

### ISSUE THREAD

**Issue by rauljordan** [prysmaticlabs/prysm#6534]
# 💎 Issue

### Background

Thank you @rkapka for bringing up this topic. Currently, our docs portal https://docs.prylabs.network is designed to be a user-facing website that answers all questions regarding running Prysm, how to use its tools, monitoring, and more. As we grow as a team, it is imperative we have significant learning resources for external contributors to ensure knowledge of the codebase isn't kept in core developers' minds only. Instead of adding significant jargon and all of this information in the docs portal itself, it seems more useful to have a Github wiki for the Prysm project specific to explaining its development.

### Description

This is a tracking issue for the creation of such a wiki and outlining some of the items it should cover. Namely:

- [ ] How to develop new features for Prysm (explaining the feature flag lifecycle and how to create feature flags)
- [ ] Explain how the different core packages of Prysm work along with their design (linking relevant design docs where appropriate)
- [ ] Comprehensive coding style guidelines for Prysm
- [ ] How to write good tests for Prysm using tools such as gomock, how to test concurrency, how to perform fuzz tests
- [ ] Separate sections on the beacon node, validator client, and slasher services
- [ ] How to write a new RPC method for Prysm or amend existing ones: everything including the protobuf definitions, how to implement the protobuf using gRPC, best practices around separating server and client modifications into separate PRs
- [ ] Explaining how new code makes it into production using our canary testing pipeline
- [x] A section going into great detail on how initial sync works and its implementation [Init-sync docs](https://docs.google.com/document/d/1rqMUAajVTIePszy2Fjg3yluX6rryXk_fa1NllxcenXc/edit?usp=sharing)
- [ ] All about p2p networking for Prysm beacon nodes, with explainers on discv5

This is a large undertaking and unlikely something we can wrap up in a single quarter. However, we can all divide the work and take up a section incrementally. If there's anything missing, feel free to add more bullet points.

**Comment by rkapka** [comment]
Thank you for creating this issue. I believe a GitHub wiki for contributors is a great way to encourage more people to start participating. I remember that such a Wiki helped me greatly when I wanted to contribute to another project some time ago.

One thing I would definitely add to the list is the explanation why Prysm uses Bazel (I think Preston already mentioned this somewhere around here).

> All about p2p networking for Prysm beacon nodes, with explainers on discv5

I am not sure what you mean by "explainers", but I would avoid documenting something that is already available in 3rd party documentation. In my opinion it is enough to provide links for further reading which makes the external documentation a single source of truth.

> A section going into great detail on how initial sync works and its implementation

I would be careful with the "great detail" part. The more details you put into the Wiki, the better the chance that something will change in the code and the Wiki page will get outdated. I think this should be carefully balanced.

**Comment by rkapka** [comment]
Another thing worth describing might be the environment which is required/preferred when developing. At the beginning I wanted to develop on Windows using VS Code and it later turned out that I had to switch to Linux and GoLand. Maybe there are some cool debugging/monitoring tools that core developers use which are helpful?

**Comment by rkapka** [comment]
>  Comprehensive coding style guidelines for Prysm

Is this really necessary? Go already has a standard for formatting and the linter takes care of a lot of stuff. I don't see any issues with the current setup. Also, duplicating linter rules in the Wiki means that both the Wiki and static code analysis have to be synchronized by someone.

**Comment by prestonvanloon** [comment]
I'm OK with the idea of a wiki, but I wonder if there is overlap between the wiki and the docs portal.

What is the benefit for supporting / maintaining a wiki and docs portal simultaneously?

**Comment by ayushpateria** [comment]
Also, it would be great we can have all the design docs you guys wrote somewhere.

**Comment by rkapka** [comment]
Closing this as we have a developer wiki in our docs now.
