### ISSUE TITLE
[Tracking] Update tests using new testutils

### ISSUE THREAD

**Issue by terencechain** [prysmaticlabs/prysm#6590]
With the introduction of #6563 (Thanks @farazdagi), we can begin to update unit tests using the new testutil packages. I'm breaking down the items by package. This PR tracks the overall progress.
- [x] cache              
- [x] ~~flags~~ no tests there              
- [x] operations        
- [x] rpc #6641               
- [x] core/blocks #6939
- [x] core/epoch, core/feed, core/helpers, core/state, core/validator #6940               
- [x] forkchoice                   
- [x] p2p #6597                
- [x] state #6623              
- [x] blockchain #6605        
- [x] db #6938                
- [x] powchain #6652            
- [x] sync #6603
- [x] validator/accounts #6653
- [x] validator/client #6654
- [x] validator/db #6694
- [x] validator/keymanager #6683
- [x] validator misc (validator/node and validator/slashing-protection) #6694
- [x] slasher #6998
- [x] shared #6666
- [x] misc/left-overs #7003

Please call out a package before you work on it

**Comment by farazdagi** [comment]
I'll work on updating `p2p` package (I've already started with new tests there - for peer scorer).

**Comment by farazdagi** [comment]
I'll work on `sync` (including `init-sync`).

**Comment by rkapka** [comment]
I will update tests in `cache`.

I already started and one thing that is a bit annoying is comparing integers in certain scenarios. I changed

```
if cachedDeposits.MerkleTrieIndex != 2
```

into

```
assert.Equal(t, 2, cachedDeposits.MerkleTrieIndex, (...))
```

This is what happened:

```
Incorrect index of last deposit (2) vs expected 2, got: 2, want: 2
```

`cachedDeposits.MerkleTrieIndex` is of type `int64`, so I expect that there is a problem with incompatible types (`int` and `int64`). To make the test pass I had to rewrite the assertion as

```
assert.Equal(t, int64(2), cachedDeposits.MerkleTrieIndex, (...))
```

I don't know if there's an elegant way to handle such possible scenarios, but I figured I'll let you guys know.

**Comment by farazdagi** [comment]
Go's comparison operator `==` takes type into account as well, and asserts being explicit about type of compared value is good, imo. Plus, I believe that we should keep assertion package as simple as possible -- w/o any complex checks, type assertions etc.

**Comment by farazdagi** [comment]
@rkapka btw, instead of
```golang
assert.Equal(t, 2, cachedDeposits.MerkleTrieIndex, (...))
```
you can use
```golang
assert.Equal(t, 2, cachedDeposits.MerkleTrieIndex)
```
(the last param can be omitted)

**Comment by terencechain** [comment]
Working on `core`

**Comment by farazdagi** [comment]
Working on `blockchain`

**Comment by farazdagi** [comment]
Working on `state`

**Comment by terencechain** [comment]
> Working on `core`

Core may be hard to do. Since testutil uses `helpers`, we'll be getting import cycle there. Might just leave it as it is...

**Comment by terencechain** [comment]
Working on `operations`

**Comment by farazdagi** [comment]
> Core may be hard to do. Since testutil uses helpers, we'll be getting import cycle there. Might just leave it as it is...

Nice catch, #6610 should resolve the import cycle, so that assert/require can be used everywhere.

**Comment by terencechain** [comment]
> > Core may be hard to do. Since testutil uses helpers, we'll be getting import cycle there. Might just leave it as it is...
> 
> Nice catch, #6610 should resolve the import cycle, so that assert/require can be used everywhere.

Great. Thank you

**Comment by farazdagi** [comment]
Working on `rpc`.

**Comment by terencechain** [comment]
Working on `shared`.

**Comment by farazdagi** [comment]
Working on `validator`.

**Comment by farazdagi** [comment]
Working on `validator/client`.

**Comment by farazdagi** [comment]
Working on `validator/keymanager`.

**Comment by rkapka** [comment]
Working on `forkchoice`.

**Comment by farazdagi** [comment]
Wrapping up validator related tests: `validator/db`,  `validator/accounts`, `validator misc`

**Comment by farazdagi** [comment]
Working on `beacon-chain/db`.

**Comment by farazdagi** [comment]
Working on `core/*` items.

**Comment by farazdagi** [comment]
Working on `shared`.

**Comment by terencechain** [comment]
> Working on `shared`.


https://github.com/prysmaticlabs/prysm/pull/6666

**Comment by farazdagi** [comment]
Sorry! Working on `slasher` then :)

**Comment by farazdagi** [comment]
@terencechain I've updated description of #6666 ("Part of" -> "Closes", as your PR will be last one before we can close this issue.

**Comment by terencechain** [comment]
> @terencechain I've updated description of #6666 ("Part of" -> "Closes", as your PR will be last one before we can close this issue.

Sounds good. Also fyi, there's a few left that's not in shared. 

![Screen Shot 2020-08-14 at 4 33 53 PM](https://user-images.githubusercontent.com/21316537/90299716-0ae6cc80-de4c-11ea-9fd2-00fead576f5f.png)

**Comment by farazdagi** [comment]
Got it, will check the ones that are not part of `slasher` (#6998) or `shared` (#6666).
