### ISSUE TITLE
[Tracking] Peer scoring service

### ISSUE THREAD

**Issue by farazdagi** [prysmaticlabs/prysm#6622]
# 💎 Issue

### Background

Issue to track progress on peer scoring and rate limiting service implementation.

### Description
- [ ] Refactor "bad responses counter" into peer scoring system #6579
- [ ] `init-sync` slow peer (peers returning low number of blocks, constantly) descoring and throttling
- [ ] `init-sync` weak peer (peers returning blocks that are not processable, low average slots advanced) handling
- [ ] Inject peer scorer into Gossipsub v1.1 #6043

**Comment by farazdagi** [comment]
Removing from the milestone - we need some more efforts before scoring is considered solid.
