### ISSUE TITLE
Align to v0.12.2

### ISSUE THREAD

**Issue by terencechain** [prysmaticlabs/prysm#6716]
This PR tracks to the progress to align Prysm to v.0.12.2 which is the target version for Medella testnet
https://github.com/ethereum/eth2.0-specs/releases/tag/v0.12.2

## Beacon chain ⛓️ 

- [x] Add DEPOSIT_CHAIN_ID and DEPOSIT_NETWORK_ID to configuration (https://github.com/ethereum/eth2.0-specs/pull/1988)
- [x] [non-substantive] Compute committee count per slot is epoch based and rewrite gossip condition to be less stateful (https://github.com/ethereum/eth2.0-specs/pull/1904)
- [x] [non-substantive] Apply strict uint64 casting (https://github.com/ethereum/eth2.0-specs/pull/1746, https://github.com/ethereum/eth2.0-specs/pull/1935)
- [x] [non-substantive] Separate config files by phases (https://github.com/ethereum/eth2.0-specs/pull/1882)
- [x] [non-substantive] Reorder conditions to validator target_epoch before its use (https://github.com/ethereum/eth2.0-specs/pull/1996)

##  Fork choice 🍴 

- [x] [bug-fix] Fix edgecase in updating target checkpoint state (https://github.com/ethereum/eth2.0-specs/pull/1886)
- [x] [non-substantive] Use parent_root in ancestor check to add mutations after assertions (https://github.com/ethereum/eth2.0-specs/pull/1884)
- [x] [non-substantive] Avoid redundant call to get_ancestor (https://github.com/ethereum/eth2.0-specs/pull/1880)

##  Validator 🧑‍🤝‍🧑 

- [x] [non-substantive] Fix param in epoch_boundary_block_root calculation (https://github.com/ethereum/eth2.0-specs/pull/1962)

##  Networking 🖥️ 

- [x] Add queuing possibility to p2p messages in gossip (https://github.com/ethereum/eth2.0-specs/pull/1956)
- [x] Update gossipsub config params and add FAQ for explanation of choices (https://github.com/ethereum/eth2.0-specs/pull/1958)
- [x] Remove ssz encoding from req/resp (https://github.com/ethereum/eth2.0-specs/pull/1982) #6415
- [x] Add gossip conditions that block must have finalized checkpoint as ancestor (https://github.com/ethereum/eth2.0-specs/pull/1985) #6549 
- [x] [non-substantive] p2p formatting RP (https://github.com/ethereum/eth2.0-specs/pull/1953)

## Spec test
- [x] Update spec tests #6713

**Comment by terencechain** [comment]
Completed. We are complied fully v0.12.2 

Thanks @nisdas !

**Comment by terencechain** [comment]
Closed too early `Update gossipsub config params` is not yet done
