### ISSUE TITLE
[Tracking Issue] Implement Full-Featured, Easy Voluntary Exits

### ISSUE THREAD

**Issue by rauljordan** [prysmaticlabs/prysm#6882]
# 🚀 Feature Request

### Description

We are missing a way to perform voluntary exits easily with Prysm, and this is a requirement for mainnet. This feature needs to be well-tested and well-documented.

### Describe the solution you'd like

We need the ability to initiate a voluntary exit from the CLI, being able for users to understand the implications and have dedicated docs for this process.

### Progress tracking
- [x] Implement validator CLI command (#7046)
- [x] Additional confirmation before exiting (#7046)
- [x] Connect to a beacon node gRPC server to submit the exit (#7162)
- [x] Offer feedback to the user on the status of their exit and what they can do next (moved to #7208)
- [x] Update the documentation link for the second confirmation step
- [x] Prepare documentation
- [x] ~~Release the Kraken~~ Make the functionality available to users
