### ISSUE TITLE
Replacing deprecated packages and members

### ISSUE THREAD

**Issue by rkapka** [prysmaticlabs/prysm#6891]
This is a part of https://github.com/prysmaticlabs/prysm/issues/6747. Replacing deprecated members is not obvious, so let's discuss them one-by-one. The analysis can be found here: https://deepsource.io/gh/rkapka/prysm/issue/SCC-SA1019/occurrences

---

**What?**
- [x] package github.com/golang/protobuf/proto is deprecated: Use the "google.golang.org/protobuf/proto" package instead.

**Where?**
https://github.com/prysmaticlabs/prysm/blob/master/validator/testing/slasher_mock.go
https://github.com/prysmaticlabs/prysm/blob/master/beacon-chain/db/kafka/export_wrapper.go

**What is the problem?**
Switching packages as suggested results in compilation errors. Examples:

`slashingAtt, ok := proto.Clone(in).(*eth.IndexedAttestation)` // Cannot use 'in' (type *eth.IndexedAttestation) as type Message Type does not implement 'Message' as some methods are missing: ProtoReflect() Message

`if err := marshaler.Marshal(buf, msg); err != nil {` // Cannot use 'msg' (type "google.golang.org/protobuf/proto".Message) as type "github.com/golang/protobuf/proto".Message Type does not implement 'proto.Message' as some methods are missing: Reset() String() string ProtoMessage()

---

**What?**
- [x] ethpb.ChainStartResponse is deprecated: Do not use.

**Where?**
Several places.

**What is the problem?**
What should this struct be replaced with?
```
// Deprecated: Do not use.
type ChainStartResponse struct {
```
This was added by @prestonvanloon here: https://github.com/prysmaticlabs/ethereumapis/commit/6607cc86ddb7c78acfe3b1f0dfb115489a96d46d

---

**What?**
- [x] log.Finish is deprecated: Stop using go-log for event logging
- [x] log.Start is deprecated: Stop using go-log for event logging

**Where?**
https://github.com/prysmaticlabs/prysm/blob/master/tools/relaynode/relaynode.go

**What is the problem?**
Is it OK to replace `log = logging.Logger("prysm-relaynode")` with `log = logrus.WithField("prefix", "prysm-relaynode")`?
This also requires changing
```
ctx := context.Background()
log.Start(ctx, "main")
defer log.Finish(ctx)
```
to
```
ctx := context.Background()
ctx, span := trace.StartSpan(ctx, "main")
defer span.End()
```
---

**What?**
- [x] grpc.WithDialer is deprecated: use WithContextDialer instead. Will be supported throughout 1.x.

**Where?**
https://github.com/prysmaticlabs/prysm/blob/492944db0116195f8eac23ad86ab070672c1265d/beacon-chain/gateway/gateway.go#L177-L187

**What is the problem?**
`WithContextDialer` expects a `func(context.Context, string) (net.Conn, error)` as the argument, so `d` should be changed. It can no longer have the `timeout` argument and needs to take in a context instead. How to refactor this?

---

**What?**
- [x] interfaceT.Embedded is deprecated: Use EmbeddedType which is not restricted to defined (*Named) types.

**Where?**
https://github.com/prysmaticlabs/prysm/blob/492944db0116195f8eac23ad86ab070672c1265d/tools/analyzers/errcheck/analyzer.go#L402

**What is the problem?**
Changing the code to `embedded := interfaceT.EmbeddedType(i)` changes the type of `embedded` from `*types.Named` to `types.Type`. The variable is used as a return value, so this does not compile.

---

**What?**
- [x] package github.com/libp2p/go-libp2p-crypto is deprecated: use github.com/libp2p/go-libp2p-core/crypto instead.
- [x] package github.com/libp2p/go-libp2p-host is deprecated: use github.com/libp2p/go-libp2p-core/host instead.
- [x] package github.com/libp2p/go-libp2p-net is deprecated: use github.com/libp2p/go-libp2p-core/network instead.
- [x] package github.com/golang/protobuf/jsonpb is deprecated: Use the "google.golang.org/protobuf/encoding/protojson" package instead.

**Where?**
https://github.com/prysmaticlabs/prysm/blob/master/tools/relaynode/relaynode.go
https://github.com/prysmaticlabs/prysm/blob/master/tools/bootnode-query/main.go
https://github.com/prysmaticlabs/prysm/blob/master/beacon-chain/db/kafka/export_wrapper.go

**What is the problem?**
There is no problem here. The analysis includes some other warnings related to the old packages but they go away after the update. The last warning needs some small additional refactoring.

**Comment by rauljordan** [comment]
For the switch to the new protobuf package, tried to update it a while back but ran into issues. To fix the compilation errors, one has to convert our message types into MessageV2 protobufs: https://godoc.org/github.com/golang/protobuf/proto#MessageV2. However, there is some issue in dependencies that prevented us from doing so. It might be a pain to go through this route.

Regarding logging, that action item might fall under this open issue https://github.com/prysmaticlabs/prysm/issues/6317.

Not sure about the WithDialer issue, we might have to look at modern examples to see how they do this, or perhaps their godocs.

**Comment by rauljordan** [comment]
hey @rkapka this one is still relevant. My deps update PR #7646 only updates bug fix or security vulnerabilities in dependencies, but we still have to amend the Prysm code in this issue that uses deprecated package members

**Comment by prestonvanloon** [comment]
Removing from v1 milestone since it's not a release blocker.
