### ISSUE TITLE
Feature Flag Tracking: enablePeerScorer

### ISSUE THREAD

**Issue by farazdagi** [prysmaticlabs/prysm#6980]
# 🦄 Feature Tracking

**Current status** (opt-in or opt-out): 
- opt-in

**Opt-in feature flag name**:
`--enable-peer-scorer`

**Opt-out feature flag name**: 
`--disable-peer-scorer`

### Feature Description
Enables peer scoring (capturing peer performance and exposing single value capturing different metrics).

### Tasks

- [x] Feature flag created as opt-in #6709
- [x] Feature implemented / code complete
- [x] Feature tested in production for adequate amount of time
- [ ] Feature flag is inverted to be opt-out and the opt-in flag is deprecated
- [ ] Feature has made it to a tagged production release as an opt-out flag
- [ ] Opt-out feature flag is deprecated and old code paths are cleaned up

This issue should be closed after all of the above tasks are complete.

**Comment by rauljordan** [comment]
Peer scoring is enabled by default in 2.1.4
