### ISSUE TITLE
Support local protection data interchange format

### ISSUE THREAD

**Issue by shayzluf** [prysmaticlabs/prysm#7196]
# 💎 Issue

### Background

in order to support validators to seamlessly migrate to and from prysm we have to support the [protection db data interchange
](https://hackmd.io/@sproul/Bk0Y0qdGD)
### Description
this is the list of steps to be taken:

- [x] create a new proposal schema update #7197
- [x] create a new attestation schema update #7248
- [x] support migration of data from old schema to new schema #7430
- [x] use the new schema for local protection #7518 
- [ ] validate in runtime
- [ ] support full yaml version data import
- [ ] support full yaml version data export
- [ ] add minimal protection method
- [ ] support minimal yaml version data import

**Comment by michaelsproul** [comment]
EIP-3076 is now the canonical reference for the format: https://eips.ethereum.org/EIPS/eip-3076

I also need input from Prysm on some decisions here: https://ethereum-magicians.org/t/eip-3076-validator-client-interchange-format-slashing-protection/4883/2

**Comment by rauljordan** [comment]
Closing in favor of #7813
