### ISSUE TITLE
Feature Flag Tracking: --use-check-point-cache

### ISSUE THREAD

**Issue by terencechain** [prysmaticlabs/prysm#7239]
# 🦄 Feature Tracking

**Current status** (opt-in or opt-out): 

**Opt-in feature flag name**:

**Opt-out feature flag name**: 

### Feature Description

`--use-check-point-cache` is a superior implementation comparing to the current attestation check point state cache. It uses 50% less memory and is a life saver at long epochs without finality periods

### Tasks

- [x] Feature flag created as opt-in
- [x] Feature implemented / code complete
- [x] Feature tested in production for adequate amount of time
- [ ] Feature flag is inverted to be opt-out and the opt-in flag is deprecated
- [ ] Feature has made it to a tagged production release as an opt-out flag
- [ ] Opt-out feature flag is deprecated and old code paths are cleaned up

This issue should be closed after all of the above tasks are complete.

**Comment by terencechain** [comment]
No longer relevant
