### ISSUE TITLE
Feature Flag Tracking: --batch-block-verify

### ISSUE THREAD

**Issue by terencechain** [prysmaticlabs/prysm#7243]
# 🦄 Feature Tracking

**Current status** (opt-in or opt-out): 

**Opt-in feature flag name**:

**Opt-out feature flag name**: 

### Feature Description

`--batch-block-verify` is a better initial syncing algorithm than the current naive initial syncing algorithm. This allows batch verification of beacon chain objects which improves the syncing speed.

### Tasks

- [x] Feature flag created as opt-in
- [x] Feature implemented / code complete
- [x] Feature tested in production for adequate amount of time
- [x] Feature flag is inverted to be opt-out and the opt-in flag is deprecated
- [x] Feature has made it to a tagged production release as an opt-out flag
- [x] Opt-out feature flag is deprecated and old code paths are cleaned up

This issue should be closed after all of the above tasks are complete.

**Comment by terencechain** [comment]
Completed in latest release
