### ISSUE TITLE
Align to v0.12.3

### ISSUE THREAD

**Issue by terencechain** [prysmaticlabs/prysm#7274]
Opening this to track `v0.12.3` changes. This is 100% backwards compatible with `v0.12.x`

Beacon chain
- [x] Add configuration -- PROPORTIONAL_SLASHING_MULTIPLIER -- for slashing multiplier (https://github.com/ethereum/eth2.0-specs/pull/2034)
- [x] [non-substantive] Add clarifying comment for genesis skip conditions (https://github.com/ethereum/eth2.0-specs/pull/1999)

Fork choice
- [x] [non-substantive] Pass anchor_block to get_forkchoice_store (https://github.com/ethereum/eth2.0-specs/pull/2061)

Validator
- [x] [non-substantive] Clarify what state is for block proposals in validator guide (https://github.com/ethereum/eth2.0-specs/pull/2022)

Networking
- [x] Add self-consistency checks to attestation gossip validation (https://github.com/ethereum/eth2.0-specs/pull/2001)
- [x] Add two more simple gossip validations (https://github.com/ethereum/eth2.0-specs/pull/2030)
- [x] Use raw SHA256 as message-id and reduce size to 8 bytes (https://github.com/ethereum/eth2.0-specs/pull/2044)

Simple Serialize
- [x] [non-substantive] Clarify offsets serialization (https://github.com/ethereum/eth2.0-specs/pull/2043)

BLS
- [x] [non-substantive] Bump IETF BLS standard version to -03 (https://github.com/ethereum/eth2.0-specs/pull/2051)

I'm neglecting the wss changes since we already are tracking that separately
