### ISSUE TITLE
Trail of Bits audit tracking

### ISSUE THREAD

**Issue by terencechain** [prysmaticlabs/prysm#7410]
This tracks the progress on audit resolutions, we will update this through out the duration of the audit:

- [x] 1. Failure to propagate errors in beacon-chain #7246
- [x] 2. Data race in featureconfig #7406
- [x] 3. Context leak in validator client #7405
- [x] 4. Variable shadowing in beacon-chain history regeneration code #7308
- [x] 5. Data race in beacon-chain syncing code #7682
- [x] 6. Failure to error check could cause undefined behavior #7398 #7403
- [x] 7. Improvements needed to Bazel end-to-end testing documentation
- [x] 8. Raw password logged #7404 
- [x] 9. Dependencies are out of date #7646
- [x] 10. Code relies on two dependencies with OSS advisories #7646
- [x] 11. Overwrite of powchain.Service.preGenesisState even when deposits cannot be processed #7681
- [x] 12. Excessive memory usage by snappy.Decode _(Invalid, see reason below)_
- [x] 13. Improper use of recover in hashutil.HashProto #7683
- [x] 14. Improper use of recover in powchain.Service #7435
- [x] 15. Premature loop exit causes validator deposits to be missed #7678
- [x] 16. Proposer indices cannot be retrieved from cache #7442
- [x] 17. Shuffled list is not added to cache if proposer indices are present #7442
- [x] 18. Inefficiencies surrounding use of cache #7442
- [x] 19. Wrong domain used in helpers.SlotSignature #7447
- [x] 20. Wrong loop exit condition in store.ForkChoice.AncestorRoot #7226
- [x] 21. Handler on_tick unimplemented (we dont have a ticker, the slot advances as block comes in)
- [x] 22. Hardcoded contract bytecode
- [x] 23. Files and directories created with os.MkdirAll and ioutil.WriteFile are not ensured to have correct permissions #7685
- [x] 24. Response body not closed in tests #7450
- [x] 25. Password guesses should be limited to prevent brute force
- [x] 26. Premature exit under certain conditions in blockchain.Service.ancestor

**Comment by terencechain** [comment]
For 12, we actually can not use `MaxGossipSize` (1MB)  to safe guard against decode in `db/kv`. Reason being db decodes beacon state which is not a gossip object. Currently a medalla beacon state is 30MB

**Comment by rkapka** [comment]
Related with 9: #6891

**Comment by rauljordan** [comment]
Working on
9. Dependencies are out of date
10. Code relies on two dependencies with OSS advisories
22. Hardcoded contract bytecode
23. Files and directories created with os.MkdirAll and ioutil.WriteFile are not ensured to have correct permissions
24. Response body not closed in tests

**Comment by terencechain** [comment]
> 24. Response body not closed in tests

24 is addressed in #7450

**Comment by rauljordan** [comment]
Regarding: 25. Password guesses should be limited to prevent brute force
Won't fix because there is no reliable way to enforce password guesses. If we add some file that marks how long a user is locked out of password attempts, the attacker can just remove that file and keep brute forcing. Moreover, passwords are now forced to have stricter requirements

**Comment by rauljordan** [comment]
22: Won't fix as it does not affect any dependencies nor behavior of eth2 in mainnet. We do want to get rid of the deposit contract code eventually so we only promote the canonical eth2 deposit contract repo

**Comment by rauljordan** [comment]
7 has been fixed, auditors were eventually able to run e2e tests normally
