### ISSUE TITLE
Observed Data Races In Prysm

### ISSUE THREAD

**Issue by nisdas** [prysmaticlabs/prysm#7412]
# 🐞 Bug Report

### Description

This tracks the current data races observed in prysm during runtime. 

### Has this worked before in a previous version?

N.A

## 🔬 Minimal Reproduction

N.A

## 🔥 Error

Data Race 1:

- [x] Observed at startup when subscribing for subnets:
[Sync Race 2.txt](https://github.com/prysmaticlabs/prysm/files/5316398/Sync.Race.2.txt)

Data Race 2:

- [x] Observed when setting head after processing a block:

[Sync Race 3.txt](https://github.com/prysmaticlabs/prysm/files/5316403/Sync.Race.3.txt)

Data Race 3:

- [x] Observed when recomputing field trie:

[Sync Race 4.txt](https://github.com/prysmaticlabs/prysm/files/5316409/Sync.Race.4.txt)

Data Race 4:

- [x] Observed when calling our sync checker to check the current status

[Sync Race 5.txt](https://github.com/prysmaticlabs/prysm/files/5316421/Sync.Race.5.txt)
 
Data Race 6:

- [x] Observed when starting up

[Sync Race 6.txt](https://github.com/prysmaticlabs/prysm/files/5316451/Sync.Race.6.txt)

Data Race 7:

- [x] Observed with BLST Signature Verification

[Sync Race 7.txt](https://github.com/prysmaticlabs/prysm/files/5316697/Sync.Race.7.txt)

Data Race 8:

- [x] Similar to the ones shown above, this pops up in Aggregate Signature Verification

[Sync Race 8.txt](https://github.com/prysmaticlabs/prysm/files/5316857/Sync.Race.8.txt)

Data Race 9:

- [x] This one comes up in forkchoice while processing an attestation

[Sync Race 9.txt](https://github.com/prysmaticlabs/prysm/files/5316867/Sync.Race.9.txt)

Data Race 10:

- [x] This one comes up in forkchoice while computing deltas 

[Sync Race 10.txt](https://github.com/prysmaticlabs/prysm/files/5316873/Sync.Race.10.txt)

Data Race 11:

- [x] The comes up with multiple routines updating the head concurrently.

[Sync Race 11.txt](https://github.com/prysmaticlabs/prysm/files/5316934/Sync.Race.11.txt)

Data Race 12:

- [x] Another data race in forkchoice while updating best child.

[Sync Race 12.txt](https://github.com/prysmaticlabs/prysm/files/5316951/Sync.Race.12.txt)

Data Race 13:

- [x] Data Race at startup in the validator client.

[Sync Race 13.txt](https://github.com/prysmaticlabs/prysm/files/5316994/Sync.Race.13.txt)

**Comment by terencechain** [comment]
#7423 resolves bullet point 2

**Comment by terencechain** [comment]
#7426 resolves bullet points 9, 10, 11, 12

**Comment by rauljordan** [comment]
Update, found this data race triggered many times after initial sync

![Uploading Screen_Shot_2020-11-10_at_11.33.12_AM.png…]()

**Comment by rauljordan** [comment]
Data Race 1 was due to p2p.GossipTypeMappings which discussed offline is OK as we never write to that map

**Comment by rauljordan** [comment]
13 is an issue in the internal grpc logger package that is not a big deal for Prysm, we can ignore
