### ISSUE TITLE
[Mega tracking] - 🦄 Standard Eth2 APIs Implementation

### ISSUE THREAD

**Issue by 0xKiwi** [prysmaticlabs/prysm#7510]
### 💎 Feature Description
This is a mega tracking issue for progress on the standardized Eth2 API endpoints here: https://ethereum.github.io/eth2.0-APIs/

Any new services should be placed in a temporary `${SERVICE}v1` folder to not cause renames in the entire repo.

### EthereumAPIs protos
- [x] `beacon` endpoints protos
- [x] `config` endpoints protos
- [x] `debug` endpoints protos
- [x] `events` endpoints protos
- [x] `node` endpoints protos
- [x] `validator` endpoints protos

#### Beacon endpoints
- [x] `/eth/v1/beacon/*` endpoints outline #7408 
- [x] `/eth/v1/beacon/genesis` endpoint #8380 
- [x] `/eth/v1/beacon/states` endpoints #8402 #8456 #8476  #8896
- [x] `/eth/v1/beacon/headers` endpoints #7433
- [x] `/eth/v1/beacon/blocks` endpoints #7433
- [x] `/eth/v1/beacon/pool` endpoints #7525 #8492 #8508 #8515 #8532 #8902

#### Config endpoints
- [x] `/eth/v1/config/*` endpoints outline #7408
- [x] `/eth/v1/config/fork_schedule` endpoint #8345 
- [x] `/eth/v1/config/spec` endpoint #8328 
- [x] `/eth/v1/config/deposit_contract` endpoint #8316 

#### Debug endpoints
- [x] `/eth/v1/debug/*` endpoints outline #8496 
- [x] `/eth/v1/debug/beacon/states/{state_id}` endpoint #8631
- [x] `/eth/v1/debug/beacon/heads` endpoint #8675

#### Events endpoints
- [x] `/eth/v1/events` endpoint #9001 

#### Node endpoints
- [x] `/eth/v1/node/*` endpoints outline #7522
- [x] `/eth/v1/node/identity` endpoint #8230 
- [x] `/eth/v1/node/peers` endpoint #8288
  - [x] verify if string --> enum conversion works out of the box
- [x] `/eth/v1/node/peers/{peer_id}` endpoint #8264 
- [x] `eth/v1/node/peer_count` endpoint #8306
- [x] `/eth/v1/node/version` endpoint #8207
- [x] `/eth/v1/node/syncing` endpoint #8241
- [x] `/eth/v1/node/health` endpoint #8217 

#### Validator endpoints
- [x] `/eth/v1/validator/*` endpoints outline #9174 
- [x] `/eth/v1/validator/duties/attester/{epoch}` endpoint #9207
- [x] `/eth/v1/validator/duties/proposer/{epoch}` endpoint #9223 
- [x] `/eth/v1/validator/blocks/{slot}` endpoint #9259 
- [x] `/eth/v1/validator/attestation_data` endpoint #9271 
- [x] `/eth/v1/validator/aggregate_attestation` endpoint #9243 
- [x] `/eth/v1/validator/aggregate_and_proofs` endpoint #9294 
- [x] `/eth/v1/validator/beacon_committee_subscriptions` endpoint #9318 

#### v2.0.0 endpoints
- [x] `​/eth​/v1​/beacon​/states​/{state_id}​/sync_committees` #9434
- [x] `/eth/v2/beacon/blocks/{block_id}` #9433
- [x] `​/eth​/v1​/beacon​/pool​/sync_committees` #9464
- [x] `​/eth​/v2​/debug​/beacon​/states​/{state_id}` #9506
- [x] `​/eth​/v1​/validator​/duties​/sync​/{epoch}` #9478
- [x] `​/eth​/v2​/validator​/blocks​/{slot}`
- [x] `​/eth​/v1​/validator​/sync_committee_subscriptions` #9498
- [x] `​/eth​/v1​/validator​/sync_committee_contribution`
- [x] `/eth/v1/validator/contribution_and_proofs`

#### Testing
- [ ] Integration tests (priority: low)
- [x] e2e conformance tests
- [x] e2e tests (priority: medium)

#### Miscellaneous 
- [x] Customize response codes [as shown here](https://grpc-ecosystem.github.io/grpc-gateway/docs/mapping/customizing_your_gateway/#controlling-http-response-status-codes)
- [x] Make enum values case insensitive
- [x] Remove unused fields from `Server` variables, add `span` to every method
- [x] Return enums as lowercase strings #8904
- [x] Some proto fields are not correct
- [x] Proto for `/node/syncing` does not contain the `is_syncing` field
- [x] Error response from `/beacon/pool/attestations` POST should include an additional `failures` field #8904
- [x] Handle top level JSON arrays in `/beacon/pool/attestations` POST #8904
- [x] Make proxy endpoint configurable #8904
- [x] `/debug/states/{state_id}`'s response is too big
- [x] `debug/states/{state_id}` should allow an SSZ-serialized response
- [x] Resolve review comments in https://github.com/prysmaticlabs/prysm/pull/8904
- [x] Allow query string to contain comma-separated values e.g. `id=1,2` (priority: medium)
- [x] Prepare documentation for users (priority: high)
- [x] Fix #9516 and #9531 (priority: high)
- [x] Add Version field to some response messages as per the spec (priority: high)
- [x] Run new endpoints through the API Middleware to make them conform to the spec (priority: high)
- [x] Prepare a developer wiki page (priority: medium)
- [x] Move all endpoints under a single port (priority: medium)
- [ ] Implement #9398 (priority: low)
- [ ] Allow to return custom errors from SSZ endpoints (priority: low)
- [ ] Error returned from `GET /pool/attestations` should not include the `failures` field (priority: low)
- [ ] Allow large return values without the need to set `--grpc-max-msg-size`. See discussion: https://discord.com/channels/476244492043812875/603588441741066241/850168955950727179 (priority: low)

This issue should be closed after all of the above tasks are complete.

**Comment by rkapka** [comment]
Working on Node.
