### ISSUE TITLE
[Mega tracking] - Security Improvements and More Robust Code

### ISSUE THREAD

**Issue by rauljordan** [prysmaticlabs/prysm#7514]
# 💎 Issue

### Background

This is a large tracking issue for improving the security of Prysm as well as enhance 

### Description

**High Level**
- [x] Resolve deep source analysis issues, especially those with bug risks attached to them
- [x] Resolve race detection issues with go test all across Prysm
- [x] Harden dependencies, update relevant ones which had bug fixes

**Repository Health**
- [x] Remove deprecated tools from the repository and clean up READMEs

**Go Code Improvements**
- [x] Complete integration of most go vetting tools, such as ineffassign along with important static analyzers for safety
- [ ] Reduce high amount of interface redundancy, making it difficult for outsiders to step in
- [ ] Make certain packages more "pure", akin to the core package. For example, we should isolate eth2-specific logic and code paths from service and business logic codepaths
- [ ] Many different variants of duplicated code: FuncWithNoBLSVerify, FuncWithBLSVerify, obfuscates the process to reason about for others
- [ ] Caches are mixed with important functions and should be more isolated, such as cache filling occurring somewhere different than where it was needed
- [ ] All cache keys should be audited to ensure they are used properly

**Accounts and Validator RPC**
- [x] Use a different password than the wallet password for logging in through the web interface for security purposes
- [x] No need to expose DefaultWalletPath endpoint, in-fact, such endpoint is not even needed
- [x] Logout should invalidate JWT in backend
- [x] JWT auth path should have more tests and should enforce a signing type provided by the token from the user
- [x] Consider not exposing the backup endpoint at all via RPC, as it is too high-risk if an attacker gains access
- [x] Disable account creation for non-HD wallets, and rename it to `imported` wallet to align with the web UI. For security reasons, this type of wallet should only be able to import external keystores
- [x] If someone has never signed up before, someone else could sign up for a staker if they gain access to the validator RPC 
- [x] Remove accounts-v1 in favor of accounts-v2 only
- [x] Slashing protection should be clear-cut and documented for users to understand its implications

**Comment by rauljordan** [comment]
It's hard to find a single resolution for this issue, as it mostly involves ongoing changes. Will instead focus on what's actionable in a new tracking issue for prysm v2.0.0
