### ISSUE TITLE
[Mega tracking] - Prysm Beta Release

### ISSUE THREAD

**Issue by rauljordan** [prysmaticlabs/prysm#7515]
# 💎 Issue

### Background

This is a large tracking issue for our breaking release, the Prysm beta release

### Description

- [ ] Remove feature flags for beta #7509 
- [ ] Remove accounts-v1
- [ ] Finish eth2 apis integration #7510 
- [ ] Align wallet derivation with the EIP-2335 updates
- [ ] Include slashing protection history in accounts-v2 backup
- [ ] Include legal waiver for users of Prysm that requires one-time confirmation
- [ ] Support local interchange slashing format #7196 
- [ ] Add docs for slasher

**Comment by rauljordan** [comment]
Beta.0 released https://github.com/prysmaticlabs/prysm/releases/tag/v1.0.0-beta.0
