### ISSUE TITLE
Feature Flag Tracking: enableSyncBacktracking

### ISSUE THREAD

**Issue by farazdagi** [prysmaticlabs/prysm#7734]
# 🦄 Feature Tracking

**Current status** (opt-in or opt-out): 
- `opt-in`

**Opt-in feature flag name**:
`--enable-sync-backtracking`

**Opt-out feature flag name**: 
`--disable-sync-backtracking`

### Feature Description

Turns on backtracking routine when init-sync works on block beyond the finalized epoch (alternative branches are explored).

### Tasks

- [x] Feature flag created as opt-in #7564
- [x] Feature implemented / code complete
- [x] Feature tested in production for adequate amount of time
- [x] Feature flag is inverted to be opt-out and the opt-in flag is deprecated #8034
- [x] Feature has made it to a tagged production release as an opt-out flag `tag: v1.10`
- [x] Opt-out feature flag is deprecated and old code paths are cleaned up #8371

This issue should be closed after all of the above tasks are complete.

**Comment by rauljordan** [comment]
Update on this one @farazdagi ?

**Comment by farazdagi** [comment]
Feature has been confirmed to work on pyrmont, will create an opt-out flag today.
