### ISSUE TITLE
Enable & Disable Account

### ISSUE THREAD

**Issue by fabdarice** [prysmaticlabs/prysm#7787]
# 🦄 Feature Tracking

**Current status** (opt-in or opt-out): 

**Opt-in feature flag name**:

**Opt-out feature flag name**: 

### Feature Description
The feature will allow users to enable and disable via command lines one or many validator keys.
Disabled validators will not be removed from the account wallet, but instead simply be inactive and will not perform any attestation, aggregation or block proposals.

This is particularly handy if a user is looking to migrate his keys to other clients or another server without having to `delete` and `import` again his keys.

### Tasks
- [x] Feature to disable accounts for imported accounts (#7746)
- [x] Feature to enable accounts for imported accounts(#7746)
- [ ] Distinguish disabled accounts from active ones (`accounts list`)
- [ ] Feature to disable accounts for derived accounts 
- [ ] Feature to enable accounts for derived accounts 
- [ ] `enable` and `disable` should have effect without requiring the user to restart their validator node

This issue should be closed after all of the above tasks are complete.

**Comment by fabdarice** [comment]
@rauljordan does your recent change de-activate disabled accounts without having to restart the node?
I didn't see anything in the `run()` of validator.client.runner.run()` that would remove disabled accounts even if the keystore are hot-reloaded by the watchers.
In my old PR #7820, I had to add a function that watches for only ACTIVE/EXITING status or the code will trigger an error as there are no slots assigned for duties.
