### ISSUE TITLE
[Tracking] - Standard Slashing Protection Interchange Functionality

### ISSUE THREAD

**Issue by rauljordan** [prysmaticlabs/prysm#7813]
# 💎 Issue

### Background

The objective of this issue is to define a clear path for Prysm to implement the eth2 client slashing protection interchange format defined by [EIP-3076](https://eips.ethereum.org/EIPS/eip-3076). The EIP now comes with conformity tests which we can ensure our client satisfies. We have written up a design document for this feature [here](https://docs.google.com/document/d/12SZgszMbfhUqwGukJWKQCOmoCa8nY8D3GtYEElgjEKk/edit#).

## v1.0.1 Schema and Foundations

- [x] Define the standard slashing format struct in Prysm #7675
- [x] Implement the import functions for the standard slashing format #7675
- [x] Add missing protection features (genesis validator root) #7864 and #7855 
- [x] Ensure we support optional signing roots in the interchange JSON import #7960
- [x] Support lowest and highest signed proposals in our DB #7957 

### Import and exporting
- [x] Implement the export proposal history functions for the standard slashing format #7964 
- [x] Implement the export attesting history functions for the standard slashing format #8027
- [x] Ensure slashing protection JSON cannot be imported into a running validator client (our boltdb lock might already enforce this)
- [x] Ensure we ask users for their slashing interchange json file upon importing keys into Prysm #7880
- [x] Include a command to export the standalone interchange JSON for all validators in the DB #8040
- [x] Validate whether proposer public keys we are importing is slashable with respect to other entries in the JSON file and prevent importing those entries #8031
- [x] Validate whether attester public keys we are importing is slashable with respect to other entries in the JSON file and prevent importing those entries #8051
- [x] Prevent running keys that were found to be slashable from the 2 previous bullet points

### Integrating invariants at runtime

> It’s possible for an interchange file to contain blocks and attestations that
are mutually slashable, i.e. the interchange file contains evidence that the
validator has already committed a slashable offence. It’s also possible for
an interchange to contain messages that are slashable with respect to ones already
in the database. Require implementations to import all validators that are not slashable,
and reject all that are slashable
- [x] Support lowest and highest signed proposals in our DB #7957 
- [x] Add test to ensure slashing protection allows genesis attestations to go through #7977
- [x] Ensure lowest signed source / target epoch getters return a boolean indicating if they exist in our database #8004
- [x] Ensure lowest signed proposal getters return a boolean indicating if they exist in our database #8020
- [x] Support the invariant below:
> Refuse to sign any block with slot <= min(b.slot for b in data.signed_blocks if b.pubkey == proposer_pubkey), except if it is a repeat signing as determined by the signing_root. #8067
- [x]  Support the invariant below #7966
> Refuse to sign any attestation with source epoch less than the minimum source epoch present in that signer’s attestations (as seen in data.signed_attestations)
- [x] Migrate attesting history with unattested epochs to FAR_FUTURE_EPOCH #8121

### Testing and docs
- [x] Include the [conformity test vectors](https://github.com/eth2-clients/slashing-protection-interchange-tests) and ensure Prysm passes the tests #7858
