### ISSUE TITLE
[Tracking] - Prysm Mainnet Week

### ISSUE THREAD

**Issue by rauljordan** [prysmaticlabs/prysm#7903]
# 💎 Issue

### Background

This is a tracking issue for all our related priorities this upcoming week now that Prysm v1 has a release candidate and we must prepare for launch.

- [x] Create v1.1.0 branch and merge larger features into this branch instead of master (specifically, revamp of validator slashing protection and anything that is non-trivial) 
- [x] Everyone needs to comb through everything
- [x] Review flag usage help text
- [x] Review docs site pages
- [x] Review github issues
- [x] Review markdown files in the monorepo #7910
- [x] Remove old tools #7912
- [x] Review WARNING/ERROR level logs

**Comment by terencechain** [comment]
I'm working on `Review WARNING/ERROR level logs` across Prysm's beacon chain and validator repo. If someone can take slasher that'd be great
