### ISSUE TITLE
[Tracking] - Integrating Slashing Protection Invariants

### ISSUE THREAD

**Issue by rauljordan** [prysmaticlabs/prysm#8052]
As a follow-up to #7813, we want to ensure we enforce some strong invariants recommended by EIP-3076 after slashing protection data is imported into the validator client. Given this is high risk to include in a minor semver patch, we need to test it for a while and will be separate from #7813, which is safe to go in a minor patch release.

- [ ] Support the invariant below:
> Refuse to sign any block with slot <= min(b.slot for b in data.signed_blocks if b.pubkey == proposer_pubkey), except if it is a repeat signing as determined by the signing_root.
- [ ]  Support the invariant below #7966
> Refuse to sign any attestation with source epoch less than the minimum source epoch present in that signer’s attestations (as seen in data.signed_attestations)
- [ ] Allow resubmission of blocks with the same signing root in slashing protection #7866

If there is a problem with the code above, we can prevent all prysm validators from attesting or proposing, so great care must be taken with this feature.

**Comment by rauljordan** [comment]
After discussion offline, closing and moving back to #7813
