### ISSUE TITLE
[Tracking] Custom basic types

### ISSUE THREAD

**Issue by farazdagi** [prysmaticlabs/prysm#8205]
# 💎 Issue

### Background
- There has been an intensive discussion whether benefits of wrapping custom types (`Epoch`, `Slot`, `Shard` etc, see [specs](https://github.com/ethereum/eth2.0-specs/blob/dev/specs/phase0/beacon-chain.md#custom-types) for more types) into their dedicated Golang types outweigh drawbacks, eventually settling for enabling this after the mainnet release.
- For more details on an attempt to have custom types (with pros/cons listed in the PR description) see #7536

### Description
- [x] Make sure previous PR works on top of the `develop` branch we produced after the mainnet release
  - [x] Everything builds (both using `bazel build` and `go build`)
  - [x] All tests do pass
  - [x] Protobufs are updated
  - [x] ssz generated objects are updated
- [x] Introduce first custom types (introduce in separate PRs):
  - [x] `Epoch` #8373
  - [x] `Slot` #8408
  - [x] `CommitteeIndex`
  - [x] `ValidatorIndex` #8478
  - [ ] `Root`
  - [ ] `Domain` and `DomainType`
  - [ ] `ForkDigest`
  - [ ] `BLSPubkey` and `BLSSignature`

**Comment by rauljordan** [comment]
Done!

**Comment by farazdagi** [comment]
Reopening, as this was meant an issue to track all types (not only `Slot`, `Epoch`).

**Comment by rauljordan** [comment]
Roots seem to have a fundamental problem, along with the other types mentioned which are fixed-size arrays. CC @rkapka, perhaps it might not be feasible to add those to eth2-types, and we might need to close this issue. Your call

**Comment by rkapka** [comment]
@rauljordan I think it might still be valuable to add these custom types. Even though it will not be possible to catch wrong array size at compile time, it will guard against mistakenly mixing up types.

**Comment by terencechain** [comment]
I don't think we'll do rest of the custom data type so it's better to close this for now
