### ISSUE TITLE
[Tracking] - Optimized Slasher Redesign

### ISSUE THREAD

**Issue by rauljordan** [prysmaticlabs/prysm#8331]
# 💎 Issue

## Background

The objective of this issue is to define a clear path for Prysm to implement an optimized implementation of slasher based on our design document [here](https://hackmd.io/@Yl0VNGYRR6aeDrHHQNhuaA/rkvKcTNJO). Our current slasher is untenable and has been unmaintained for a while. To support the growing numbers of validators and create a future-proof solution, we need to redesign it from the ground up.

This issue tracks the completion of the different steps required to make this happen.

## Foundations

- [x] Define a slasher as a beacon node service, subscribing to an event feed of indexed attestations #8335
- [x] Define the configuration parameters for the slasher service, with comprehensive comments and package level godocs #8335
- [x] Define a `Chunker` interface and structs which meet the interface for MinSpans and MaxSpans #8350 
- [x] Define the necessary DB schema and methods  #8342 

## Implementation

- [x] Implement the `Chunker` interface for min spans #8350 
- [x] Implement the `Chunker` interface for max spans #8358 
- [x] Implement the ingestion and preprocessing of indexed attestations from an event feed
- [x] Implement a mock indexed attestation generator for testing
- [x] Implement the detection process for incoming batches of attestations using the chunker interface for min and max spans'
- [x] Implement double vote detection
- [x] Implement double proposal detection
- [x] Implement ability to defer valid attestations from the future for future processing
- [x] Implement pruning for old attestation records
- [x] Implement compression for chunks on disk
- [x] Integrate slasher into the beacon node runtime, ensuring the beacon node sends it signed indexed attestations and signed beacon blocks (WIP)
- [x] Implement the slasher gRPC endpoints
- [x] Remove the old slasher codebase
- [x] Create documentation for how to run slasher

## Tests & Benchmarks

- [x] Implement comprehensive integration tests and unit tests for the feature
- [x] Run simulations for N validators, M epochs, with different frequencies of received indexed attestations and observe performance both on CPU, memory, and disk I/O
- [x] Integrate the slasher simulator into e2e
- [x] Run in Pyrmont, measure baseline CPU and RAM use and disk space usage
- [x] Create manifests to run slasher in k8s
- [x] Announce by next release that within a few releases, we will be deprecating and removing the old slasher from the codebase
- [x] Ensure remote slashing protection works in the Prater testnet
- [x] Ensure DB use is reasonable on mainnet and in testnets

**Comment by rauljordan** [comment]
Done!
