### ISSUE TITLE
[Tracking] Dynamic Reload of Validator Keys

### ISSUE THREAD

**Issue by rkapka** [prysmaticlabs/prysm#8572]
This tracking issue is a follow-up to the [Dynamic Reload of Validator Keys design doc](https://docs.google.com/document/d/1fLdUi6AHQ5-wYOy6DCzW5JlLlq3VuI275-KoyEZ2Pmw).

### Imported/Derived wallet
- [x] Start with an active key, import an active key #8585 
- [x] Start with an active key, import an inactive key #8585 
- [x] Start with an inactive key, import an active key #8558 
- [x] Start with an inactive key, import an inactive key #8558
- [x] Start with one active and one inactive key, delete the active key #8585 
- [x] Start with one active and one inactive key, delete the inactive key #8585 
- [x] Start with any keys, delete all of them #8585 
### Remote wallet
- [x] Make all scenarios listed in the doc's table work for the remote wallet #8611 
### General
- [ ] Refactor `WaitForActivation` so that it does not require fetching keys that we already have.
