### ISSUE TITLE
Altair HF1 Tracking

### ISSUE THREAD

**Issue by terencechain** [prysmaticlabs/prysm#8638]
# Altair(HF1) Official Tracking

# Detailed tracking
#### Protobuf definitions EthereumAPI
- [x] Beacon block Altair https://github.com/prysmaticlabs/ethereumapis/pull/234
- [x] Beacon state Altair #8581 #8641 
- [x] Sync aggregate https://github.com/prysmaticlabs/ethereumapis/pull/234
- [x] Sync committee #8581 #8641
- [x] Validator sync committee signature containers
   - [x] `SyncCommitteeSigningData` in types.proto #8870
   - [x] Rest is in ethereumAPI  https://github.com/prysmaticlabs/ethereumapis/pull/237

#### Protobuf definitions Eth2API
- [x] Beacon block Altair https://github.com/prysmaticlabs/ethereumapis/pull/230
- [x] Beacon state Altair
- [x] Sync aggregate
- [x] Sync committee

#### Custom type
- [x] Go-bitfield: Bitvector[SYNC_COMMITTEE_SIZE] https://github.com/prysmaticlabs/go-bitfield/pull/33
- [ ] Eth2-type: ParticipationFlags

### Altair configs
- [x] Mainnet #8642 
- [x] Minimal #8642 

### New beacon state pkg for Altair
- [x] Revamp beacon state phase0 pkg in anticipation of Altair #8533 #8544 #8552 #8589 #8609 #8615 #8620 #8630 #8633 #8650 #8705 #8704 #8698 #8696 #8653 #8767 #8773 #8781
- [x] Implement beacon state Altair pkg #8670 #8658 #8673 #8690 #8856
- [x] Test utility setup to initialize beacon state Altair #8716 

### Core processing pkgs
- [x] Genesis state init for interop and testing #8712 #8713  
- [x] Sync committees to support light clients #8717 #8721 #8728
- [x] New accounting reform #8461 #8729 #8731  #8753
- [x] New slashing parameters #8732
- [x] Per validator inactivity leak  #8753 #8762
- [x] New process block #8784
- [x] New process epoch #8772 #8797 #8841 #8857
- [x] New state transition #8796

### DB pkg
- [x] Signed beacon block Altair
- [x] Beacon state Altair
- [x] Handling Different Data Types For Phase 0/Altair Objects.

### Cache pkg
- [x] Sync committee indices cache #8884
- [x] Beacon state Altair

### Networking
- [x] Gossip Validation Addition
- [x] Beacon block gossip topic for new Altair type
- [x] Gossip For Sync Committee Aggregates
- [x ] Gossip Subnets for Sync Committee Contribution
- [x] Processing Path for Sync Committee Aggregate
- [x] Processing Path for Sync Committee Contribution
- [x] Refactoring RPC handles to take in context
- [x] Add in v2 Path for Req/Resp Topics. 
- [x] Fork Awareness Logic For Gossip/RPC(Req/Resp).
- [x] Registering For Sync Committee Subnets.
- [x] Adjusting Discovery For Different Forks.

### RPC
- [x] Validator sync committee assignments
- [x] Sync committee aggregates in beacon blocks
- [x] Block proposal for Altair

### Fork logic
- [x] Switch over Phase 0 beacon state to an Altair beacon state

### Weak subjectivity
- [x] New weak subjectivity period calculations and sample values

## ⭐ Validator
- [x] Helpers for RPC server in https://github.com/ethereum/eth2.0-specs/blob/dev/specs/altair/validator.md
- [x] Service definitions on ethereumapi
- [x] Proposer to package new beacon block body with sync aggregate
- [x] Attester to submit sync committee signature
- [x] Aggregator to aggregate sync committee signatures
- [x] Validator client must have fork awareness, we need design

## ⭐ Testing
- [x] Phase 0 spec tests clean up #8798 #8800 #8826
- [x] Altair spec tests
    - [x] Operations #8795
    - [x] Epoch #8806
    - [x] Rewards #8818 
    - [x] Sanity #8831
    - [x] SSZ static #8847
- [x] Duplicate e2e tests to cover hard fork code paths
- [x] E2E tests to cover the switch over in various hard fork combinations 

## ⭐ Misc
- [x] Merge our custom changes to fastssz into upstream to avoid using forks of the repo in go.mod

**Comment by terencechain** [comment]
Closing this. ` Eth2-type: ParticipationFlags` will be tracked in another issue
