### ISSUE TITLE
[Tracking] - Web UI V1 Backend Requirements

### ISSUE THREAD

**Issue by rauljordan** [prysmaticlabs/prysm#8664]
# 💎 Issue

### Background

We have been working towards revamping our Prysm web UI to version 1, which comes with a lot more useful features and user experience improvements for the usability of Prysm. Based on user research and aligned with the direction of Prysm as an eth2 client that encourages a good user experience, we are redefining the purpose of our web UI.

The purpose of the web UI is to be an **alternative to the CLI to manage Prysm and run validators**. It is **not** meant to be a block explorer by any means. This means we should stick to showing users information about their validators, their processes instead of showing greater information about the state of the network. We want to delegate this info as much as possible to block explorers. The web UI is meant to be **functional**. That is, we want easy access to the key actions a user can take and the key data a user wants to see right away.

To accomplish this, more work needs to be done in the frontend as it involves design work as well. However, there is important backend work to be done.

### Description

- [x] Wallet recover requests should add in a `language: string` property which allows users to pick a bip39 standard language for recovering their wallet from a mnemonic
- [x] Add back the delete accounts RPC endpoints, previously reverted from Prysm
- [x] Add an accounts voluntary-exit endpoint `/v2/validator/accounts/voluntary-exit`
- [x] Add slashing protection import/export endpoints `/v2/validator/slashing-protection/import` and `export`
- [x] Embed the built web UI using go1.16 file embed features

The required request types for these items above can be found [here](https://github.com/prysmaticlabs/prysm-web-ui/blob/2190e45f1ce4ce1613073d8eb198f19b702bc6e2/src/app/proto/validator/accounts/v2/web_api.ts#L219)

**Comment by ahadda5** [comment]
Starting with the Wallet recover request, is it safe to say that the `RecoverWallet `  func needs to validate the new property against the bip39 bip-0039-wordlists.md import? 
Also  If that new parameter (flag) is not specified it is defaulted to 'English'.

**Comment by ahadda5** [comment]
For the delete accounts it was removed part of  [This Commit](https://github.com/prysmaticlabs/prysm/pull/7676) 
I'll revert it back

**Comment by ahadda5** [comment]
For the voluntarily exit I'm getting this. I stopped my validator, kept the beacon(running on the same machine) running to broadcast. 

```
>./prysm.sh validator accounts voluntary-exit
Latest Prysm version is v1.3.4.
Validator is up to date.
Verifying binary integrity.
validator-v1.3.4-linux-amd64: OK
gpg: Signature made 22 مار, 2021 07:16:22 م +04
gpg:                using RSA key 0AE0051D647BA3C1A917AF4072E33E4DF1A5036E
gpg: Good signature from "Preston Van Loon <preston@prysmaticlabs.com>" [unknown]
gpg: WARNING: This key is not certified with a trusted signature!
gpg:          There is no indication that the signature belongs to the owner.
Primary key fingerprint: 0AE0 051D 647B A3C1 A917  AF40 72E3 3E4D F1A5 036E
Verified /home/ahaddad/prysm/dist/validator-v1.3.4-linux-amd64 has been signed by Prysmatic Labs.
Starting Prysm validator accounts voluntary-exit
[2021-03-29 18:11:08]  WARN flags: Running on ETH2 Mainnet
[2021-03-29 18:11:08]  INFO prompt: (wallet path) /home/ahaddad/.eth2validators/prysm-wallet-v2
Wallet password: 
Done with selections
Are you sure you want to perform a voluntary exit on 0 accounts? () Y/N:
y
===============IMPORTANT===============
Withdrawing funds is not possible in Phase 0 of the system. Please navigate to the following website and make sure you understand the current implications of a voluntary exit before making the final decision:
https://docs.prylabs.network/docs/wallet/exiting-a-validator/#withdrawal-delay-warning
If you still want to continue with the voluntary exit, please input a phrase found at the end of the page from the above URL:
Exit my validator
[2021-03-29 18:17:47]  WARN validator: You are using an insecure gRPC connection. If you are running your beacon node and validator on the same machines, you can ignore this message. If you want to know how to enable secure connections, see: https://docs.prylabs.network/docs/prysm-usage/secure-grpc
[2021-03-29 18:17:47]  INFO accounts: No successful voluntary exits
```

**Comment by c1cio** [comment]
What has been closed?
