### ISSUE TITLE
Add support for beaconcha.in style metrics tracking

### ISSUE THREAD

**Issue by kasey** [prysmaticlabs/prysm#8833]
# 🦄 Feature Tracking

**Current status** (opt-in or opt-out): opt-in

**Opt-in feature flag name**: This feature runs as a separate process. for example to collect metrics from a beacon-node process running locally:
```
go run github.com/prysmaticlabs/prysm/cmd/client-stats --beacon-node-metrics-url=http://localhost:8080/metrics --scrape-interval=1 --clientstats-api-url=https://beaconcha.in/api/v1/stats/{apikey}/{machineName}`
```
### Feature Description

The beaconcha.in Client Stats Proposal describes an HTTP endpoint that enables collection of metrics for validators, beacon nodes, slashers, and the systems where those processes run, so that operators of nodes can obtain some basic monitoring and observability capabilities from the beaconcha.in service.

Values will be obtained by scraping the existing prometheus exposition format data exposed by beaconnode and validator processes (by default on ports 8080 and 8081 respectively). The code to scrape values and push to the aggregation API will run in a separate process, possibly on a separate host. This ensures maximum privacy and a very clear choice on the part of the user to opt-in to this service. Additional metrics exposed on the existing prometheus port for this feature are low-level details about the running processes, and will not create additional privacy concerns for users.

### Tasks

- [x] Feature flag created as opt-in
- [x] Feature implemented / code complete
- [ ] Feature tested in production for adequate amount of time
- [ ] Feature flag is inverted to be opt-out and the opt-in flag is deprecated
- [ ] Feature has made it to a tagged production release as an opt-out flag
- [ ] Opt-out feature flag is deprecated and old code paths are cleaned up

This issue should be closed after all of the above tasks are complete.

**Comment by kasey** [comment]
Broke this PR up into 2 parts https://github.com/prysmaticlabs/prysm/pull/8834 and https://github.com/prysmaticlabs/prysm/pull/8835
