### ISSUE TITLE
[Tracking] - Eth PoW to PoS Merge

### ISSUE THREAD

**Issue by rauljordan** [prysmaticlabs/prysm#9278]
# 💎 Issue

### Background

Ethereum is migrating completely to proof of stake. Phase 0 of proof of stake already launched in December 1st, 2020, but it is running as a separate chain today. Sometime early 2022, there will be a transition process in which the current Ethereum chain, with all its smart contracts and applications, will migrate to run using the consensus of the beacon chain using proof of stake. There is a lot of work to do on this front and we can get started by tracking some of the highest priorities in this Github issue.

Today, we do have a [Merge Mainnet Readiness Checklist](https://github.com/ethereum/pm/blob/master/Merge/mainnet-readiness.md) which outlines the high-level tasks by domain, such as by execution clients (go-ethereum), consensus clients (prysm), R&D, and testing. This checklist, although valuable, does not give us a good idea of priorities for our team in the coming months. This issue will be ordering action items by **priority**.

In the meantime while we work on Altair, team should be reading the [latest merge specification](https://github.com/ethereum/eth2.0-specs/tree/dev/specs/merge) carefully.

### Priorities

**Pre-Preparation Stage** 
- [ ] Merge Altair `hf1` branch into `develop` #9123 
- [ ] Rebase the `merge` branch of Prysm develop once Altair is merged

**Latest Specification**
- [ ] Review the diff in our `merge` branch compared to the [latest merge specification](https://github.com/ethereum/eth2.0-specs/tree/dev/specs/merge)
- [ ] Begin implementing the [transition total difficulty process](https://github.com/ethereum/eth2.0-specs/pull/2462) which solves an attack vector during the merge transition where eth2 could be enshrining a chain with a low difficulty. Instead, we want to enshrine the current Ethereum chain, which has a higher difficulty than any malicious fork of Ethereum would'

**Implementation Details**
- [ ]  Implement all the required API endpoints for the `merge` and decide with other teams on whether or not this should be JSON-RPC, REST API, websockets, or something else. Execution and consensus clients will be communicating synchronously via RPC, so this is a critical component that has not had enough discussion.
- [ ] Work on code review and design discussions with the go-ethereum team for their required action items for the merge

**Testing and Community Awareness**
- [ ] Pass all merge spec tests
- [ ] End to end tests for the merge transition process. Our e2e suite contains an eth1 node, so we should be able to test this out ourselves in our testing suite
- [ ] Launch a single client public testnet for the community to try our Ethereum with proof of stake
- [ ] Publish documentation and updates on merge work to the community

**Comment by terencechain** [comment]
Already tracking this on notion and the project board
