### ISSUE TITLE
Merge interop tracking

### ISSUE THREAD

**Issue by terencechain** [prysmaticlabs/prysm#9716]
This issue tracks the necessary tasks required to support merge interop. The working branch is on [merge-oct](https://github.com/prysmaticlabs/prysm/tree/merge-oct)

- [x] Update bazel-go-ethereum to latest catalyst commit
- [x] Implement newly added execution payload, header and beacon state protobuf types
- [ ] Implement SSZ support for the new types
- [x] Implement beacon chain merge functions
- [x] Implement beacon state trie for merge
- [x] Implement cli flags related to merge features (ie client settings, fee recipient... etc)
- [x] Implement merge spec vector test framework
- [x] Implement db support for merge version block and state 
- [x] Add execution engine calls into beacon node run time
    - [x] prepare payload
    - [x] get payload
    - [x] execute payload
    - [x] consensus validated
    - [x] forkchoice updated
- [x] Implement modified merge version of `BeaconBlocksByRange` and `BeaconBlocksByRoot`
- [x] Implement merge topics subscription
