### ISSUE TITLE
Reduce DB size 

### ISSUE THREAD

**Issue by jmozah** [prysmaticlabs/prysm#9962]
# 💎 Issue

### Background

The issue is to track the reduction of DB size in beacon node.

### Description
The database size of our beacon node is increasing day by day.  
The rate at which we are growing in size is more than what we have seen in Execution Layers. 
This issue is to reformat the DB tables to optimize for size reduction

- [ ] Create wrapper over BeaconState to add metadata #9963
- [ ] Add subcommand to convert old DB (db that didn't enable efficient historical flag) to new format
- [ ] Add subcommand support for migrated DB to the new format
- [ ] Add subcommand support for circular buffers conversions to new  DB format
- [ ] Add changes to read the new DB formats while constructing the state from these new tables

**Comment by terencechain** [comment]
Outdated
